### ISSUE TITLE
ROS2 Iron release

### ISSUE THREAD

**Issue by Serafadam** [introlab/rtabmap_ros#1011]
Hi,
I wanted to ask if there are plans to release RTABMap packages for ROS2 Iron in near future?

**Comment by matlabbe** [comment]
Good question!

Coming in soon: 
* https://github.com/ros/rosdistro/pull/38163
* https://github.com/ros/rosdistro/pull/38164

**Comment by Serafadam** [comment]
Thanks!

**Comment by matlabbe** [comment]
Current status for IRON (available in nightly version of ros2, not yet in latest release): http://repo.ros2.org/status_page/humble_default.html?q=iron-rtabmap
