### ISSUE TITLE
Redundant line in code?

### ISSUE THREAD

**Issue by kojokaro** [introlab/rtabmap_ros#1022]
Hi Mathieu

I got a warning about this line (2061) - https://github.com/introlab/rtabmap_ros/blob/bc79e15b77e988fb42ff666a5f73b5d54cf71f73/rtabmap_slam/src/CoreWrapper.cpp#L2061C7-L2061C31

Is this just redundant or covariance need to be set to something here?

Thanks
Keren

**Comment by matlabbe** [comment]
The covariance is correctly set in the lines after, I think it was a wrong copy/paste that fell through the cracks. Thx for reporting!
