### ISSUE TITLE
Unable to create proper 2D occupancy grid map using 3D lidar.

### ISSUE THREAD

**Issue by raviS123-dot** [introlab/rtabmap_ros#1033]
![Screenshot from 2023-09-13 14-44-42](https://github.com/introlab/rtabmap_ros/assets/58106153/11f0e6ed-9d1a-4ac1-a8a7-521ccae2554a)

3D map is good but Unable to create proper 2D occupancy grid map using 3D lidar.

**Comment by matlabbe** [comment]
You may try to enable ray tracing: add `--Grid/RayTracing true` to rtabmap node's arguments or
```xml
<param name="Grid/RayTracing" type="str" value="true"/>
```

**Comment by raviS123-dot** [comment]
Thanks, it worked.
