### ISSUE TITLE
rtabmap 

### ISSUE THREAD

**Issue by Zhang-JiLi** [introlab/rtabmap_ros#1040]
Hello author, I am running rtabmap on euroc dataset ，but there were some issues.
![图片](https://github.com/introlab/rtabmap_ros/assets/87462518/55cdefc2-0d91-4867-a969-39f5d37936c7)

**Comment by matlabbe** [comment]
Is it rtabmap_ros binary version? Are you using this launch file https://github.com/introlab/rtabmap_ros/blob/master/rtabmap_examples/launch/euroc_datasets.launch?

**Comment by Zhang-JiLi** [comment]
I use this launch file https://github.com/introlab/rtabmap_ros/blob/master/rtabmap_examples/launch/euroc_datasets.launch. Through GDB parsing, the following content is obtained:

**Comment by Zhang-JiLi** [comment]
![图片](https://github.com/introlab/rtabmap_ros/assets/87462518/73f2ec67-1f59-41cd-8ded-6c280318aa51)
![图片](https://github.com/introlab/rtabmap_ros/assets/87462518/4be08998-bd3e-4005-8e57-745691d24350)
![图片](https://github.com/introlab/rtabmap_ros/assets/87462518/2ed8be47-69c0-4c5c-abaf-9f227ba59fd3)
![图片](https://github.com/introlab/rtabmap_ros/assets/87462518/d343314e-2f03-4b4f-9cc2-79c30c83b750)
![图片](https://github.com/introlab/rtabmap_ros/assets/87462518/987b0685-fbc4-46a2-bd85-249e392948f1)

**Comment by matlabbe** [comment]
`malloc(): Memory corruption` from `cv::Mat::create` may be related to rtabmap built with a different opencv version than the one used on runtime. Were there warnings in cmake logs about one opencv hidden by another one?
