### ISSUE TITLE
Advice on Updating Point Cloud's Pose

### ISSUE THREAD

**Issue by 360wcui** [introlab/rtabmap_ros#1043]
I am porting rtabmap rviz plugins to Foxglove.  I notice that the point cloud's pose is not updated as well as one in RViz.

Here is the code snippet I have to update point cloud's pose using s.getPose().   Any advice on how to update the poses would be greatly appreciated. 

//            odomCloud = rtabmap::util3d::transformPointCloud(cloud, s.getPose());
//            pcl::toROSMsg(*odomCloud, *odomCloudMsg);
//            odomCloudMsg->header.frame_id = "map";

I replayed the demo bag `rosbag play --clock demo_mapping.bag`,  RViz showed a perfect map,  but Foxglove suffered an odom drift as one could see from the pictures below. 

[
![Screenshot from 2023-10-02 18-31-49](https://github.com/introlab/rtabmap_ros/assets/12385457/442c64f6-5103-4790-96ab-0fbefb934598)
![Screenshot from 2023-10-02 18-31-42](https://github.com/introlab/rtabmap_ros/assets/12385457/19cdffeb-00f3-4955-bbea-8a55826e37b2)

**Comment by matlabbe** [comment]
For the rviz plugin, each time we receive a new MapData topic, we get the current poses, 
https://github.com/introlab/rtabmap_ros/blob/68066b7e9a32d87766440a3f0033a0763f146350/rtabmap_rviz_plugins/src/MapCloudDisplay.cpp#L276-L282

then update all point clouds added so far with the current optimized poses (actually we just adjust the anchor of each point cloud, we don't transform individual points):
https://github.com/introlab/rtabmap_ros/blob/68066b7e9a32d87766440a3f0033a0763f146350/rtabmap_rviz_plugins/src/MapCloudDisplay.cpp#L731-L762

**Comment by 360wcui** [comment]
Thank you.  What would be the easiest way for me to publish all the updated point clouds for visualization?  Do you recommend doing so?  My rationale is to have C++ do all the heavy lifting and let JavaScript handle only the visualization.

**Comment by matlabbe** [comment]
The MapData way would limit the bandwidth usage, as only latest node data has to be published. 

If you want to get the full map cloud after every frame, you can subscribe to /rtabmap/map_cloud topic, which is a PointCloud2 msg. 

Note that when the occupancy grid is created by 2d scans, the map cloud will be 2d.

**Comment by 360wcui** [comment]
I don't see any messages in /rtabmap/map_cloud.   Do I need to enable anything?   'rtabmap_ros' is 'tag: 0.21.1-noetic',   The bag is your 'demo_mapping.bag'.   Thank you.

**Comment by MRSHIMMER** [comment]
> The MapData way would limit the bandwidth usage, as only latest node data has to be published.
> 
> If you want to get the full map cloud after every frame, you can subscribe to /rtabmap/map_cloud topic, which is a PointCloud2 msg.
> 
> Note that when the occupancy grid is created by 2d scans, the map cloud will be 2d.



> /rtabmap/map_cloud

Does the "/rtabmap/map_cloud" topic mentioned in your answer actually refer to the "/rtabmap/cloud_map" topic?

**Comment by matlabbe** [comment]
Yeah sorry, I corrected it.
