### ISSUE TITLE
Example of RTabMap running with multiple sensors on a single mobile robot

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap_ros#1044]
Is there any working example/reference to RTabMap taking inputs from multiple sensors  ( like 2 Zed Cameras or 2 T265 or 1 Zed and 1 T265 ) placed on the same mobile robot but at different positions on the robot and eventually build a single 3D map.

**Comment by matlabbe** [comment]
[This](https://github.com/introlab/rtabmap_ros/blob/68066b7e9a32d87766440a3f0033a0763f146350/rtabmap_demos/launch/demo_unitree_quadruped_robot.launch#L17-L92) can be a good example with 3 cameras. 

I am looking forward to receive my [RAE](https://shop.luxonis.com/products/rae) robot someday, I'll create an example for it.
