### ISSUE TITLE
Visualize created map

### ISSUE THREAD

**Issue by nicolasukd** [introlab/rtabmap_ros#1047]
Where can i visualize the map thats created? 
I know that its located in `~/.ros/rtabmap.db` by default, but i dont know how to open it.

**Comment by matlabbe** [comment]
You can open it with:
```
$ rtabmap ~/.ros/rtabmap.db
```
Or 
```
$ rtabmap-databaseViewer ~/.ros/rtabmap.db
```

**Comment by matlabbe** [comment]
Can you do `which` to see which rtabmap is started? You may explicitly call `~/rtabmap/build/bin/rtabmap` to make sure it is the one you just built with latest master version.

**Comment by nicolasukd** [comment]
![image](https://github.com/introlab/rtabmap_ros/assets/53022979/b7890218-e1e1-448c-9fe1-d81cf855db07)

How do i explicitly call ~/rtabmap/build/bin/rtabmap?

**Comment by matlabbe** [comment]
That database may have been created on another computer using a more recent version of rtabmap. If you did:
```
cd rtabmap
git pull origin master
cd build
make
sudo make install
```
I'll suggest to remove ros binaries:
```
sudo apt remove ros-melodic-rtabmap
```
so you will make sure you will be using 0.21 installed from source instead.

To explicitly call `~/rtabmap/build/bin/rtabmap`, just do `~/rtabmap/build/bin/rtabmap` in terminal.

**Comment by nicolasukd** [comment]
It worked. Im wondering now if i can visualize this map in windows.

**Comment by matlabbe** [comment]
You should be able to visualize on windows using the 0.21.0 binaries (see assets section): https://github.com/introlab/rtabmap/releases/tag/0.21.0
