### ISSUE TITLE
unable to start rtabmap

### ISSUE THREAD

**Issue by abhignans** [introlab/rtabmap_ros#105]
hello i have installed rtabmap_ros from source.
all went well but after i open the application it does not start and says segmentation error and application doesnt start forever
 here is the screen shot.
can anybody suggest me way to proceed or how to debug it even
![screenshot from 2016-07-29 15 52 21](https://cloud.githubusercontent.com/assets/17729885/17263060/8a3c5f34-55a4-11e6-86ef-de318a9d5018.png)

**Comment by willdzeng** [comment]
did you installed rtabmap from ROS before?
if it is, you can try remove it and re-install rtabmap

Can you print your
`ls /usr/local/lib`
and
`ls /usr/local/lib/x86_64-linux-gnu`
here?

**Comment by matlabbe** [comment]
closed by inactivity
