### ISSUE TITLE
Making a map with reference points

### ISSUE THREAD

**Issue by coen132** [introlab/rtabmap_ros#1062]
Hey, 

I'm trying to make a map with RTABmap of a warehouse where I have RFID tags in the floor. I want to use the RFID tags as ground truth, already have a function which sets the pose of my robot as soon as I drive over the first two tags. The problem is that rtabmap always starts mapping from origin 0,0,0, does anybody know what the most simple way is to set the initial position for mapping?

Thanks in advance!

**Comment by matlabbe** [comment]
rtabmap first node is not always (0,0), but would match the odometry pose received, which is often (0,0) when the mapping is started and the robot didn't move yet.

If you set `Optimizer/PriorsIgnored` to false, you may be able to use `/rtabmap/global_pose` topic to publish a global pose to rtabmap when a RFID is detected. If you know the global position of that tag and the relative position of the robot to that tag when detected, publishing `/rtabmap/global_pose` ([geometry_msgs/PoseWithCovarianceStamped](http://docs.ros.org/en/noetic/api/geometry_msgs/html/msg/PoseWithCovarianceStamped.html)) with the robot pose in that coordinate frame and some covariance (depending how accurate the RFID detection is). On 2D case, you would have to fill only x,y and yaw parameters of the covariance matrix:
```
x 0 0    0    0    0
0 y 0    0    0    0
0 0 9999 0    0    0
0 0 0    9999 0    0 
0 0 0    0    9999 0
0 0 0    0    0    yaw
```
If you cannot know the yaw orientation relative to tag, set yaw to 9999:
```
x 0 0    0    0    0
0 y 0    0    0    0
0 0 9999 0    0    0
0 0 0    9999 0    0 
0 0 0    0    9999 0
0 0 0    0    0    9999
```

cheers,
Mathieu
