### ISSUE TITLE
Improve Mapping Qaulity

### ISSUE THREAD

**Issue by 360wcui** [introlab/rtabmap_ros#1068]
We have a custom camera setup.   We are able to port in point cloud, hires, and vio for rtabmap.   Below is the resulting 3D map in RViz.  I wonder if there is anything we can do to further improve mapping quality.    Thank you. 

<img width="690" alt="Screenshot 2023-11-18 at 10 22 04 AM" src="https://github.com/introlab/rtabmap_ros/assets/12385457/d633aa72-5a6e-4e5c-88af-847e41ad1446">

**Comment by 360wcui** [comment]
The hires, vio, and point cloud are published at 5 Hz

**Comment by matlabbe** [comment]
Is it with a TOF camera? In term of quality, do you mean point cloud noise, color, misalignement? The frame rate is not that important on mapping side as long as the VIO pose and all image topics are already synchronized.

**Comment by 360wcui** [comment]
Yes, we use a ToF sensor.  Th max range is about 5m.
