### ISSUE TITLE
RTABMAP_SYNC_MULTI_RGBD using multiple RGBD cameras

### ISSUE THREAD

**Issue by takahiko-hasegawa-hdjp** [introlab/rtabmap_ros#1078]
Hi there, 

Im trying to use multiple RGBD cameras for visual localization and did some reading on the usage of multiple cameras (using rgbd_sync nodelet) on ros2. 

First question is can I use multiplecamera feature to improve mapping and localization? (I have my own wheel encoder which publishes odom and base_link, so not using visual odometry)

I have two cameras in my robot which are located in the front of the camera and the second one located in the rear of the robot (180degree rotated from front camera).

Does the multicamera capability also handle front and rear? or it needs to be front and right/left

thanks in advance

**Comment by matlabbe** [comment]
Yes, multiple cameras could increase your odometry accuracy, unless your wheel encoders have a very low drift. 

If you want to use multi cameras with rtabmap, it is strongly recommended to build rtabmap with [OpenGV](https://github.com/laurentkneip/opengv) support.

You can place your cameras anywhere on the robot. You should make sure that the extrinsics between cameras and base frame are accurate. Ideally having hardware synchronized cameras, though it can work satisfactory with 30 Hz approx sync between the cameras.
