### ISSUE TITLE
How to improve the frequency of re-localization when its localization lost in navigation.

### ISSUE THREAD

**Issue by ddp123cqu** [introlab/rtabmap_ros#1083]
As the title indicated, I use the map built by rtabmap to navigation by move_base. And when I rotate the robot or it rotated frequently, it may lost its localization which lead to the failure of navigation. Sometimes it could recovery by itself if I manipulate the robot to go straight or not. But most time it could not and lead to errors in localization. So I thought that maybe I could improve the frequency of re-localization. The question is that I didn't find the code of re-localization. I am very appreciate if you could help me or give me some advice to deal with it.

![d3a2b6ca71a66c91ae5daee577a2871](https://github.com/introlab/rtabmap_ros/assets/120436141/95c31235-a30b-4506-9ce1-3c2b33c37769)

**Comment by matlabbe** [comment]
What odometry are you using? If you are using any rtabmap's odometry and have wheel odometry, you may set `guess_frame_id` parameter with `Odom/ResetCountdown=1` to use wheel odometry when visual odometry cannot be computed, then automatically reset VO form latest wheel odometry motion.
