### ISSUE TITLE
Offset of the map made using rtabmap_costmap_plugins::StaticLayer

### ISSUE THREAD

**Issue by JoachimDenantes** [introlab/rtabmap_ros#1087]
Hi, I am using ROS noetic, producing gridmap with RTAB-Map and trying to use this map to make a global map in move_base. So I am using the plugin rtabmap_costmap_plugins::StaticLayer as you can see in costmap_global_laser.yaml.
You can see the result in the image of rviz I sent. The global map is build correctly using the RTAB-Map gridmap, but it is offset, not aligned with the rest. Any idea on how to fix this ?
![map offset](https://github.com/introlab/rtabmap_ros/assets/102583098/418ba9ae-d040-432c-9869-17db4f6e6058)
![costmap_common](https://github.com/introlab/rtabmap_ros/assets/102583098/904ad66a-d1e7-4586-b526-ed753e247fc7)
![global_costmap](https://github.com/introlab/rtabmap_ros/assets/102583098/2d7ea707-bf71-4eb9-8833-7ccd6f524231)

**Comment by matlabbe** [comment]
I think `static_map` should be `true` for the global costmap. The `width` and `height` don't need to be explicitly set. `rolling_window` should be false.

**Comment by JoachimDenantes** [comment]
It work! Thank you very much
