### ISSUE TITLE
I'm having an error when while trying to build my package

### ISSUE THREAD

**Issue by omarabdullaalali** [introlab/rtabmap_ros#1099]
$colcon build --symlink-install --packages-select vectornav_msgs

Starting >>> vectornav_msgs
--- stderr: vectornav_msgs                         
CMake Error at /opt/ros/iron/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:192 (message):
  rosidl_generate_interfaces() the passed dependency 'common_msgs' has not
  been found before using find_package()
Call Stack (most recent call first):
  CMakeLists.txt:13 (rosidl_generate_interfaces)

---
Failed   <<< vectornav_msgs [0.26s, exited with code 1]

Summary: 0 packages finished [0.68s]
  1 package failed: vectornav_msgs
  1 package had stderr output: vectornav_msgs

**Comment by matlabbe** [comment]
I'll suggest to post that question on [robotics stack exchange](https://robotics.stackexchange.com/)
