### ISSUE TITLE
3D map can not be generated and visualized on RVIZ

### ISSUE THREAD

**Issue by Jenanaputra** [introlab/rtabmap_ros#1108]
Hi

I am working with ROS2 Humble to generate 3D map using rtabmap_ros. It is run in the turtlebot3 simulation.  I used the depth camera plugin on the robot urdf, so it can publish depthcamera, camerainfo and image_rect_color.

The way I run the simulation :

1.  ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py
2.  run the bridge.py program (this is created by myself to remap the '/intel_realsense_r200_depth/depth/image_raw', '/intel_realsense_r200_depth/camera_info', '/intel_realsense_r200_depth/image_raw' to be '/camera/depth_registered/image_raw', '/camera/rgb/camera_info','/camera/rgb/image_rect_color')   
3. ros2 launch rtabmap_launch rtabmap.launch.py visual_odometry:=false frame_id:=base_footprint subscribe_scan:=true depth:=true approx_sync:=true odom_topic:=/odom scan_topic:=/scan qos:=2 args:="-d --RGBD/NeighborLinkRefining true --Reg/Strategy 1" use_sim_time:=true rviz:=true

When all those steps are executed, the 3d map did not come up. 
![viz](https://github.com/introlab/rtabmap_ros/assets/69109599/5937bf75-d434-42c6-8536-e73d4b4997d9)

But I got the warning notification on my command line terminal:
![debugging](https://github.com/introlab/rtabmap_ros/assets/69109599/cd0219fa-06ad-4289-ae3c-d39a096b7f37)

I also attach the rqt_graph of the active nodes and msgs:
![rqt_graph](https://github.com/introlab/rtabmap_ros/assets/69109599/6ad63c5a-e8ea-452d-a1ab-48e435013cbb)

Does anyone know what happen here and how to solve it ? I am on the dead end. Thanks!!

**Comment by matlabbe** [comment]
To make the turtlebot3 simulation works, look at the instructions in the header of that launch file:
https://github.com/introlab/rtabmap_ros/blob/ros2/rtabmap_demos/launch/turtlebot3_rgbd_sync.launch.py

**Comment by Jenanaputra** [comment]
Hii @matlabbe .. Thanks!!! it works

**Comment by basheeraltawil** [comment]
@matlabbe 
Can you share all model.sdf script 
Because I added this part of modification and couldn't get the 3D details.
I got the results as in this issue .

**Comment by matlabbe** [comment]
The latest version of that launch file is here: https://github.com/introlab/rtabmap_ros/blob/ros2/rtabmap_demos/launch/turtlebot3/turtlebot3_sim_rgbd_demo.launch.py, though it looks pretty similar to instructions above.

**Comment by rovinthomas** [comment]
@Jenanaputra Could you share the full model.sdf script you used? Have been facing the exact same problems as mentioned in your initial issue, with no 3D map and the exact same warning notifications.

This is despite having made all the changes instructed in the header of the launch file (turtlebot3_sim_rgbd_demo.launch.py), am in the same situation as @basheeraltawil 

Thank you!

**Comment by matlabbe** [comment]
Here is a diff with the Humble version:
```diff
368a369
>     <link name="camera_rgb_frame"/>
370c371,380
<     <link name="camera_rgb_frame">
---
>     <joint name="camera_rgb_optical_joint" type="fixed">
>       <parent>camera_rgb_frame</parent>
>       <child>camera_rgb_optical_frame</child>
>       <pose>0 0 0 -1.57079632679 0 -1.57079632679</pose>
>       <axis>
>         <xyz>0 0 1</xyz>
>       </axis>
>     </joint> 
> 
>     <link name="camera_rgb_optical_frame">
385c395
<       <sensor name="camera" type="camera">
---
>       <sensor name="camera" type="depth">
392,393c402,403
<             <width>1920</width>
<             <height>1080</height>
---
>             <width>640</width>
>             <height>480</height>
```
Here the file: 

[model.zip](https://github.com/user-attachments/files/24274283/model.zip)
