### ISSUE TITLE
Reading mapGraph poses from rtabmap.db directly

### ISSUE THREAD

**Issue by 360wcui** [introlab/rtabmap_ros#1110]
Would it be possible to read mapGraph poses from rtabmap.db?    I tried to read poses from Node table in rtabmap.db and realized that they are odometry poses not mapGraph poses.  Any insight would be greatly appreciated. 

![Screenshot from 2024-01-26 15-18-29](https://github.com/introlab/rtabmap_ros/assets/12385457/a56fccbd-65ea-441a-abdc-be2ef4b604cd)
![Screenshot from 2024-01-26 15-14-40](https://github.com/introlab/rtabmap_ros/assets/12385457/c151e32b-006c-4588-a074-d4b235fb4883)

**Comment by matlabbe** [comment]
Look under `Admin` table, there is `opt_poses` field.
https://github.com/introlab/rtabmap/blob/c27507bc772cfda34f6624d386ab2cd62d49e90d/corelib/src/resources/DatabaseSchema.sql.in#L123-L124

**Comment by 360wcui** [comment]
Thank you, but the field is null sometimes.   Would it be possible to enable it in real-time like /rtabmap/mapGraph which is published at 1 hz.   
![Screenshot from 2024-01-27 21-52-01](https://github.com/introlab/rtabmap_ros/assets/12385457/7cc987e3-33be-497c-9c11-321fb9792611)

**Comment by matlabbe** [comment]
Currently it is saved only when the database is closed. In ROS, you would have already the same info with `/rtabmap/mapGraph`.
