### ISSUE TITLE
rtabmap_viz vtkOpenGLPolyDataMapper warnings filling shell output

### ISSUE THREAD

**Issue by unicornuniform** [introlab/rtabmap_ros#1111]
![Screenshot from 2024-01-27 23-51-42](https://github.com/introlab/rtabmap_ros/assets/75616262/a6f8bb37-adcf-4a06-9553-f7e6254586ad)
When I run rtabmap_ros, I get a nonstop flood of:
`[rtabmap_viz-4] 2024-01-27 12:43:14.845 (  13.573s) [        A2CDB3C0]vtkOpenGLPolyDataMapper:336   WARN| vtkOpenGLPolyDataMapper::GetGeometryShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetGeometryShaderCode instead.`

I didn't compile rtabmap_ros from scratch. I installed from apt-get install ros-humble-rtabmap

**Comment by matlabbe** [comment]
It seems this warning is coming from VTK library itself: https://discourse.vtk.org/t/vtk-9-0-rc1/2916/3

Other related comment in PointCloud library:
https://github.com/PointCloudLibrary/pcl/issues/4830#issuecomment-873326759

We don't call these functions explicitly in rtabmap code. The fix would be to add `VTK_LEGACY_REMOVE` in cmake.

**Comment by unicornuniform** [comment]
Will this make it's way into the binaries eventually?

**Comment by matlabbe** [comment]
The commit above should fix the VTK warnings issue in next release.
