### ISSUE TITLE
mapping object detection data

### ISSUE THREAD

**Issue by FlorianMehnert** [introlab/rtabmap_ros#1146]
Hi there,

is it possible to use rtabmap with object detection data or are there better alternatives for storing detected objects?  I found a similar project that does basically what I want using rtabmap where they drive around detecting objects and storing them in rtabmap for later use: [https://github.com/ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d](https://github.com/ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d). 
![2d-map-with-obstacles](https://user-images.githubusercontent.com/20625381/49587668-e57f9b00-f9a7-11e8-8414-81462b6e2e36.png) 
[![turtlebot3_slam_3d_mapping](https://user-images.githubusercontent.com/20625381/49206744-58ac6e80-f3f6-11e8-895b-23a05ec03512.gif)](https://drive.google.com/open?id=11fpvLkPqPS2xIGGCNxgHxWuRkkYeu7e-)
Since I ran into issues getting the turtlebot3_slam_3d to run (not maintained anymore) I was wondering whether this is supported out of the box/there are any attempts to add a similar feature to rtabmap?

**Comment by matlabbe** [comment]
It seems they collected the objects in another file, with name and pose in the current map frame. As they are not saving against the graph, I am not sure if the pose of the objects is corrected on a loop closure. We have an example [here](http://wiki.ros.org/rtabmap_ros#rtabmap_ros.2Fnoetic_and_newer.Robot_mapping_with_Find-Object) where objects were added to the graph, then shown back in rviz (follow `save_objects` argument). The main code is in this [example](https://github.com/introlab/rtabmap_ros/blob/master/rtabmap_demos/src/SaveObjectsExample.cpp). There are two callbacks: one from some object detection topic that encodes detection in UserData msg to be recorded in rtabmap node, and one that subscribe to published MapData from rtabmap node an decode the UserData to create markers to be shown in rviz. If the map's graph changes, the markers are updated.

**Comment by FlorianMehnert** [comment]
for the find object example I ran into a similar issue as #509 but the same fix with a small python script works

**Comment by matlabbe** [comment]
Thanks to point out, I'll reupload a fixed rosbag for that demo.

**Comment by matlabbe** [comment]
[Bag](https://docs.google.com/uc?export=download&confirm=XJb5&id=0B46akLGdg-uaUEVEX1VmQTdOQUE) has been updated.
