### ISSUE TITLE
There are a lot of issues or errors when run the make of the source for the indigo version in the last two steps

### ISSUE THREAD

**Issue by 78226415** [introlab/rtabmap_ros#117]
Hi everyone,
     I have caught a problem when  run the make of the source for the indigo version, the command like:

$ cd ~
$ git clone https://github.com/introlab/rtabmap.git rtabmap
$ cd rtabmap/build
$ cmake ..  [<---double dots included]
$ make -j4

it is one of the last two steps, all steps above this step are built successful. My environment is ubuntu14.04 LTS, ros indigo.
    The error message are:
/usr/include/ni/XnCppWrapper.h: At global scope:
/usr/include/ni/XnCppWrapper.h:9717:9: error: ‘XnStatus’ does not name a type
  inline XnStatus NodeInfoList::FilterList(Context& context, Query& query)
         ^
/usr/include/ni/XnCppWrapper.h: In member function ‘void xn::ProductionNode::GetContext(xn::Context&) const’:
/usr/include/ni/XnCppWrapper.h:9724:66: error: ‘xnGetRefContextFromNodeHandle’ was not declared in this scope
   context.TakeOwnership(xnGetRefContextFromNodeHandle(GetHandle()));
                                                                  ^
/usr/include/ni/XnCppWrapper.h: In member function ‘xn::Context xn::ProductionNode::GetContext() const’:
/usr/include/ni/XnCppWrapper.h:9729:66: error: ‘xnGetRefContextFromNodeHandle’ was not declared in this scope
   XnContext* pContext = xnGetRefContextFromNodeHandle(GetHandle());
                                                                  ^
/usr/include/ni/XnCppWrapper.h:9731:28: error: ‘xnContextRelease’ was not declared in this scope
   xnContextRelease(pContext);
                            ^
/usr/include/ni/XnCppWrapper.h: In member function ‘xn::NodeInfoList& xn::NodeInfo::GetNeededNodes() const’:
/usr/include/ni/XnCppWrapper.h:9739:60: error: ‘xnNodeInfoGetNeededNodes’ was not declared in this scope
    XnNodeInfoList* pList = xnNodeInfoGetNeededNodes(m_pInfo);
                                                            ^
/usr/include/ni/XnCppWrapper.h: In member function ‘void xn::NodeInfo::SetUnderlyingObject(XnNodeInfo*)’:
/usr/include/ni/XnCppWrapper.h:9753:3: error: ‘m_bOwnerOfNode’ was not declared in this scope
   m_bOwnerOfNode = FALSE;
   ^
/usr/include/ni/XnCppWrapper.h: At global scope:
/usr/include/ni/XnCppWrapper.h:9758:9: error: ‘XnBool’ does not name a type
  inline XnBool FrameSyncCapability::CanFrameSyncWith(Generator& other) const
         ^
/usr/include/ni/XnCppWrapper.h:9763:9: error: ‘XnStatus’ does not name a type
  inline XnStatus FrameSyncCapability::FrameSyncWith(Generator& other)
         ^
/usr/include/ni/XnCppWrapper.h:9768:9: error: ‘XnStatus’ does not name a type
  inline XnStatus FrameSyncCapability::StopFrameSyncWith(Generator& other)
         ^
/usr/include/ni/XnCppWrapper.h:9773:9: error: ‘XnBool’ does not name a type
  inline XnBool FrameSyncCapability::IsFrameSyncedWith(Generator& other) const
         ^
/usr/include/ni/XnCppWrapper.h:9778:9: error: ‘XnStatus’ does not name a type
  inline XnStatus NodeInfo::GetInstance(ProductionNode& node) const
         ^
/usr/include/ni/XnCppWrapper.h:9800:9: error: ‘XnStatus’ does not name a type
  inline XnStatus Device::Create(Context& context, Query* pQuery/*=NULL*/, EnumerationErrors* pErrors/*=NULL*/)
         ^
/usr/include/ni/XnCppWrapper.h:9809:9: error: ‘XnStatus’ does not name a type
  inline XnStatus Recorder::Create(Context& context, const XnChar* strFormatName /*= NULL*/)
         ^
/usr/include/ni/XnCppWrapper.h:9818:9: error: ‘XnStatus’ does not name a type
  inline XnStatus Player::Create(Context& context, const XnChar* strFormatName)
         ^
/usr/include/ni/XnCppWrapper.h:9827:9: error: ‘XnStatus’ does not name a type
  inline XnStatus DepthGenerator::Create(Context& context, Query* pQuery/*=NULL*/, EnumerationErrors* pErrors/*=NULL*/)
         ^
/usr/include/ni/XnCppWrapper.h:9836:9: error: ‘XnStatus’ does not name a type
  inline XnStatus MockDepthGenerator::Create(Context& context, const XnChar* strName /* = NULL */)
         ^
/usr/include/ni/XnCppWrapper.h:9845:9: error: ‘XnStatus’ does not name a type
  inline XnStatus MockDepthGenerator::CreateBasedOn(DepthGenerator& other, const XnChar* strName /* = NULL */)
         ^
/usr/include/ni/XnCppWrapper.h:9856:9: error: ‘XnStatus’ does not name a type
  inline XnStatus ImageGenerator::Create(Context& context, Query* pQuery/*=NULL*/, EnumerationErrors* pErrors/*=NULL*/)
         ^
/usr/include/ni/XnCppWrapper.h:9865:9: error: ‘XnStatus’ does not name a type
  inline XnStatus MockImageGenerator::Create(Context& context, const XnChar* strName /* = NULL */)
         ^
/usr/include/ni/XnCppWrapper.h:9874:9: error: ‘XnStatus’ does not name a type
  inline XnStatus MockImageGenerator::CreateBasedOn(ImageGenerator& other, const XnChar* strName /* = NULL */)
         ^
/usr/include/ni/XnCppWrapper.h:9885:9: error: ‘XnStatus’ does not name a type
  inline XnStatus IRGenerator::Create(Context& context, Query* pQuery/*=NULL*/, EnumerationErrors* pErrors/*=NULL*/)
         ^
/usr/include/ni/XnCppWrapper.h:9894:9: error: ‘XnStatus’ does not name a type
  inline XnStatus MockIRGenerator::Create(Context& context, const XnChar* strName /* = NULL */)
         ^
/usr/include/ni/XnCppWrapper.h:9903:9: error: ‘XnStatus’ does not name a type
  inline XnStatus MockIRGenerator::CreateBasedOn(IRGenerator& other, const XnChar* strName /* = NULL */)
         ^
/usr/include/ni/XnCppWrapper.h:9914:9: error: ‘XnStatus’ does not name a type
  inline XnStatus GestureGenerator::Create(Context& context, Query* pQuery/*=NULL*/, EnumerationErrors* pErrors/*=NULL*/)
         ^
/usr/include/ni/XnCppWrapper.h:9923:9: error: ‘XnStatus’ does not name a type
  inline XnStatus SceneAnalyzer::Create(Context& context, Query* pQuery/*=NULL*/, EnumerationErrors* pErrors/*=NULL*/)
         ^
/usr/include/ni/XnCppWrapper.h:9933:9: error: ‘XnStatus’ does not name a type
  inline XnStatus HandsGenerator::Create(Context& context, Query* pQuery/*=NULL*/, EnumerationErrors* pErrors/*=NULL*/)
         ^
/usr/include/ni/XnCppWrapper.h:9942:9: error: ‘XnStatus’ does not name a type
  inline XnStatus UserGenerator::Create(Context& context, Query* pQuery/*=NULL*/, EnumerationErrors* pErrors/*=NULL*/)
         ^
/usr/include/ni/XnCppWrapper.h:9951:9: error: ‘XnStatus’ does not name a type
  inline XnStatus AudioGenerator::Create(Context& context, Query* pQuery/*=NULL*/, EnumerationErrors* pErrors/*=NULL*/)
         ^
/usr/include/ni/XnCppWrapper.h:9960:9: error: ‘XnStatus’ does not name a type
  inline XnStatus MockAudioGenerator::Create(Context& context, const XnChar* strName /* = NULL */)
         ^
/usr/include/ni/XnCppWrapper.h:9969:9: error: ‘XnStatus’ does not name a type
  inline XnStatus MockAudioGenerator::CreateBasedOn(AudioGenerator& other, const XnChar* strName /* = NULL */)
         ^
/usr/include/ni/XnCppWrapper.h:9980:9: error: ‘XnStatus’ does not name a type
  inline XnStatus MockRawGenerator::Create(Context& context, const XnChar* strName /*= NULL*/)
         ^
/usr/include/ni/XnCppWrapper.h:9989:9: error: ‘XnStatus’ does not name a type
  inline XnStatus Codec::Create(Context& context, XnCodecID codecID, ProductionNode& initializerNode)
         ^
/usr/include/ni/XnCppWrapper.h:9998:9: error: ‘XnStatus’ does not name a type
  inline XnStatus ScriptNode::Run(EnumerationErrors* pErrors)
         ^
/usr/include/ni/XnCppWrapper.h:10003:9: error: ‘XnStatus’ does not name a type
  inline XnStatus ScriptNode::Create(Context& context, const XnChar* strFormat)
         ^
/usr/include/ni/XnCppWrapper.h:10016:31: error: variable or field ‘XN_API_DEPRECATED’ declared void
  inline void XN_API_DEPRECATED("Use xn::Version::Current() instead") GetVersion(XnVersion& Version)
                               ^
/usr/include/ni/XnCppWrapper.h:10028:54: error: expected ‘)’ before ‘handler’
   StateChangedCallbackTranslator(StateChangedHandler handler, void* pCookie) : m_UserHandler(handler), m_pUserCookie(pCookie), m_hCallback(NULL) {}
                                                      ^
/usr/include/ni/XnCppWrapper.h:10030:3: error: ‘XnStatus’ does not name a type
   XnStatus Register(_XnRegisterStateChangeFuncPtr xnFunc, XnNodeHandle hNode)
   ^
make[2]: *** [corelib/src/CMakeFiles/rtabmap_core.dir/CameraThread.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/include/ni/XnCppWrapper.h:10040:10: error: ‘XnStatus’ does not name a type
   static XnStatus RegisterToUnderlying(_XnRegisterStateChangeFuncPtr xnFunc, XnNodeHandle hNode, StateChangedHandler handler, void* pCookie, XnCallbackHandle& hCallback)
          ^
/usr/include/ni/XnCppWrapper.h:10059:10: error: ‘XnStatus’ does not name a type
   static XnStatus UnregisterFromUnderlying(_XnUnregisterStateChangeFuncPtr xnFunc, XnNodeHandle hNode, XnCallbackHandle hCallback)
          ^
/usr/include/ni/XnCppWrapper.h:10072:4: error: ‘StateChangedHandler’ does not name a type
    StateChangedHandler userHandler;
    ^
/usr/include/ni/XnCppWrapper.h:10077:15: error: variable or field ‘XN_CALLBACK_TYPE’ declared void
   static void XN_CALLBACK_TYPE StateChangedCallback(XnNodeHandle hNode, void* pCookie)
               ^
/usr/include/ni/XnCppWrapper.h:10077:15: error: expected ‘;’ at end of member declaration
/usr/include/ni/XnCppWrapper.h:10084:3: error: ‘StateChangedHandler’ does not name a type
   StateChangedHandler m_UserHandler;
   ^
/usr/include/ni/XnCppWrapper.h: In member function ‘int xn::StateChangedCallbackTranslator::StateChangedCallback(XnNodeHandle, void*)’:
/usr/include/ni/XnCppWrapper.h:10081:12: error: ‘class xn::StateChangedCallbackTranslator’ has no member named ‘m_UserHandler’
    pTrans->m_UserHandler(node, pTrans->m_pUserCookie);
            ^
/usr/include/ni/XnCppWrapper.h: At global scope:
/usr/include/ni/XnCppWrapper.h:10089:9: error: ‘XnStatus’ does not name a type
  static XnStatus _RegisterToStateChange(_XnRegisterStateChangeFuncPtr xnFunc, XnNodeHandle hNode, StateChangedHandler handler, void* pCookie, XnCallbackHandle& hCallback)
         ^
/usr/include/ni/XnCppWrapper.h: In function ‘void xn::_UnregisterFromStateChange(xn::_XnUnregisterStateChangeFuncPtr, XnNodeHandle, XnCallbackHandle)’:
/usr/include/ni/XnCppWrapper.h:10096:3: error: ‘UnregisterFromUnderlying’ is not a member of ‘xn::StateChangedCallbackTranslator’
   StateChangedCallbackTranslator::UnregisterFromUnderlying(xnFunc, hNode, hCallback);
   ^
/usr/include/ni/XnCppWrapper.h: At global scope:
/usr/include/ni/XnCppWrapper.h:10099:9: error: ‘XnStatus’ does not name a type
  inline XnStatus GeneralIntCapability::RegisterToValueChange(StateChangedHandler handler, void* pCookie, XnCallbackHandle& hCallback)
         ^
/usr/include/ni/XnCppWrapper.h: In member function ‘void xn::GeneralIntCapability::UnregisterFromValueChange(XnCallbackHandle)’:
/usr/include/ni/XnCppWrapper.h:10121:54: error: ‘m_strCap’ was not declared in this scope
   xnUnregisterFromGeneralIntValueChange(GetHandle(), m_strCap, pTrans->m_hCallback);
                                                      ^
/usr/include/ni/XnCppWrapper.h:10121:83: error: ‘xnUnregisterFromGeneralIntValueChange’ was not declared in this scope
   xnUnregisterFromGeneralIntValueChange(GetHandle(), m_strCap, pTrans->m_hCallback);
                                                                                   ^
In file included from /home/liguangxi/rtabmap/corelib/src/../include/rtabmap/core/CameraRGBD.h:41:0,
                 from /home/liguangxi/rtabmap/corelib/src/CameraRGBD.cpp:28:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h: At global scope:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:71:116: error: ‘XnUInt64’ has not been declared
       inline DepthImage (boost::shared_ptr<xn::DepthMetaData> depth_meta_data, float baseline, float focal_length, XnUInt64 shadow_value, XnUInt64 no_sample_value) throw ();
                                                                                                                    ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:71:139: error: ‘XnUInt64’ has not been declared
       inline DepthImage (boost::shared_ptr<xn::DepthMetaData> depth_meta_data, float baseline, float focal_length, XnUInt64 shadow_value, XnUInt64 no_sample_value) throw ();
                                                                                                                                           ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:127:14: error: ‘XnUInt64’ does not name a type
       inline XnUInt64 
              ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:133:14: error: ‘XnUInt64’ does not name a type
       inline XnUInt64 
              ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:161:7: error: ‘XnUInt64’ does not name a type
       XnUInt64 shadow_value_;
       ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:162:7: error: ‘XnUInt64’ does not name a type
       XnUInt64 no_sample_value_;
       ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:165:117: error: ‘XnUInt64’ has not been declared
   DepthImage::DepthImage (boost::shared_ptr<xn::DepthMetaData> depth_meta_data, float baseline, float focal_length, XnUInt64 shadow_value, XnUInt64 no_sample_value) throw ()
                                                                                                                     ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:165:140: error: ‘XnUInt64’ has not been declared
   DepthImage::DepthImage (boost::shared_ptr<xn::DepthMetaData> depth_meta_data, float baseline, float focal_length, XnUInt64 shadow_value, XnUInt64 no_sample_value) throw ()
                                                                                                                                            ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h: In constructor ‘openni_wrapper::DepthImage::DepthImage(boost::shared_ptr<xn::DepthMetaData>, float, float, int, int)’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:169:5: error: class ‘openni_wrapper::DepthImage’ does not have any field named ‘shadow_value_’
   , shadow_value_ (shadow_value)
     ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:170:5: error: class ‘openni_wrapper::DepthImage’ does not have any field named ‘no_sample_value_’
   , no_sample_value_ (no_sample_value) { }
     ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h: At global scope:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:192:3: error: ‘XnUInt64’ does not name a type
   XnUInt64
   ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:198:3: error: ‘XnUInt64’ does not name a type
   XnUInt64
   ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h: In member function ‘unsigned int openni_wrapper::DepthImage::getWidth() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:207:23: error: ‘class xn::DepthMetaData’ has no member named ‘XRes’
     return depth_md_->XRes ();
                       ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h: In member function ‘unsigned int openni_wrapper::DepthImage::getHeight() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:213:23: error: ‘class xn::DepthMetaData’ has no member named ‘YRes’
     return depth_md_->YRes ();
                       ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h: In member function ‘unsigned int openni_wrapper::DepthImage::getFrameID() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:219:23: error: ‘class xn::DepthMetaData’ has no member named ‘FrameID’
     return depth_md_->FrameID ();
                       ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h: In member function ‘long unsigned int openni_wrapper::DepthImage::getTimeStamp() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_depth_image.h:225:51: error: ‘class xn::DepthMetaData’ has no member named ‘Timestamp’
     return static_cast<unsigned long> (depth_md_->Timestamp ());
                                                   ^
In file included from /home/liguangxi/rtabmap/corelib/src/../include/rtabmap/core/CameraRGBD.h:42:0,
                 from /home/liguangxi/rtabmap/corelib/src/CameraRGBD.cpp:28:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h: In member function ‘void openni_wrapper::Image::fillRaw(unsigned char*) const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h:121:38: error: ‘class xn::ImageMetaData’ has no member named ‘Data’
       memcpy (rgb_buffer, image_md_->Data (), image_md_->DataSize ());
                                      ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h:121:58: error: ‘class xn::ImageMetaData’ has no member named ‘DataSize’
       memcpy (rgb_buffer, image_md_->Data (), image_md_->DataSize ());
                                                          ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h: In member function ‘unsigned int openni_wrapper::Image::getWidth() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h:181:23: error: ‘class xn::ImageMetaData’ has no member named ‘XRes’
     return image_md_->XRes ();
                       ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h: In member function ‘unsigned int openni_wrapper::Image::getHeight() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h:187:23: error: ‘class xn::ImageMetaData’ has no member named ‘YRes’
     return image_md_->YRes ();
                       ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h: In member function ‘unsigned int openni_wrapper::Image::getFrameID() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h:193:23: error: ‘class xn::ImageMetaData’ has no member named ‘FrameID’
     return image_md_->FrameID ();
                       ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h: In member function ‘long unsigned int openni_wrapper::Image::getTimeStamp() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h:199:51: error: ‘class xn::ImageMetaData’ has no member named ‘Timestamp’
     return static_cast<unsigned long> (image_md_->Timestamp ());
                                                   ^
In file included from /usr/include/pcl-1.7/pcl/io/openni_camera/openni_driver.h:47:0,
                 from /usr/include/pcl-1.7/pcl/io/openni_grabber.h:48,
                 from /home/liguangxi/rtabmap/corelib/src/CameraRGBD.cpp:44:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h: At global scope:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:417:7: error: ‘XnUInt64’ does not name a type
       XnUInt64 
       ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:482:9: error: ‘XnUInt16’ does not name a type
         XnUInt16 zero_plane_distance_;
         ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:483:9: error: ‘XnFloat’ does not name a type
         XnFloat zero_plane_pixel_size_;
         ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:484:9: error: ‘XnFloat’ does not name a type
         XnFloat emitter_dcmos_distace_;
         ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:485:9: error: ‘XnUInt32’ does not name a type
         XnUInt32 max_shift_;
         ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:486:9: error: ‘XnUInt32’ does not name a type
         XnUInt32 device_max_shift_;
         ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:487:9: error: ‘XnUInt32’ does not name a type
         XnUInt32 const_shift_;
         ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:488:9: error: ‘XnUInt32’ does not name a type
         XnUInt32 pixel_size_factor_;
         ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:489:9: error: ‘XnUInt32’ does not name a type
         XnUInt32 param_coeff_;
         ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:490:9: error: ‘XnUInt32’ does not name a type
         XnUInt32 shift_scale_;
         ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:491:9: error: ‘XnUInt32’ does not name a type
         XnUInt32 min_depth_;
         ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:492:9: error: ‘XnUInt32’ does not name a type
         XnUInt32 max_depth_;
         ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:533:7: error: ‘XnUInt64’ does not name a type
       XnUInt64 shadow_value_;
       ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:535:7: error: ‘XnUInt64’ does not name a type
       XnUInt64 no_sample_value_;
       ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h: In member function ‘float openni_wrapper::OpenNIDevice::getImageFocalLength(int) const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:558:51: error: ‘XnMapOutputMode’ has no member named ‘nXRes’
       output_x_resolution = getImageOutputMode ().nXRes;
                                                   ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h: In member function ‘float openni_wrapper::OpenNIDevice::getDepthFocalLength(int) const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device.h:569:51: error: ‘XnMapOutputMode’ has no member named ‘nXRes’
       output_x_resolution = getDepthOutputMode ().nXRes;
                                                   ^
In file included from /usr/include/pcl-1.7/pcl/io/openni_grabber.h:52:0,
                 from /home/liguangxi/rtabmap/corelib/src/CameraRGBD.cpp:44:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_ir_image.h: In member function ‘unsigned int openni_wrapper::IRImage::getWidth() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_ir_image.h:83:18: error: ‘class xn::IRMetaData’ has no member named ‘XRes’
   return ir_md_->XRes ();
                  ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_ir_image.h: In member function ‘unsigned int openni_wrapper::IRImage::getHeight() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_ir_image.h:88:18: error: ‘class xn::IRMetaData’ has no member named ‘YRes’
   return ir_md_->YRes ();
                  ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_ir_image.h: In member function ‘unsigned int openni_wrapper::IRImage::getFrameID() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_ir_image.h:93:18: error: ‘class xn::IRMetaData’ has no member named ‘FrameID’
   return ir_md_->FrameID ();
                  ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_ir_image.h: In member function ‘long unsigned int openni_wrapper::IRImage::getTimeStamp() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_ir_image.h:98:46: error: ‘class xn::IRMetaData’ has no member named ‘Timestamp’
   return static_cast<unsigned long> (ir_md_->Timestamp ());
                                              ^
In file included from /home/liguangxi/rtabmap/corelib/src/CameraRGBD.cpp:44:0:
/usr/include/pcl-1.7/pcl/io/openni_grabber.h: In member function ‘bool pcl::OpenNIGrabber::modeComp::operator()(const XnMapOutputMode&, const XnMapOutputMode&) const’:
/usr/include/pcl-1.7/pcl/io/openni_grabber.h:451:21: error: ‘const XnMapOutputMode’ has no member named ‘nXRes’
           if (mode1.nXRes < mode2.nXRes)
                     ^
/usr/include/pcl-1.7/pcl/io/openni_grabber.h:451:35: error: ‘const XnMapOutputMode’ has no member named ‘nXRes’
           if (mode1.nXRes < mode2.nXRes)
                                   ^
/usr/include/pcl-1.7/pcl/io/openni_grabber.h:453:26: error: ‘const XnMapOutputMode’ has no member named ‘nXRes’
           else if (mode1.nXRes > mode2.nXRes)
                          ^
/usr/include/pcl-1.7/pcl/io/openni_grabber.h:453:40: error: ‘const XnMapOutputMode’ has no member named ‘nXRes’
           else if (mode1.nXRes > mode2.nXRes)
                                        ^
/usr/include/pcl-1.7/pcl/io/openni_grabber.h:455:26: error: ‘const XnMapOutputMode’ has no member named ‘nYRes’
           else if (mode1.nYRes < mode2.nYRes)
                          ^
/usr/include/pcl-1.7/pcl/io/openni_grabber.h:455:40: error: ‘const XnMapOutputMode’ has no member named ‘nYRes’
           else if (mode1.nYRes < mode2.nYRes)
                                        ^
/usr/include/pcl-1.7/pcl/io/openni_grabber.h:457:26: error: ‘const XnMapOutputMode’ has no member named ‘nYRes’
           else if (mode1.nYRes > mode2.nYRes)
                          ^
/usr/include/pcl-1.7/pcl/io/openni_grabber.h:457:40: error: ‘const XnMapOutputMode’ has no member named ‘nYRes’
           else if (mode1.nYRes > mode2.nYRes)
                                        ^
/usr/include/pcl-1.7/pcl/io/openni_grabber.h:459:26: error: ‘const XnMapOutputMode’ has no member named ‘nFPS’
           else if (mode1.nFPS < mode2.nFPS)
                          ^
/usr/include/pcl-1.7/pcl/io/openni_grabber.h:459:39: error: ‘const XnMapOutputMode’ has no member named ‘nFPS’
           else if (mode1.nFPS < mode2.nFPS)
                                       ^
In file included from /usr/include/pcl-1.7/pcl/io/oni_grabber.h:48:0,
                 from /home/liguangxi/rtabmap/corelib/src/CameraRGBD.cpp:45:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device_oni.h: In member function ‘bool openni_wrapper::DeviceONI::hasDataLeft()’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_device_oni.h:89:24: error: ‘class xn::Player’ has no member named ‘IsEOF’
       return (!player_.IsEOF ());
                        ^
In file included from /home/liguangxi/rtabmap/corelib/src/../include/rtabmap/core/CameraRGBD.h:42:0,
                 from /home/liguangxi/rtabmap/corelib/src/CameraRGBD.cpp:28:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h: In member function ‘unsigned int openni_wrapper::Image::getHeight() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h:188:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h: In member function ‘unsigned int openni_wrapper::Image::getWidth() const’:
/usr/include/pcl-1.7/pcl/io/openni_camera/openni_image.h:182:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
make[2]: *** [corelib/src/CMakeFiles/rtabmap_core.dir/CameraRGBD.cpp.o] Error 1
make[1]: *** [corelib/src/CMakeFiles/rtabmap_core.dir/all] Error 2
make: *** [all] Error 2

Could some one help me? thanks.

**Comment by willdzeng** [comment]
Did you installed openNI?

**Comment by matlabbe** [comment]
Similar posts:
 * https://github.com/CognitiveRobotics/organized_segmentation_tools/issues/1
 * http://official-rtab-map-forum.67519.x6.nabble.com/Compilitaion-td955.html
It is a OpenNI vs PCL problem.

**Comment by 78226415** [comment]
use the GTSAM3.2.0, not GTSAM3.2.1, will get it, thank you very much!
