### ISSUE TITLE
2d Map Editor in database viewer save issue

### ISSUE THREAD

**Issue by robotx10** [introlab/rtabmap_ros#1173]
I am facing issue with the latest RTABMAP on ROS2 Humble, the issue is 2d Map Editor in database viewer is having save issue. After saving and running localization with 'Mem/IncrementalMemory':'False', 'Mem/InitWMWithAllNodes':'True' is vanishing drawn occupancy grids cells on graph

Below are the database files and corresponding screen shots. 

![mapping](https://github.com/introlab/rtabmap_ros/assets/135056133/6e0087d9-4156-4e66-8211-279e18d4126e)

DB file:
https://drive.google.com/file/d/1EunzWWneflGMYX5TK6O0w41LdpUZXoB_/view?usp=sharing

![editing](https://github.com/introlab/rtabmap_ros/assets/135056133/7cbe2387-3338-4b1b-992c-0e2d9148a842)

DB file:
https://drive.google.com/file/d/1T4YJH5CloISOKemO6zf41jgYZnnsUXhT/view?usp=sharing
<b>
- When Ran with localization</b>

![after_localization](https://github.com/introlab/rtabmap_ros/assets/135056133/6dd618be-76c2-4535-ae6a-054deb62bf28)

https://drive.google.com/file/d/1BiL7HWuvU8B3YAe-1FBvmX5b1dc8LqHS/view?usp=sharing

launch parameters:

    parameters={
          'frame_id':'base_footprint',
          'subscribe_stereo':True,
          'subscribe_odom_info':True,
          'wait_imu_to_init':True,
          'qos_image':qos,
          'qos_imu':qos,
          'Reg/Force3DoF':'true',
          'Grid/RayTracing':'true',
          }

        Node(
            package='rtabmap_odom', executable='stereo_odometry', output='screen',
            parameters=[parameters],
            remappings=remappings),

        # SLAM mode:
        Node(
            condition=UnlessCondition(localization),
            package='rtabmap_slam', executable='rtabmap', output='screen',
            parameters=[parameters],
            remappings=remappings,
            arguments=['-d']), # This will delete the previous database (~/.ros/rtabmap.db)

        # Localization mode:
        Node(
            condition=IfCondition(localization),
            package='rtabmap_slam', executable='rtabmap', output='screen',
            parameters=[parameters,
              {'Mem/IncrementalMemory':'False',
               'Mem/InitWMWithAllNodes':'True'}],
            remappings=remappings),

I uploaded db files for all the cases. It used to work good with previous versions. But now suddenly it stopped working. 'Mem/IncrementalMemory':'False', 'Mem/InitWMWithAllNodes':'True'

**Comment by matlabbe** [comment]
Thx for reporting, there was indeed a bug. This issue was introduced in that PR: https://github.com/introlab/rtabmap/pull/1180

I fixed it in this [commit](https://github.com/introlab/rtabmap/commit/2a840fe340a31a62a9c4860bb22035f97e6a3f36). You should update/rebuild rtabmap library.

Here the result:
![image](https://github.com/introlab/rtabmap_ros/assets/2319645/da6365b6-9938-4b82-a8c7-499b1166234a)
