### ISSUE TITLE
Rtabmap odom doesn't publish tf with correct time

### ISSUE THREAD

**Issue by dyumanaditya** [introlab/rtabmap_ros#1189]
Hello,

I am using gazebo as my main simulator with a robot  and a simulated rgbd camera. I'm trying to use the data coming from that camera along with `rtabmap_odom` in ros2. Everything works fine except I am not able to control the time in the tf transform from `odom -> base_link`. Therefore visualizing the robot in rviz is impossible since there's no transform found from `odom` to any moving part of the robot.

I am using `use_sim_time=true` how can I fix this mismatch between the tf frame times so that I can visualize the robot in rviz?

The code I'm using to launch rtabmap_odom:
```python
rtabmap = Node(
        package='rtabmap_odom',
        executable='rgbd_odometry',
        name='rgbd_odometry',
        output='screen',
        parameters=[{
            'frame_id': 'base_link',
            'approx_sync': True,
            'use_sim_time':True,
            'odom_frame_id': 'odom',
            'publish_tf': True,
        }],
        remappings=[
            ('/rgb/image', '/d435_camera/color/image_raw'),
            ('/depth/image', '/d435_camera/depth/image_raw'),
            ('/rgb/camera_info', '/d435_camera/color/camera_info')
        ]
    )
```

Error in rviz displaying the robot (for all `link_name`):
```
No transform from [link_name] to [odom]
```

When I try to find the transform in the terminal with `ros2 run tf2_ros tf2_echo odom link_name`:
```
Failure at 1722257648.303
Exception thrown:Lookup would require extrapolation into the past.  Requested time 3928.933000 but the earliest data is at time 1722257645.358313, when looking up transform from frame [fl_foot] to frame [odom]
```

**Comment by matlabbe** [comment]
`rgbd_odometry` doesn't call `now()`, but use the stamp in the input topic's header. It will publish in TF with the same stamp. You can doublecheck by looking at the time set in the output odom topic from `rgbd_odometry`.
