### ISSUE TITLE
How to find small objects which width is 4.5cm and height is 15cm?

### ISSUE THREAD

**Issue by 78226415** [introlab/rtabmap_ros#119]
Hi every one:
     I did a example for kinect v2 to find an object which width is 4.5cm and height is 15cm, it is difficult to find, it shows: Too low matches(9). It is very easy to find if the object's width is 12cm and height is 15cm.
     How to find small objects which width is 4.5cm and height is 15cm or even more small?

thanks

**Comment by matlabbe** [comment]
What code are you using for object detection? If [Find-Object](http://introlab.github.io/find-object/) is used, `Too low matches` means that there are not enough visual features on the object (`Homography/minimumInliers` parameter is 10 by default). Small objects may have a low number of visual features for the same resolution. A higher image resolution may create more features.

Note that for simple generic objects (cylinder, sphere, plane), you may use only the depth information to segment them. See this PCL tutorial: http://pointclouds.org/documentation/tutorials/cylinder_segmentation.php#cylinder-segmentation .

cheers
