### ISSUE TITLE
ROS2 humble on ARM, OpenCV charuco.hpp not found error 

### ISSUE THREAD

**Issue by Al-khattab** [introlab/rtabmap_ros#1200]
Hi, I am trying to build rtabmap_ros from source on a jetson board that is running Ubuntu22.04 and jetpack 6.0 with ROS2 humble, 
I am following the build steps provided in the ros2 branch and when I build I get the following error 

```
/ros2_ws/src/rtabmap/guilib/src/../include/rtabmap/gui/CalibrationDialog.h:43:10: fatal error: opencv2/aruco/charuco.hpp: No such file or directory
   43 | #include <opencv2/aruco/charuco.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [guilib/src/CMakeFiles/rtabmap_gui.dir/build.make:164: guilib/src/CMakeFiles/rtabmap_gui.dir/PreferencesDialog.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:923: guilib/src/CMakeFiles/rtabmap_gui.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
---
Failed   <<< rtabmap [5min 8s, exited with code 2]
```

**Comment by matlabbe** [comment]
Could be a logic error in this code: 
https://github.com/introlab/rtabmap/blob/6ce85b4e55adc2903a6f08dd25fa0c894b34c9cd/guilib/include/rtabmap/gui/CalibrationDialog.h#L42-L45

Which OpenCV version is used? Can you do `make` under `/ros2_ws/build/rtabmap`?

**Comment by Al-khattab** [comment]
as far as I understand, the package will install the dependencies, correct? so I do not need to install OpenCV manually?

also after running the command `make VERBOSE=1` under `/ros2_ws/build/rtabmap`
this is the output 

/usr/bin/cmake -S/home/jetson/ros2_ws/src/rtabmap -B/home/jetson/ros2_ws/build/rtabmap --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/jetson/ros2_ws/build/rtabmap/CMakeFiles /home/jetson/ros2_ws/build/rtabmap//CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/jetson/ros2_ws/build/rtabmap'
make -f utilite/src/CMakeFiles/rtabmap_utilite.dir/build.make utilite/src/CMakeFiles/rtabmap_utilite.dir/depend
make[2]: Entering directory '/home/jetson/ros2_ws/build/rtabmap'
cd /home/jetson/ros2_ws/build/rtabmap && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/jetson/ros2_ws/src/rtabmap /home/jetson/ros2_ws/src/rtabmap/utilite/src /home/jetson/ros2_ws/build/rtabmap /home/jetson/ros2_ws/build/rtabmap/utilite/src /home/jetson/ros2_ws/build/rtabmap/utilite/src/CMakeFiles/rtabmap_utilite.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/jetson/ros2_ws/build/rtabmap'
make -f utilite/src/CMakeFiles/rtabmap_utilite.dir/build.make utilite/src/CMakeFiles/rtabmap_utilite.dir/build
make[2]: Entering directory '/home/jetson/ros2_ws/build/rtabmap'
make[2]: Nothing to be done for 'utilite/src/CMakeFiles/rtabmap_utilite.dir/build'.
make[2]: Leaving directory '/home/jetson/ros2_ws/build/rtabmap'
[ 5%] Built target rtabmap_utilite
make -f utilite/resource_generator/CMakeFiles/res_tool.dir/build.make utilite/resource_generator/CMakeFiles/res_tool.dir/depend
make[2]: Entering directory '/home/jetson/ros2_ws/build/rtabmap'
cd /home/jetson/ros2_ws/build/rtabmap && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/jetson/ros2_ws/src/rtabmap /home/jetson/ros2_ws/src/rtabmap/utilite/resource_generator /home/jetson/ros2_ws/build/rtabmap /home/jetson/ros2_ws/build/rtabmap/utilite/resource_generator /home/jetson/ros2_ws/build/rtabmap/utilite/resource_generator/CMakeFiles/res_tool.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/jetson/ros2_ws/build/rtabmap'
make -f utilite/resource_generator/CMakeFiles/res_tool.dir/build.make utilite/resource_generator/CMakeFiles/res_tool.dir/build
make[2]: Entering directory '/home/jetson/ros2_ws/build/rtabmap'
make[2]: Nothing to be done for 'utilite/resource_generator/CMakeFiles/res_tool.dir/build'.
make[2]: Leaving directory '/home/jetson/ros2_ws/build/rtabmap'
[ 6%] Built target res_tool
make -f corelib/src/CMakeFiles/rtabmap_core.dir/build.make corelib/src/CMakeFiles/rtabmap_core.dir/depend
make[2]: Entering directory '/home/jetson/ros2_ws/build/rtabmap'
cd /home/jetson/ros2_ws/build/rtabmap && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/jetson/ros2_ws/src/rtabmap /home/jetson/ros2_ws/src/rtabmap/corelib/src /home/jetson/ros2_ws/build/rtabmap /home/jetson/ros2_ws/build/rtabmap/corelib/src /home/jetson/ros2_ws/build/rtabmap/corelib/src/CMakeFiles/rtabmap_core.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/jetson/ros2_ws/build/rtabmap'
make -f corelib/src/CMakeFiles/rtabmap_core.dir/build.make corelib/src/CMakeFiles/rtabmap_core.dir/build
make[2]: Entering directory '/home/jetson/ros2_ws/build/rtabmap'
make[2]: Nothing to be done for 'corelib/src/CMakeFiles/rtabmap_core.dir/build'.
make[2]: Leaving directory '/home/jetson/ros2_ws/build/rtabmap'
[ 57%] Built target rtabmap_core
make -f guilib/src/CMakeFiles/rtabmap_gui_autogen.dir/build.make guilib/src/CMakeFiles/rtabmap_gui_autogen.dir/depend
make[2]: Entering directory '/home/jetson/ros2_ws/build/rtabmap'
cd /home/jetson/ros2_ws/build/rtabmap && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/jetson/ros2_ws/src/rtabmap /home/jetson/ros2_ws/src/rtabmap/guilib/src /home/jetson/ros2_ws/build/rtabmap /home/jetson/ros2_ws/build/rtabmap/guilib/src /home/jetson/ros2_ws/build/rtabmap/guilib/src/CMakeFiles/rtabmap_gui_autogen.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/jetson/ros2_ws/build/rtabmap'
make -f guilib/src/CMakeFiles/rtabmap_gui_autogen.dir/build.make guilib/src/CMakeFiles/rtabmap_gui_autogen.dir/build
make[2]: Entering directory '/home/jetson/ros2_ws/build/rtabmap'
[ 57%] Automatic MOC and UIC for target rtabmap_gui
cd /home/jetson/ros2_ws/build/rtabmap/guilib/src && /usr/bin/cmake -E cmake_autogen /home/jetson/ros2_ws/build/rtabmap/guilib/src/CMakeFiles/rtabmap_gui_autogen.dir/AutogenInfo.json Release
make[2]: Leaving directory '/home/jetson/ros2_ws/build/rtabmap'
[ 57%] Built target rtabmap_gui_autogen
make -f guilib/src/CMakeFiles/rtabmap_gui.dir/build.make guilib/src/CMakeFiles/rtabmap_gui.dir/depend
make[2]: Entering directory '/home/jetson/ros2_ws/build/rtabmap'
cd /home/jetson/ros2_ws/build/rtabmap && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/jetson/ros2_ws/src/rtabmap /home/jetson/ros2_ws/src/rtabmap/guilib/src /home/jetson/ros2_ws/build/rtabmap /home/jetson/ros2_ws/build/rtabmap/guilib/src /home/jetson/ros2_ws/build/rtabmap/guilib/src/CMakeFiles/rtabmap_gui.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/jetson/ros2_ws/build/rtabmap'
make -f guilib/src/CMakeFiles/rtabmap_gui.dir/build.make guilib/src/CMakeFiles/rtabmap_gui.dir/build
make[2]: Entering directory '/home/jetson/ros2_ws/build/rtabmap'
[ 58%] Building CXX object guilib/src/CMakeFiles/rtabmap_gui.dir/rtabmap_gui_autogen/mocs_compilation.cpp.o
cd /home/jetson/ros2_ws/build/rtabmap/guilib/src && /usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DDISABLE_OPENNI2 -DDISABLE_PCAP -DDISABLE_PNG -DEIGEN_DENSEBASE_PLUGIN=\"grid_map_core/eigen_plugins/DenseBasePlugin.hpp\" -DEIGEN_FUNCTORS_PLUGIN=\"grid_map_core/eigen_plugins/FunctorsPlugin.hpp\" -DELPP_NO_DEFAULT_LOG_FILE -DPCL_OMP -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DVTK_GLOBAL_WARNING_DISPLAY_OFF -Dkiss_fft_scalar=double -Drtabmap_gui_EXPORTS -I/home/jetson/ros2_ws/build/rtabmap/guilib/src/rtabmap_gui_autogen/include -I/home/jetson/ros2_ws/src/rtabmap/guilib/src/../include -I/home/jetson/ros2_ws/src/rtabmap/guilib/src -I/home/jetson/ros2_ws/build/rtabmap/guilib/src -I/home/jetson/ros2_ws/build/rtabmap/guilib/src/include -I/home/jetson/ros2_ws/src/rtabmap/corelib/src/../include -I/home/jetson/ros2_ws/build/rtabmap/corelib/src/include -I/home/jetson/ros2_ws/src/rtabmap/utilite/src/../include -I/home/jetson/ros2_ws/build/rtabmap/utilite/src/include -isystem /usr/include/aarch64-linux-gnu/qt5 -isystem /usr/include/aarch64-linux-gnu/qt5/QtWidgets -isystem /usr/include/aarch64-linux-gnu/qt5/QtGui -isystem /usr/include/aarch64-linux-gnu/qt5/QtCore -isystem /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/aarch64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/opencv4 -isystem /usr/include/pcl-1.12 -isystem /usr/include/eigen3 -isystem /usr/include/ni -isystem /opt/ros/humble/include -isystem /usr/include/vtk-9.1 -isystem /usr/include/jsoncpp -isystem /usr/include/freetype2 -isystem /usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -fmessage-length=0 -fopenmp -std=c++17 -O3 -DNDEBUG -fPIC -Wall -Wno-unknown-pragmas -fPIC -MD -MT guilib/src/CMakeFiles/rtabmap_gui.dir/rtabmap_gui_autogen/mocs_compilation.cpp.o -MF CMakeFiles/rtabmap_gui.dir/rtabmap_gui_autogen/mocs_compilation.cpp.o.d -o CMakeFiles/rtabmap_gui.dir/rtabmap_gui_autogen/mocs_compilation.cpp.o -c /home/jetson/ros2_ws/build/rtabmap/guilib/src/rtabmap_gui_autogen/mocs_compilation.cpp
In file included from /home/jetson/ros2_ws/build/rtabmap/guilib/src/rtabmap_gui_autogen/NBNA5662NX/moc_CalibrationDialog.cpp:10,
from /home/jetson/ros2_ws/build/rtabmap/guilib/src/rtabmap_gui_autogen/mocs_compilation.cpp:3:
/home/jetson/ros2_ws/build/rtabmap/guilib/src/rtabmap_gui_autogen/NBNA5662NX/../../../../../../src/rtabmap/guilib/include/rtabmap/gui/CalibrationDialog.h:43:10: fatal error: opencv2/aruco/charuco.hpp: No such file or directory
43 | #include <opencv2/aruco/charuco.hpp>
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [guilib/src/CMakeFiles/rtabmap_gui.dir/build.make:136: guilib/src/CMakeFiles/rtabmap_gui.dir/rtabmap_gui_autogen/mocs_compilation.cpp.o] Error 1
make[2]: Leaving directory '/home/jetson/ros2_ws/build/rtabmap'
make[1]: *** [CMakeFiles/Makefile2:923: guilib/src/CMakeFiles/rtabmap_gui.dir/all] Error 2
make[1]: Leaving directory '/home/jetson/ros2_ws/build/rtabmap'

**Comment by matlabbe** [comment]
It seems jetpack6 is using OpenCV 4.8 unlike Ubuntu 22.04 Desktop having OpenCV 4.5.4 and including aruco module. Since OpenCV 4.7.0, charuco module [has been moved](https://github.com/opencv/opencv/pull/22986) from opencv_contrib to opencv repo.

I'll make a local build with latest opencv to fix that issue.

**Comment by matlabbe** [comment]
The commit above should fix the issue. You will need to update `rtabmap` code to latest.
