### ISSUE TITLE
[ERROR] [stereo_odometry-2]: process has died

### ISSUE THREAD

**Issue by pangpangxiong520** [introlab/rtabmap_ros#1226]
**My Device**
Realsense D435i
ROS2 humble
ubuntu 22.04 LTS
When I clone the codes in ros2 branch, I just follow the readme.md and run the command ros2 launch rtabmap_examples realsense_d435i_color.launch.py
The realsense node is successfully up:
![image](https://github.com/user-attachments/assets/0149f2d9-ca18-4d23-9155-b0fd6d048631)
However, there is an error and stereo_odometry process has died:
![image](https://github.com/user-attachments/assets/b3e992a5-d2fd-49c5-af53-7bacd44b4b59)
Then the gui comes up to the screen but here comes the warning:
![image](https://github.com/user-attachments/assets/d25566e4-f721-4a0b-86c8-ba86166de99e)
And when I try to see the topic /odom with command ros2 topic hz /odom, there is nothing appear.
However, the topic  /imu/imu_data can output information:
![image](https://github.com/user-attachments/assets/1ce6c1c5-549d-42a8-a6e7-83296b7da615)
So where is the problem?:(

**Comment by pangpangxiong520** [comment]
I resolved this error by reinstalling RTABMAP, but I can't rule out the possibility that installing the turtlebot3 package before reinstalling RTABMAP also contributed to the solution. Perhaps due to dependencies on turtlebot3, the problem was fixed after reinstalling RTABMAP. I'll go ahead and close this issue.

**Comment by matlabbe** [comment]
Looks like you have a custom opencv version, this can cause problem with rtabmap_ros if those opencv libraries are loaded on runtime and they are not compatible with the ones rtabmap is built on.
