### ISSUE TITLE
[rtabmap/stereo_odometry-1] process has died [pid 16783, exit code -6,

### ISSUE THREAD

**Issue by imranhussain14** [introlab/rtabmap_ros#1239]
Hello, 
I am working on a outdoor mapping and i am using the depthai camera. my rtabmap.launch file is previously working fine but when i installed the navigation (https://github.com/ros-planning/navigation.git) and after catkin_make, its done sucessfully, but now whenever i am giving the command to launch the rtabmap is gives me below error:
`rtabmap/stereo_odometry-1] process has died [pid 16783, exit code -6, cmd /home/darlab/hada_ws_final/devel/lib/rtabmap_odom/stereo_odometry left/image_rect:=/stereo_inertial_publisher/left/image_rect right/image_rect:=/stereo_inertial_publisher/right/image_rect left/camera_info:=/stereo_inertial_publisher/right/camera_info right/camera_info:=/stereo_inertial_publisher/left/camera_info rgbd_image:=rgbd_image_relay odom:=odom imu:=/stereo_inertial_publisher/imu/data __name:=stereo_odometry __log:=/home/darlab/.ros/log/0f47cc38-a80b-11ef-ab94-33ef8da0750a/rtabmap-stereo_odometry-1.log].
log file: /home/darlab/.ros/log/0f47cc38-a80b-11ef-ab94-33ef8da0750a/rtabmap-stereo_odometry-1*.log
[ INFO] [1732195144.172952339]: rtabmap_viz: Reading parameters from the ROS server...
[ INFO] [1732195144.591868814]: rtabmap_viz: Parameters read = 377
[ INFO] [1732195144.591927594]: rtabmap_viz: Parameters successfully read.
[ INFO] [1732195146.797556096]: /rtabmap/rtabmap_viz: subscribe_depth = false
[ INFO] [1732195146.797618834]: /rtabmap/rtabmap_viz: subscribe_rgb = false
[ INFO] [1732195146.797648301]: /rtabmap/rtabmap_viz: subscribe_stereo = true
[ INFO] [1732195146.797673487]: /rtabmap/rtabmap_viz: subscribe_rgbd = false (rgbd_cameras=1)
[ INFO] [1732195146.797707145]: /rtabmap/rtabmap_viz: subscribe_sensor_data = false
[ INFO] [1732195146.797736187]: /rtabmap/rtabmap_viz: subscribe_odom_info = true
[ INFO] [1732195146.797780696]: /rtabmap/rtabmap_viz: subscribe_user_data = false
[ INFO] [1732195146.797820150]: /rtabmap/rtabmap_viz: subscribe_scan = false
[ INFO] [1732195146.797872276]: /rtabmap/rtabmap_viz: subscribe_scan_cloud = false
[ INFO] [1732195146.797924562]: /rtabmap/rtabmap_viz: subscribe_scan_descriptor = false
[ INFO] [1732195146.797961755]: /rtabmap/rtabmap_viz: topic_queue_size = 1
[ INFO] [1732195146.798026142]: /rtabmap/rtabmap_viz: sync_queue_size = 10
[ INFO] [1732195146.798060720]: /rtabmap/rtabmap_viz: approx_sync = true
[ INFO] [1732195146.798167066]: Setup stereo callback
[ INFO] [1732195146.878369595]: 
/rtabmap/rtabmap_viz subscribed to (approx sync):
   /rtabmap/odom \
   /stereo_inertial_publisher/left/image_rect \
   /stereo_inertial_publisher/right/image_rect \
   /stereo_inertial_publisher/right/camera_info \
   /stereo_inertial_publisher/left/camera_info \
   /rtabmap/odom_info
[ INFO] [1732195146.881311778]: rtabmap_viz started.`

I am looking on the internet for this but i didn't find the relevant solution. Can you please tell me how i fix it?

**Comment by matlabbe** [comment]
What commands are you using to start depthai and rtabmap?

Can you share a sample rosbag of the relevant topics:
`rosbag record /tf /tf_static /stereo_inertial_publisher/left/image_rect /stereo_inertial_publisher/right/image_rect /stereo_inertial_publisher/right/camera_info /stereo_inertial_publisher/left/camera_info /stereo_inertial_publisher/imu/data`
