### ISSUE TITLE
Map frame not generating 

### ISSUE THREAD

**Issue by Annaiyan** [introlab/rtabmap_ros#125]
Hello,
Recently i have updated the rtabmap_ros and rtabmap (standalone library).
After that map frame(tf) is not generating.At first, tried with my rosbag and later changed to  `stereo_outdoorA.bag` along with stereo_demo launch file

Both results the same and there is no map frame.Below is the rosgraph of tf
![rosgarph_11_10_2016](https://cloud.githubusercontent.com/assets/12847673/19262727/ddac97d2-8f98-11e6-82dd-c1ac6d9694ed.png)

why it is not generating, even with general rosbag ?

any idea/suggestions would be helpful

thanks in advance

**Comment by matlabbe** [comment]
`/map -> /odom` is published only after rtabmap is correctly receiving topics. Which example did you try? If I do the [stereo demo](http://wiki.ros.org/rtabmap_ros#Stereo_mapping), it is ok:
```bash
$ roslaunch rtabmap_ros demo_stereo_outdoor.launch
$ rosbag play --clock stereo_outdoorA.bag
```
![screenshot from 2016-10-11 14 23 31](https://cloud.githubusercontent.com/assets/2319645/19282977/52ac40f8-8fbe-11e6-8e58-663cccb70522.png)
