### ISSUE TITLE
some question about turtlebot3_sim_rgbd_scan_demo.launch.py ​

### ISSUE THREAD

**Issue by ccblog-cmd** [introlab/rtabmap_ros#1250]
When I run turtlebot3_sim_rgbd_scan_demo.launch.py ​​--- vision and 2D radar fusion, rviz only shows the grid sub-map, not the 3D point cloud map. How can I set it up? In the example given by the author of RO2 humble branch, both are displayed in rviz.
This is my running result, rtabmap runs normally：
![image](https://github.com/user-attachments/assets/ab53cd2b-0988-4fc3-870a-eb95e9444d68)
![image](https://github.com/user-attachments/assets/06e53be9-544c-44fc-8ed4-e5a190c45230)
This is the author's running result：
![image](https://github.com/user-attachments/assets/5e39f796-5ed6-448f-9acc-ed1768358840)

**Comment by matlabbe** [comment]
The 3D point cloud is there in your screenshot. By default the nav2 rviz config shows an orthogonal view, you can change the View to Orbit under Views panel in rviz.

In the demo screenshot, the `rtabmap_rviz_plugins::MapCloud` plugin in rviz was used.

**Comment by ccblog-cmd** [comment]
> The 3D point cloud is there in your screenshot. By default the nav2 rviz config shows an orthogonal view, you can change the view to Orbit under Views panel in rviz.
> 
> In the demo screenshot, the `rtabmap_rviz_plugins::MapCloud` plugin in rviz was used.

thank you,it's ok.
