### ISSUE TITLE
The implementation of generating occupancy grid from pointcloud

### ISSUE THREAD

**Issue by Severn-Vergil** [introlab/rtabmap_ros#128]
Hi, Mathieu
Is the proj_map generated from cloud_map, by simply 'deleting' the Z dimension value? Where can I check out the corresponding codes?

Sincerely Thanks,
Severn

**Comment by willdzeng** [comment]
Hi Severn,

It first do ground detection and then project everything else to the ground to generate proj_map.
You can check out it here:
https://github.com/introlab/rtabmap_ros/blob/master/src/MapsManager.cpp#L653

Questions like this better to be asked in the forum.
http://official-rtab-map-forum.67519.x6.nabble.com/

**Comment by Severn-Vergil** [comment]
Thank you, willdzeng! I just know that there's a forum of RTABMAP :)
