### ISSUE TITLE
Missing dependency on image_geometry

### ISSUE THREAD

**Issue by tfoote** [introlab/rtabmap_ros#129]
There's a missing dependency on image_geometry I think this was an implicit dependency that was cleaned up by another dependency a week ago: https://github.com/ros-visualization/rviz/pull/1009

http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__rtabmap_ros__ubuntu_xenial_amd64__binary/33/consoleFull
```
00:15:08.032 /tmp/binarydeb/ros-kinetic-rtabmap-ros-0.11.8/src/nodelets/rgbd_odometry.cpp:40:48: fatal error: image_geometry/stereo_camera_model.h: No such file or directory
```

**Comment by matlabbe** [comment]
Indeed, that [commit](https://github.com/introlab/rtabmap_ros/commit/40439707fd7c09bc89595c1b432ff62f285ef2ba) should do the job, included in that pull request: https://github.com/ros/rosdistro/pull/13013

cheers
