### ISSUE TITLE
Change turtlebot to Kinect+Odometry configurations 

### ISSUE THREAD

**Issue by Hoototo** [introlab/rtabmap_ros#130]
When I use Turtlebot2 to launch demo_turtlebot_mapping.launch file, my robot's configurations is Kinect+Odometry+Fake 2D laser from Kinect。 
But I want to put my robot into Kinect+Odometry,and I want to create with rtabmap node with proj_map topic a 2D occupancy grid map from the projection of the Kinect. How do I modify the demo_turtlebot_mapping.launch file.

**Comment by matlabbe** [comment]
See http://official-rtab-map-forum.67519.x6.nabble.com/Demo-RTAB-Map-on-Turtlebot-td439i40.html#a2189
