### ISSUE TITLE
rtabmap confused on orientation, drifts with map

### ISSUE THREAD

**Issue by natejgardner** [introlab/rtabmap_ros#138]
In localization mode, after turning the camera around once or twice, rtabmap totally loses orientation as if it's not localizing against a map at all. When I rotate, it's obvious to me rtabmap's frame is totally wrong, as if there's no relationship between `odom` and `map`. It looks like this in the rtabmap viewer. The first image is the start position. The second is after I've spun the camera a few times. Examining in RViz, it's clear that the odometry drifts significantly in position and orientation. It's also as if there is no transform between the live scan and the map, even though rtabmap claims to be seeing features from the map and a few objects that were not in my original scan show as black, indicting rtabmap seems to be correctly localizing against known features. Yet everything is sideways.

How can I get rtabmap to consistently localize against a fixed map?

![before-failure](https://cloud.githubusercontent.com/assets/8813777/21340551/46321aaa-c63c-11e6-89a9-31f2711d88b0.png)
![after-failure](https://cloud.githubusercontent.com/assets/8813777/21340554/49c63110-c63c-11e6-9fa3-129cffd86922.png)

**Comment by natejgardner** [comment]
With additional testing, rtabmap seems not to have any global idea of the map's coordinates. Doesn't make much sense. It loop closes, but it has no idea which direction it's facing.

**Comment by matlabbe** [comment]
Are you using the same launch file as in this [tutorial](http://wiki.ros.org/rtabmap_ros/Tutorials/HandHeldMapping) (with command lines used)? Which I could use to try to reproduce the problem.

At first view, it seems related to `RGBD/OptimizeFromGraphEnd` parameter. If true, the map is transformed in current odometry frame, rotating the map if the camera was started tilted differently than when the map was first created (e.g., TF /map -> /odom will be always null). If false, the current odometry frame is transformed in map frame, so the map should look at the same pose as before, but the camera is moved/rotated accordingly to localization (e.g., TF /map -> /odom would be not null).


cheers,
Mathieu

**Comment by tekomoro** [comment]
> Are you using the same launch file as in this [tutorial](http://wiki.ros.org/rtabmap_ros/Tutorials/HandHeldMapping) (with command lines used)? Which I could use to try to reproduce the problem.
> 
> At first view, it seems related to `RGBD/OptimizeFromGraphEnd` parameter. If true, the map is transformed in current odometry frame, rotating the map if the camera was started tilted differently than when the map was first created (e.g., TF /map -> /odom will be always null). If false, the current odometry frame is transformed in map frame, so the map should look at the same pose as before, but the camera is moved/rotated accordingly to localization (e.g., TF /map -> /odom would be not null).
> 
> cheers,
> Mathieu


i use zed camera can i change RGBD/OptimizeFromGraphEnd parameter with my synchronized camera or what can i do to improve lozalizing ?
