### ISSUE TITLE
CoreNode problem

### ISSUE THREAD

**Issue by QinZiwen** [introlab/rtabmap_ros#150]
I am go to read your code of rtabmap_ros. The code confuse me when I look at "nodelet.load(nodelet_name, "rtabmap_ros/rtabmap", remap, nargv);" in CoreNode.cpp line 92. I don't know where "rtabmap_ros/rtabmap" is?

**Comment by matlabbe** [comment]
For nodelets, to know which class they are referring, see [nodelet_plugins.xml](https://github.com/introlab/rtabmap_ros/blob/835cfbc131a899032a0d562474699afca7486323/nodelet_plugins.xml#L3-L9). In this case CoreWrapper is the nodelet.

cheers

**Comment by QinZiwen** [comment]
Yes,Thanks for your help!
