### ISSUE TITLE
uFormat not declare

### ISSUE THREAD

**Issue by HoangGiang88** [introlab/rtabmap_ros#152]
Hi, 
Im try rtabmap with ros-indigo
the errors compiling as follow :
../stereo_odometry.cpp: In member function ‘virtual void rtabmap_ros::StereoOdometry::onOdomInit()’:
../nodelets/stereo_odometry.cpp:122:40: error: ‘uFormat’ was not declared in this scope

**Comment by matlabbe** [comment]
Hi,
The commit  above should fix the problem!

cheers

**Comment by HoangGiang88** [comment]
Hi,
I found that also in find_object_2d then include from that source,
compile is fine.
- #include "find_object/utilite/UConversion.h"


thanks :),
