### ISSUE TITLE
compiler error 

### ISSUE THREAD

**Issue by HoangGiang88** [introlab/rtabmap_ros#154]
Hi,
I have tried on desktop and it worked well,
but install on ubuntu(Tegra K1 kit)
-  git clone --branch 0.11.13 https://github.com/introlab/rtabmap.git rtabmap
-  cd rtabmap/build
-  cmake ..
-  make -j4
-  sudo make install
then got compiler error as follow:

[ 10%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/DBDriver.cpp.o
c++: internal compiler error: Killed (program cc1plus)

Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [tools/ExtractObject/CMakeFiles/extractObject.dir/main.cpp.o] Error 4
make[1]: *** [tools/ExtractObject/CMakeFiles/extractObject.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

[ 10%] Building CXX object corelib/src/CMakeFiles/rtabmap_core.dir/DBDriverSqlite3.cpp.o
c++: internal compiler error: Killed (program cc1plus)

Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [corelib/src/CMakeFiles/rtabmap_core.dir/Rtabmap.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [corelib/src/CMakeFiles/rtabmap_core.dir/all] Error 2
make: *** [all] Error 2
ubuntu@tegra-ubuntu:~/rtabmap/build$ vim ///usr/share/doc/gcc-4.8/README.Bugs

**Comment by HoangGiang88** [comment]
use that branch is compiled 
git clone --branch kinetic-devel https://github.com/introlab/rtabmap.git rtabmap

**Comment by matlabbe** [comment]
`The error c++: internal compiler error: Killed (program cc1plus)` seems like an out of memory compiler error. Try "`make -j1`" instead of "`make -j4`"  or increase your swap memory.

cheers,
Mathieu

**Comment by HoangGiang88** [comment]
Also close all running task for save memory.
thanks y :)
