### ISSUE TITLE
Rtabmapviz and Visual Odometry process keeps dying on start-up

### ISSUE THREAD

**Issue by JoshuaSiy** [introlab/rtabmap_ros#157]
Hello, i hope i am not making a replicated issue or any disturbances. However i am having problems trying to start up rtabmap_ros . Rtabmapviz and visual odometry keeps dying immediately without even bringing me to the gui of rtabmap_ros. I'm not sure if any errors will be newly produced after this one is resolved. I tried my best to search the issues forums and i am not pretty sure what to do since many of the cases doesn't seem to correspond with what's happening in my case.

Level of intelligence: Newbie at Linux and ROS (including cmake, C++ and python)

things i installed : Rtabmap, ROS-kinetic,rtabmap_ros, iai_kinect2  ubuntu 16.04, opencv 2.4.11 , cuda 
Software: Everything in the optional parts and needed parts and dependencies inside the instructions of iai kienct2 and rtabmap/rtabmap_ros except for beignet from the instructions(incompatible according to clinfo) which i built beignet1.3 from source.

Extraordinary things i did aside from the instruction: edited CMakelists [cvsba, rtabmap, rtabmapros, and iai kinect2] on lines regarding find_package(OPENCV REQUIRED) To find_package(OPENCV 2.4.11 REQUIRED)

Hardware: Intel i7  and Nvidia GEFORCE GTX1050

Things i did without understanding. Recompiled everything by deleting build folders, and devel repeatedly and using cmake  and catkin_make with instructions given by instructions.

Details that might be helpful:
standalone rtabmap works fine
kinect2_bridge.launch works with rosrun kinect2_viewer kinect2_viewer sd cloud 
./Protonect cl,gl,cuda, and cpu works fine 
If i  launch the rtabmap_ros launch rgbdmapping in any form including kienct2 same error produced below (roslaunch rtabmap_ros rgbd_mapping_kinect2.launch resolution:=qhd)
$rosrun rtabmap_ros rtabmapviz doesn't not work: segmentation fault(core dumped)

**Errors produced:**
[ INFO] [1489643274.416961031]: Setting RTAB-Map parameter "Vis/MinInliers"="20"
[rtabmap/rtabmapviz-4] process has died [pid 30553, exit code -11, cmd /home/nerga/catkin_ws/devel/lib/rtabmap_ros/rtabmapviz -d /home/nerga/catkin_ws/src/rtabmap_ros/launch/config/rgbd_gui.ini rgb/image:=/kinect2/qhd/image_color_rect depth/image:=/kinect2/qhd/image_depth_rect rgb/camera_info:=/kinect2/qhd/camera_info __name:=rtabmapviz __log:=/home/nerga/.ros/log/50ee4348-0a0b-11e7-a66d-c8215827d99f/rtabmap-rtabmapviz-4.log].
log file: /home/nerga/.ros/log/50ee4348-0a0b-11e7-a66d-c8215827d99f/rtabmap-rtabmapviz-4*.log
[ INFO] [1489643274.588235580]: RTAB-Map detection rate = 1.000000 Hz
[ INFO] [1489643274.588321344]: rtabmap: Deleted database "/home/nerga/.ros/rtabmap.db" (--delete_db_on_start is set).
[ INFO] [1489643274.588336165]: rtabmap: Using database from "/home/nerga/.ros/rtabmap.db".
[rtabmap/visual_odometry-2] process has died [pid 30541, exit code -11, cmd /home/nerga/catkin_ws/devel/lib/rtabmap_ros/rgbd_odometry rgb/image:=/kinect2/qhd/image_color_rect depth/image:=/kinect2/qhd/image_depth_rect rgb/camera_info:=/kinect2/qhd/camera_info __name:=visual_odometry __log:=/home/nerga/.ros/log/50ee4348-0a0b-11e7-a66d-c8215827d99f/rtabmap-visual_odometry-2.log].
log file: /home/nerga/.ros/log/50ee4348-0a0b-11e7-a66d-c8215827d99f/rtabmap-visual_odometry-2*.log

**Errors produced: $rosrun rtabmap_ros rtabmapviz**
/home/nerga/catkin_ws/devel/lib/rtabmap_ros/map_assembler: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by /usr/local/lib/libfreenect2.so.0.2)
/home/nerga/catkin_ws/devel/lib/rtabmap_ros/map_assembler: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by /usr/local/lib/libfreenect2.so.0.2)
[ INFO] [1489659859.792993038]: /map_assembler(maps): grid_cell_size             = 0.050000
[ INFO] [1489659859.793042694]: /map_assembler(maps): grid_incremental           = false
[ INFO] [1489659859.793057704]: /map_assembler(maps): grid_size                  = 0.000000
[ INFO] [1489659859.793086990]: /map_assembler(maps): grid_eroded                = false
[ INFO] [1489659859.793101767]: /map_assembler(maps): grid_footprint_radius      = 0.000000
[ INFO] [1489659859.793114816]: /map_assembler(maps): map_filter_radius          = 0.000000
[ INFO] [1489659859.793128386]: /map_assembler(maps): map_filter_angle           = 30.000000
[ INFO] [1489659859.793140860]: /map_assembler(maps): map_cleanup                = true
[ INFO] [1489659859.793153981]: /map_assembler(maps): map_negative_poses_ignored = false
[ INFO] [1489659859.793166530]: /map_assembler(maps): map_negative_scan_ray_tracing = true
[ INFO] [1489659859.793179406]: /map_assembler(maps): cloud_output_voxelized     = true
[ INFO] [1489659859.793191965]: /map_assembler(maps): cloud_subtract_filtering   = false
[ INFO] [1489659859.793204367]: /map_assembler(maps): cloud_subtract_filtering_min_neighbors = 2
^COpenCV Error: Assertion failed (key_ == -1) in ~TLSDataContainer, file /tmp/binarydeb/ros-kinetic-opencv3-3.2.0/modules/core/src/system.cpp, line 1186
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.2.0/modules/core/src/system.cpp:1186: error: (-215) key_ == -1 in function ~TLSDataContainer

Aborted (core dumped)

**Comment by JoshuaSiy** [comment]
Okay i managed to fix rtabmap ROS, all i did was to make another workspace. and compiled rtabmap_ros along with vision opencv [DESPITE RTABMAP is linked to opencv2.4  rtabmapviz keeps on linking to ros-kinetic-opencv3.2, so you have to compile both rtabmap_ros with vision_opencv [i don't know why but this is how it worked on my side]  and build iai_kinect2 make another catkin workspace folder and compile it with given instruction to find libfreenect2. I don't know why did this happen, but some details and understanding would be nice. Feel free to close the issue, but i still want to know why. Thank you.

**Comment by matlabbe** [comment]
rtabmapviz uses cv_bridge, which would be linked to OpenCV3 on kinetic. So if rtabmapviz is linked to rtabmap library (which is on OpenCV2) and cv_bridge (which is on OpenCV3), it is likely that the app crashes on start. When rebuilding vision_opencv, cv_bridge will be now linked to same OpenCV version than rtabmap library (OpenCV2). Hope this explanation satisfy you!

cheers,
Mathieu

**Comment by JoshuaSiy** [comment]
Thank you.
