### ISSUE TITLE
No map data received from rtabmap. 

### ISSUE THREAD

**Issue by tanmayshankar** [introlab/rtabmap_ros#16]
Hello, 

I'm running Ubuntu 12.04, Ros Hydro, I have rtabmap_ros compiled from source (as per instructions). 
I am using a stereo camera with (I think) the Stereo B configuration. I have modified the demo_stereo_outdoor.launch file accordingly, by removing the node republishing, remapping to stereo_camera namespace, and set use_sim_time to false. The rtabmap node is running when I launch this file. I also changed base_footprint to base_link. 

I also set up a tf broadcaster between base_link frame and camera, and set it to a constant value (0 translation), since I am holding the camera. Now the issue is that all my rtabmap/cloud_map, rtabmap/map rtabmap/path  ... (blah blah blah) topics are empty when I echo them. In rviz, my camera frame is moving around with respect to the map frame, but I cannot view the map, the path, or any clouds (optimized or not). 

I think the issue could be arising from the following - 
1) rviz file could be incorrectly set up since it is the one being used for the demo stereo outdoor.
2) tf tree / frame ID's could be incorrect. This is surprising, since my tf tree is - map --> odom --> base_link --> camera, which seems correct to me. 

Also, another glitch that is occurring (but should not make a difference), is that I am supplying the camera frame id, which is an optical frame, but pointcloud frames are defined with a different orientation. 

1) Any suggestions on how to solve the mapping issue? 
2) Can anyone confirm what frame I am expected to supply to the node? 

Thanks!

**Comment by matlabbe** [comment]
There is an answer here: http://answers.ros.org/question/210614/no-map-data-for-rtabmap_ros/?answer=210765#post-id-210765
For further problems about this topic, continue on the ROS answers.
