### ISSUE TITLE
Rtabmapviz and standalone rtabmap keeps dying on start-up

### ISSUE THREAD

**Issue by zjsprit** [introlab/rtabmap_ros#162]
I build the rtabmap_ros from source and catkin_make succesfully in the Ubuntu 14.01. Used by ASUS Xtion and When I launch the Mapping mode, the Rtabmapviz keeps dying on start-up. But when I launch the rviz, it can workaround. So , I run the standalone $ rtabmap， the rtabmap keeps dying on start-up as follows:
[FATAL] (2017-04-10 21:20:56.050) MainWindow.cpp:2533::createAndAddCloudToMap() Condition (nodeId == data.id()) not met!

**Comment by matlabbe** [comment]
The commit above should fix the problem. Feel free to comment back if it doesn't work.
