### ISSUE TITLE
rgbd_mapping_kinect2.launch not working.

### ISSUE THREAD

**Issue by dani-carbonell** [introlab/rtabmap_ros#17]
I think that topic names have changed in the current version of the Kinect2 for ROS and "rgbd_mapping_kinect2.launch" is not longer working . Could you update this launchfile? 

Thanks :)

**Comment by matlabbe** [comment]
Updated! https://github.com/introlab/rtabmap_ros/commit/831ec5a1a261d9226d4c2bb9c036632243435802

Note that rtabmap nodes has also been updated to support TYPE_8UC1 images.
