### ISSUE TITLE
Catkin build skips rtabmap-ros if image_transport_plugins is present in the catkin workspace.

### ISSUE THREAD

**Issue by ChrisPsa** [introlab/rtabmap_ros#186]
I have compiled OpenCV from source and consequently needed to compile cv_bridge, image_transport and other packages that depend on OpenCV, in my catkin workspace. I use `catkin build` for the build process and have not tested `catkin_make`. The issue arises when image_transport_plugins metapackage is present in the catkin workspace. `Catkin build` takes into account the run_depend in the `package.xml` of rtabmap_ros, which depends on the metapackage image_transport_plugins. Although, it is not recommended to issue a dependency on a metapackage, so it ignores rtabmap_ros and never builds it. 

I found two workarounds for this,

1. The first and easiest is to just remove the dependency from the package.xml, in which case it builds normally, but I have not tested if all funcitonality is there.
2. The second solution is to remove the dependency from the package.xml and replace it with dependencies on each sub-package separately, like so:

```
-  <run_depend>image_transport_plugins</run_depend>
+  <run_depend>compressed_depth_image_transport</run_depend>
+  <run_depend>compressed_image_transport</run_depend>
+  <run_depend>theora_image_transport</run_depend>
```

This builds successfully, and all functionality is there.

**Comment by matlabbe** [comment]
Should be fixed by commit above. thx for reporting!
