### ISSUE TITLE
demo_two_kinects.launch failed in load nodelet /camera1/rgbd_sync and /camera2/rgbd_sync

### ISSUE THREAD

**Issue by Severn-Vergil** [introlab/rtabmap_ros#190]
Hi Mathieu,

I'm trying to run demo_two_kinects.launch, it works well on my previous notebook a week ago(rtabmap version 0.11.1), and I'm trying to run it on my new notebook, with new installed rtabmap and rtabmap_ros(rtabmap version 0.13.0).

The logs show that the nodelet /camera1/rgbd_sync not match with the type /rtabmap_ros/rgbd_sync, and I guess it can be modified from the param "group ns = "camera1" " from demo_two_kinects.launch, and I'm trying to fix it out.

## Environment
Ubuntu 14.04 + ROS Indigo 
Kinect V1 * 2 on Turtlebot Kobuki

## Logs

 **roslaunch rtabmap_ros demo_two_kinects.launch**  
========

... logging to /home/severn/.ros/log/96f0851c-71ae-11e7-8dae-c9342e4caeee/roslaunch-severn-21286.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://severn:33065/

summary

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21
 * /rtabmap/rgbd_odometry/Odom/FillInfoData: true
 * /rtabmap/rgbd_odometry/Odom/Strategy: 0
 * /rtabmap/rgbd_odometry/OdomF2M/MaxSize: 1000
 * /rtabmap/rgbd_odometry/Vis/CorNNType: 3
 * /rtabmap/rgbd_odometry/Vis/FeatureType: 6
 * /rtabmap/rgbd_odometry/Vis/InlierDistance: 0.02
 * /rtabmap/rgbd_odometry/Vis/MaxDepth: 4.0
 * /rtabmap/rgbd_odometry/Vis/MinInliers: 20
 * /rtabmap/rgbd_odometry/frame_id: base_link
 * /rtabmap/rgbd_odometry/rgbd_cameras: 2
 * /rtabmap/rgbd_odometry/subscribe_rgbd: True
 * /rtabmap/rgbd_odometry/wait_for_transform: True
 * /rtabmap/rtabmap/Grid/FromDepth: false
 * /rtabmap/rtabmap/Vis/InlierDistance: 0.02
 * /rtabmap/rtabmap/Vis/MinInliers: 10
 * /rtabmap/rtabmap/frame_id: base_link
 * /rtabmap/rtabmap/gen_scan: True
 * /rtabmap/rtabmap/map_negative_poses_ignored: False
 * /rtabmap/rtabmap/map_negative_scan_empty_ray_tracing: False
 * /rtabmap/rtabmap/rgbd_cameras: 2
 * /rtabmap/rtabmap/subscribe_depth: False
 * /rtabmap/rtabmap/subscribe_rgbd: True
 * /rtabmap/rtabmap/wait_for_transform: True
 * /rtabmap/rtabmapviz/frame_id: base_link
 * /rtabmap/rtabmapviz/rgbd_cameras: 2
 * /rtabmap/rtabmapviz/subscribe_depth: False
 * /rtabmap/rtabmapviz/subscribe_odom_info: True
 * /rtabmap/rtabmapviz/subscribe_rgbd: True
 * /rtabmap/rtabmapviz/wait_for_transform: True

NODES
  /camera2/
    rgbd_sync (nodelet/nodelet)
  /camera1/
    rgbd_sync (nodelet/nodelet)
  /rtabmap/
    rgbd_odometry (rtabmap_ros/rgbd_odometry)
    rtabmap (rtabmap_ros/rtabmap)
    rtabmapviz (rtabmap_ros/rtabmapviz)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[camera1/rgbd_sync-1]: started with pid [21304]
process[camera2/rgbd_sync-2]: started with pid [21305]
process[rtabmap/rgbd_odometry-3]: started with pid [21306]
process[rtabmap/rtabmap-4]: started with pid [21311]
process[rtabmap/rtabmapviz-5]: started with pid [21318]
[ INFO] [1501038186.136761520]: Starting node...
[ INFO] [1501038186.214683813]: Initializing nodelet with 8 worker threads.
[ INFO] [1501038186.263984562]: Initializing nodelet with 8 worker threads.
[ INFO] [1501038186.288686158]: Starting node...
[FATAL] [1501038186.505627168]: Failed to load nodelet '/camera1/rgbd_sync` of type `rtabmap_ros/rgbd_sync` to manager `camera1_nodelet_manager'
[ INFO] [1501038186.531892417]: rtabmapviz: Using configuration from "/home/severn/rtabmap_ws/catkin_ws/src/rtabmap_ros/launch/config/rgbd_gui.ini"
[FATAL] [1501038186.562018655]: Failed to load nodelet '/camera2/rgbd_sync` of type `rtabmap_ros/rgbd_sync` to manager `camera2_nodelet_manager'
[ INFO] [1501038186.731018993]: /rtabmap/rtabmap(maps): map_filter_radius          = 0.000000
[ INFO] [1501038186.731063079]: /rtabmap/rtabmap(maps): map_filter_angle           = 30.000000
[ INFO] [1501038186.731160074]: /rtabmap/rtabmap(maps): map_cleanup                = true
[ INFO] [1501038186.731186536]: /rtabmap/rtabmap(maps): map_negative_poses_ignored = false
[ INFO] [1501038186.731249490]: /rtabmap/rtabmap(maps): map_negative_scan_ray_tracing = false
[ INFO] [1501038186.731268879]: /rtabmap/rtabmap(maps): cloud_output_voxelized     = true
[ INFO] [1501038186.731327962]: /rtabmap/rtabmap(maps): cloud_subtract_filtering   = false
[ INFO] [1501038186.731348326]: /rtabmap/rtabmap(maps): cloud_subtract_filtering_min_neighbors = 2
[camera1/rgbd_sync-1] process has died [pid 21304, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load rtabmap_ros/rgbd_sync camera1_nodelet_manager rgb/image:=rgb/image_rect_color depth/image:=depth_registered/image_raw rgb/camera_info:=rgb/camera_info __name:=rgbd_sync __log:=/home/severn/.ros/log/96f0851c-71ae-11e7-8dae-c9342e4caeee/camera1-rgbd_sync-1.log].
log file: /home/severn/.ros/log/96f0851c-71ae-11e7-8dae-c9342e4caeee/camera1-rgbd_sync-1*.log
[ INFO] [1501038186.848423007]: rtabmap: frame_id      = base_link
[ INFO] [1501038186.848473173]: rtabmap: map_frame_id  = map
[ INFO] [1501038186.848502745]: rtabmap: tf_delay      = 0.050000
[ INFO] [1501038186.848531938]: rtabmap: tf_tolerance  = 0.100000
[ INFO] [1501038186.848556511]: rtabmap: odom_sensor_sync   = false
[camera2/rgbd_sync-2] process has died [pid 21305, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load rtabmap_ros/rgbd_sync camera2_nodelet_manager rgb/image:=rgb/image_rect_color depth/image:=depth_registered/image_raw rgb/camera_info:=rgb/camera_info __name:=rgbd_sync __log:=/home/severn/.ros/log/96f0851c-71ae-11e7-8dae-c9342e4caeee/camera2-rgbd_sync-2.log].
log file: /home/severn/.ros/log/96f0851c-71ae-11e7-8dae-c9342e4caeee/camera2-rgbd_sync-2*.log
[ INFO] [1501038187.018812264]: Setting odometry parameter "Odom/FillInfoData"="true"
[ INFO] [1501038187.209002979]: Setting odometry parameter "Odom/Strategy"="0"
[ INFO] [1501038187.261474117]: Reading parameters from the ROS server...
[ INFO] [1501038187.263674515]: Setting odometry parameter "OdomF2M/MaxSize"="1000"
[ INFO] [1501038187.460742700]: Setting RTAB-Map parameter "Grid/FromDepth"="false"
[ INFO] [1501038188.113951391]: Setting odometry parameter "Vis/CorNNType"="3"
[ INFO] [1501038188.152661052]: Setting odometry parameter "Vis/FeatureType"="6"
[ INFO] [1501038188.167423983]: Setting odometry parameter "Vis/InlierDistance"="0.02"
[ INFO] [1501038188.183133914]: Setting odometry parameter "Vis/MaxDepth"="4.0"
[ INFO] [1501038188.204466342]: Parameters read = 0
[ INFO] [1501038188.211327602]: Setting odometry parameter "Vis/MinInliers"="20"
[ INFO] [1501038188.449425556]: /rtabmap/rtabmapviz: queue_size    = 10
[ INFO] [1501038188.449472682]: /rtabmap/rtabmapviz: rgbd_cameras = 2
[ INFO] [1501038188.449499369]: /rtabmap/rtabmapviz: approx_sync   = true
[ INFO] [1501038188.449552928]: Setup rgbd2 callback
[ INFO] [1501038188.527775215]: 
/rtabmap/rtabmapviz subscribed to (approx sync):
   /rtabmap/odom,
   /camera1/rgbd_image,
   /camera2/rgbd_image,
   /rtabmap/odom_info
[ INFO] [1501038188.527865004]: rtabmapviz started.
[ INFO] [1501038188.750872742]: 
/rtabmap/rgbd_odometry subscribed to (approx sync):
   /camera1/rgbd_image,
   /camera2/rgbd_image
[ WARN] [1501038193.528036400]: /rtabmap/rtabmapviz: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
/rtabmap/rtabmapviz subscribed to (approx sync):
   /rtabmap/odom,
   /camera1/rgbd_image,
   /camera2/rgbd_image,
   /rtabmap/odom_info
[ WARN] [1501038193.751195116]: /rtabmap/rgbd_odometry: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. 
/rtabmap/rgbd_odometry subscribed to (approx sync):
   /camera1/rgbd_image,
   /camera2/rgbd_image
[ INFO] [1501038194.460631117]: Setting RTAB-Map parameter "Vis/InlierDistance"="0.02"
[ INFO] [1501038194.511206214]: Setting RTAB-Map parameter "Vis/MinInliers"="10"
[ INFO] [1501038196.040420015]: RTAB-Map detection rate = 1.000000 Hz
[ INFO] [1501038196.040553917]: rtabmap: Deleted database "/home/severn/.ros/rtabmap.db" (--delete_db_on_start or -d are set).
[ INFO] [1501038196.040583530]: rtabmap: Using database from "/home/severn/.ros/rtabmap.db".
[ INFO] [1501038196.276336056]: rtabmap: Database version = "0.13.1".
[ INFO] [1501038196.403094586]: /rtabmap/rtabmap: queue_size    = 10
[ INFO] [1501038196.403133317]: /rtabmap/rtabmap: rgbd_cameras = 2
[ INFO] [1501038196.403150687]: /rtabmap/rtabmap: approx_sync   = true
[ INFO] [1501038196.403216029]: Setup rgbd2 callback
[ INFO] [1501038196.467622175]: 
/rtabmap/rtabmap subscribed to (approx sync):
   /rtabmap/odom,
   /camera1/rgbd_image,
   /camera2/rgbd_image
[ INFO] [1501038196.505766276]: rtabmap 0.13.1 started...
[ WARN] [1501038198.528295681]: /rtabmap/rtabmapviz: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
/rtabmap/rtabmapviz subscribed to (approx sync):
   /rtabmap/odom,
   /camera1/rgbd_image,
   /camera2/rgbd_image,
   /rtabmap/odom_info

 **roslaunch openni_launch camera1.launch**  
========

... logging to /home/severn/.ros/log/96f0851c-71ae-11e7-8dae-c9342e4caeee/roslaunch-severn-19788.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://severn:36542/

summary

PARAMETERS
 * /camera1/camera1_nodelet_manager/num_worker_threads: 4
 * /camera1/depth_rectify_depth/interpolation: 0
 * /camera1/depth_registered_rectify_depth/interpolation: 0
 * /camera1/disparity_depth/max_range: 4.0
 * /camera1/disparity_depth/min_range: 0.5
 * /camera1/disparity_registered_hw/max_range: 4.0
 * /camera1/disparity_registered_hw/min_range: 0.5
 * /camera1/disparity_registered_sw/max_range: 4.0
 * /camera1/disparity_registered_sw/min_range: 0.5
 * /camera1/driver/depth_camera_info_url: 
 * /camera1/driver/depth_frame_id: camera1_depth_opt...
 * /camera1/driver/depth_registration: True
 * /camera1/driver/device_id: 3@34
 * /camera1/driver/rgb_camera_info_url: 
 * /camera1/driver/rgb_frame_id: camera1_rgb_optic...
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /camera1/
    camera1_nodelet_manager (nodelet/nodelet)
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_hw_metric_rect (nodelet/nodelet)
    depth_registered_metric (nodelet/nodelet)
    depth_registered_rectify_depth (nodelet/nodelet)
    depth_registered_sw_metric_rect (nodelet/nodelet)
    disparity_depth (nodelet/nodelet)
    disparity_registered_hw (nodelet/nodelet)
    disparity_registered_sw (nodelet/nodelet)
    driver (nodelet/nodelet)
    ir_rectify_ir (nodelet/nodelet)
    points_xyzrgb_hw_registered (nodelet/nodelet)
    points_xyzrgb_sw_registered (nodelet/nodelet)
    register_depth_rgb (nodelet/nodelet)
    rgb_debayer (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
    rgb_rectify_mono (nodelet/nodelet)
  /
    camera1_base_link (tf/static_transform_publisher)
    camera1_base_link1 (tf/static_transform_publisher)
    camera1_base_link2 (tf/static_transform_publisher)
    camera1_base_link3 (tf/static_transform_publisher)
    robot_camera1_link (tf/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[camera1/camera1_nodelet_manager-1]: started with pid [19807]
process[camera1/driver-2]: started with pid [19808]
process[camera1/rgb_debayer-3]: started with pid [19809]
process[camera1/rgb_rectify_mono-4]: started with pid [19810]
process[camera1/rgb_rectify_color-5]: started with pid [19811]
process[camera1/ir_rectify_ir-6]: started with pid [19817]
process[camera1/depth_rectify_depth-7]: started with pid [19821]
process[camera1/depth_metric_rect-8]: started with pid [19829]
process[camera1/depth_metric-9]: started with pid [19836]
process[camera1/depth_points-10]: started with pid [19851]
process[camera1/register_depth_rgb-11]: started with pid [19862]
process[camera1/points_xyzrgb_sw_registered-12]: started with pid [19867]
process[camera1/depth_registered_sw_metric_rect-13]: started with pid [19874]
process[camera1/depth_registered_rectify_depth-14]: started with pid [19877]
process[camera1/points_xyzrgb_hw_registered-15]: started with pid [19884]
process[camera1/depth_registered_hw_metric_rect-16]: started with pid [19902]
process[camera1/depth_registered_metric-17]: started with pid [19910]
process[camera1/disparity_depth-18]: started with pid [19924]
process[camera1/disparity_registered_sw-19]: started with pid [19933]
process[camera1/disparity_registered_hw-20]: started with pid [19936]
process[robot_camera1_link-21]: started with pid [19946]
process[camera1_base_link-22]: started with pid [19954]
process[camera1_base_link1-23]: started with pid [19960]
process[camera1_base_link2-24]: started with pid [19962]
process[camera1_base_link3-25]: started with pid [19968]
[ INFO] [1501038168.352711371]: Initializing nodelet with 4 worker threads.
Warning: USB events thread - failed to set priority. This might cause loss of data...
Warning: USB events thread - failed to set priority. This might cause loss of data...
[ INFO] [1501038169.271017512]: Number devices connected: 2
[ INFO] [1501038169.271121650]: 1. device on bus 003:34 is a SensorKinect (2ae) from PrimeSense (45e) with serial id '0000000000000000'
[ INFO] [1501038169.271148572]: 2. device on bus 003:38 is a SensorKinect (2ae) from PrimeSense (45e) with serial id 'A00367D04979136A'
[ INFO] [1501038169.274536702]: Searching for device with bus@address = 3@34
[ INFO] [1501038170.314469921]: Opened 'SensorKinect' on bus 3:34 with serial number '0000000000000000'
[ INFO] [1501038170.455692430]: rgb_frame_id = 'camera1_rgb_optical_frame' 
[ INFO] [1501038170.455751329]: depth_frame_id = 'camera1_depth_optical_frame' 
[ WARN] [1501038170.476676677]: Camera calibration file /home/severn/.ros/camera_info/depth_0000000000000000.yaml not found.
[ WARN] [1501038170.476735874]: Using default parameters for IR camera calibration.
[ERROR] [1501038186.505226194]: Failed to load nodelet [/camera1/rgbd_sync] of type [rtabmap_ros/rgbd_sync] even after refreshing the cache: MultiLibraryClassLoader: Could not create object of class type rtabmap_ros::RGBDSync as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[ERROR] [1501038186.505396001]: The error before refreshing the cache was: Failed to load library /home/severn/rtabmap_ws/catkin_ws/devel/lib//librtabmap_ros.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = dlopen: cannot load any more object with static TLS)

Thank you in advance, 
Severn
![screenshot from 2017-07-26 15 33 45](https://user-images.githubusercontent.com/10786161/28609584-e5e3eb5a-7217-11e7-9fd0-619180255847.png)
![screenshot from 2017-07-26 15 33 59](https://user-images.githubusercontent.com/10786161/28609593-ee15d982-7217-11e7-8418-bc181fc5d069.png)

**The original log file**
https://drive.google.com/file/d/0B5Jvn2hvZkgQVUdULXB0alZLZjQ/view?usp=sharing

**Comment by matlabbe** [comment]
`rgbd_sync` nodelets cannot be loaded, not sure why as they are loaded correctly on my system. Could be a compilation problem. What if you clean the catkin build directory and redo a catkin_make?

**Comment by nathangeorge1** [comment]
I have the same/similar error, but cleaning the catkin build/devel directory didn't help me; this is the error on the Jetson Nano

```
[N=/rtabmap/rgbd_sync,F=Loader::load-300]: Failed to load nodelet [/rtabmap/rgbd_sync] of type [rtabmap_ros/rgbd_sync] even after refreshing the cache: MultiLibraryClassLoader: Could not create object of class type rtabmap_ros::RGBDSync as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[N=/rtabmap/rgbd_sync,F=Loader::load-301]: The error before refreshing the cache was: Failed to load library /opt/ros/melodic/lib//librtabmap_plugins.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /opt/ros/melodic/lib//librtabmap_plugins.so: undefined symbol: _ZN10costmap_2d12CostmapLayer9clearAreaEiiii)
[rtabmap/rgbd_sync-4] process has died [pid 27738, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet standalone rtabmap_ros/rgbd_sync /rtabmap/grid_map:=/map /cmd_vel/managed:=/motor_controller/command /cmd_vel:=/motor_controller/command_no_stamp rgb/image:=/zed/zed_node/rgb/image_rect_color depth/image:=/zed/zed_node/depth/depth_registered rgb/camera_info:=/zed/zed_node/rgb/camera_info rgbd_image:=rgbd_image __name:=rgbd_sync __log:=/home/nvidia/.ros/log/698aff04-800a-11ea-9abc-06159326cf59/rtabmap-rgbd_sync-4.log].
log file: /home/nvidia/.ros/log/698aff04-800a-11ea-9abc-06159326cf59/rtabmap-rgbd_sync-4*.log

```

There appears to be 2 slashes on one of the lines:

`/opt/ros/melodic/lib//librtabmap_plugins.so: undefined symbol`

**Comment by nathangeorge1** [comment]
I fixed this error by doing `sudo apt update` and `sudo apt upgrade`.

**Comment by lifuguan** [comment]
So is there any solution for this issue? I've faced it in version 0.19.3.

**Comment by derektan95** [comment]
I am not sure if this fixes anyone's issues. When I faced this issue on my Nvidia TX2 (while attempting to compile opencv with CUDA), I realized that I forgot to run the command: `sudo ldconfig -v`.

**Comment by hank870907** [comment]
I am facing the same issue on Nvidia agx xavier!
