### ISSUE TITLE
Armhf indigo builds are failing due to running out of memory

### ISSUE THREAD

**Issue by tfoote** [introlab/rtabmap_ros#195]
We don't have instrumentation of the memory usage. But there has not been a successful build since late july when a rebuild was triggered for new dependencies. And all of those builds that ran to the end seem to have been terminated for out of memory issues.

Looking at the last build it was a new release of geometry2 which might be causing increased memory usage that pushed this package over the limit.

Failing build: http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__rtabmap_ros__ubuntu_trusty_armhf__binary/

**Comment by matlabbe** [comment]
We can blacklist the armhf build as I didn't plan to update the Indigo version for backward compatibility issues (interface slightly different with latest code version). The latest version (which is on kinetic/lunar) has CoreWrapper.cpp split into multiple files to reduce memory used per file.

**Comment by tfoote** [comment]
Ok, thanks I've blacklisted it in https://github.com/ros-infrastructure/ros_buildfarm_config/pull/90
