### ISSUE TITLE
Not able to see all options on GUI

### ISSUE THREAD

**Issue by rs1990** [introlab/rtabmap_ros#21]
Hello, I am not able to see all the options on the top of the GUI. All i see is a pause button. I used sudo apt-get install to install it on my system. 

![screenshot from 2015-07-09 11 25 10](https://cloud.githubusercontent.com/assets/5892630/8600740/3a081104-262d-11e5-8871-4518b353c9f0.png)

and solution?

**Comment by matlabbe** [comment]
On ROS, the core is running in [rtabmap](http://wiki.ros.org/rtabmap_ros#rtabmap) node. So Start/Stop actions are not used in the GUI (as well as New/Open database). Only pause action is still here, which calls `/rtabmap/pause` service under the hood.

Well, just saw that on [rtabmapviz](http://wiki.ros.org/rtabmap_ros#rtabmapviz) documentation, the screenshot has "Pause on loop closure, ... , Mapping, Localization" buttons. In recent versions, these actions are in the Edit menu. I'll update the screenshot soon.

For you red screen, make sure to start the Kinect 1 to 3 meters from objects so the odometry can be computed.

**Comment by rs1990** [comment]
Thank you so much for your prompt reply. You have done some really amazing
work with this package.

Cheers

Raghavendra.
