### ISSUE TITLE
Does the localization mode just  maintain a local map?

### ISSUE THREAD

**Issue by harbouryi** [introlab/rtabmap_ros#210]
When i ran it in the localization mode, i found it hard to relocalize.  When i arrived at where i finished the mapping , may be the last few frames, it localization success , But in  other place , it did not success. So , dose the localization mode just  maintain a local map?

**Comment by matlabbe** [comment]
What are the parameters used in localization? As localization is quite a lot cheaper than SLAM, you can make sure that all locations are in WM when launching in localization mode like in [rtabmap.launch](https://github.com/introlab/rtabmap_ros/blob/db7118554d2a1c293f4889bbd6628c4f5839122c/launch/rtabmap.launch#L195-L197):
```xml
<!-- localization mode -->
<param     if="$(arg localization)" name="Mem/IncrementalMemory" type="string" value="false"/>
<param unless="$(arg localization)" name="Mem/IncrementalMemory" type="string" value="true"/>
<param name="Mem/InitWMWithAllNodes" type="string" value="$(arg localization)"/>
```
