### ISSUE TITLE
Losing part of the map in localization mode

### ISSUE THREAD

**Issue by smail1229** [introlab/rtabmap_ros#211]
Hello,
I have a problem about localization mode.
First, I used rtabmap to generate a grid map like this:
![default](https://user-images.githubusercontent.com/11934648/33822018-039e2666-de91-11e7-9341-93a0886759dd.png)
Then, I chose the localization mode, and the map it published look like this:
![default](https://user-images.githubusercontent.com/11934648/33822084-48179b92-de91-11e7-977b-79a3405eb0e0.png)

We can see that part of grid map on the left and bottom are missing.
Actually, I tried the localization mode several times and sometimes the gird map loses part of itself randomly.

I want to know how to get the complete map

Thank you

**Comment by matlabbe** [comment]
See this answer: https://github.com/introlab/rtabmap_ros/issues/210#issuecomment-350729981

With these parameters, you should get always the global map.

**Comment by smail1229** [comment]
Thank you! The problem is solved
