### ISSUE TITLE
rtabmap_ros mapping with Realsense D415/D435 support

### ISSUE THREAD

**Issue by fiorano10** [introlab/rtabmap_ros#223]
When will the support for Intel Realsense D415/D435 (ROS Kinetic/ Ubuntu 16.04) be available for SLAM implementation?

**Comment by matlabbe** [comment]
Should be already working, see this post: https://github.com/introlab/rtabmap/issues/262#issuecomment-361803115

**Comment by somebodyus** [comment]
For D415, you can use the following command:

`roslaunch realsense2_camera rs_camera.launch`
`roslaunch rtabmap_ros rtabmap.launch rtabmap_args:="--delete_db_on_start" rviz:=true rtabmapviz:=false depth_topic:=/camera/depth/image_rect_raw rgb_topic:=/camera/color/image_raw camera_info_topic:=/camera/color/camera_info
`
