### ISSUE TITLE
[realsense_ros_person-3] process has died exit code -6 & Unsupported ROS image format: 16UC1

### ISSUE THREAD

**Issue by JanhviK** [introlab/rtabmap_ros#254]
While entering the following command:

`roslaunch realsense_ros_person demo_person_tracking.launch` 

for intel realsense camera in catkin workspace in ros kinetic environment,
I encountered the error:
```
[ERROR] [1529485355.268396466]: Unsupported ROS image format: 16UC1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unsupported ROS image format
[realsense_ros_person-3] process has died [pid 19040, exit code -6, cmd /opt/ros/kinetic/lib/nodelet/nodelet standalone realsense_ros_person/TNodeletPt __name:=realsense_ros_person __log:=/home/janhvi/.ros/log/ce199cba-7467-11e8-8c5f-30e37a258f73/realsense_ros_person-3.log].
log file: /home/janhvi/.ros/log/ce199cba-7467-11e8-8c5f-30e37a258f73/realsense_ros_person-3*.log

```

Can anyone help regarding this issue?

**Comment by matlabbe** [comment]
It is not rtabmap related. I suggest to ask to on realsense_ros github: https://github.com/IntelRealSense/realsense_samples_ros or https://github.com/intel-ros/realsense

cheers,
Mathieu
