### ISSUE TITLE
rtabmap dies on loop closure

### ISSUE THREAD

**Issue by kemfic** [introlab/rtabmap_ros#257]
I'm trying to run the sensor_fusion example in rtabmap. Whenever a loop closure is encountered, I get the following error, and rtabmap dies:

```[FATAL] (2018-06-27 10:00:14.131) OptimizerG2O.cpp:538::optimize() Condition (optimizer.verifyInformationMatrices()) not met!```

This doesn't happen when I run rtabmap without sensor fusion. I've tried the solution suggested [here](https://github.com/introlab/rtabmap_ros/issues/239), but have had no luck in getting it to work.

**Comment by matlabbe** [comment]
See http://official-rtab-map-forum.67519.x6.nabble.com/g2o-error-on-loop-closure-td4707.html#a4725
