### ISSUE TITLE
Two Kinect playback odometry issue

### ISSUE THREAD

**Issue by frushton** [introlab/rtabmap_ros#262]
I am trying to modify the two Kinect launch file so that I can play bagfiles and have rtabmap run on the topics published by the bagfile. I have it working for when I do not try to republish /tf and /tf_static, so I can replay bagfiles as long as the calibration (of the extrinsics) was correct at the time of the recording. However, I have a bagfile recorded that does not have the correct /tf and /tf_static, but it does not work when I try to modify them. When I play the bagfile, I use the following command:

rosbag play -d 8 --clock /camera1/rgb/image_rect_color/compressed:=/compressed1/rgb/image_rect_color/compressed /camera2/rgb/image_rect_color/compressed:=/compressed2/rgb/image_rect_color/compressed /tf:=/foo1 /tf_static:=/foo2 [file.bag]

Here is the launchfile (it has a .txt extension so I could upload it, trying to copy it here was giving me trouble, and half of the code was not appearing). Note that I have commented out the rosbag play section in the launch file. It throws an error for some reason within the launch file, so I just manually do the same command in another terminal:

[working_demo_two_kinects.txt](https://github.com/introlab/rtabmap_ros/files/2185480/working_demo_two_kinects.txt)

Here is the output from the console (I get the same output when I make sure the bagfile is already playing before launching the launch file as well):

... logging to /home/e4e/.ros/log/760957d8-8527-11e8-b35d-9cb6d0177589/roslaunch-e4e-GS63VR-6RF-10936.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://e4e-GS63VR-6RF:46443/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /rtabmap/rgbd_odometry/Odom/FillInfoData: true
 * /rtabmap/rgbd_odometry/Odom/Strategy: 0
 * /rtabmap/rgbd_odometry/OdomF2M/MaxSize: 1000
 * /rtabmap/rgbd_odometry/Vis/CorNNType: 3
 * /rtabmap/rgbd_odometry/Vis/EstimationType: 0
 * /rtabmap/rgbd_odometry/Vis/FeatureType: 6
 * /rtabmap/rgbd_odometry/Vis/InlierDistance: 0.02
 * /rtabmap/rgbd_odometry/Vis/MaxDepth: 4.0
 * /rtabmap/rgbd_odometry/Vis/MinInliers: 20
 * /rtabmap/rgbd_odometry/frame_id: base_link
 * /rtabmap/rgbd_odometry/rgbd_cameras: 2
 * /rtabmap/rgbd_odometry/subscribe_rgbd: True
 * /rtabmap/rgbd_odometry/wait_for_transform: True
 * /rtabmap/rtabmap/Grid/FromDepth: false
 * /rtabmap/rtabmap/Vis/EstimationType: 0
 * /rtabmap/rtabmap/Vis/InlierDistance: 0.02
 * /rtabmap/rtabmap/Vis/MinInliers: 10
 * /rtabmap/rtabmap/frame_id: base_link
 * /rtabmap/rtabmap/gen_scan: True
 * /rtabmap/rtabmap/map_negative_poses_ignored: False
 * /rtabmap/rtabmap/map_negative_scan_empty_ray_tracing: False
 * /rtabmap/rtabmap/rgbd_cameras: 2
 * /rtabmap/rtabmap/subscribe_depth: False
 * /rtabmap/rtabmap/subscribe_rgbd: True
 * /rtabmap/rtabmap/wait_for_transform: True
 * /rtabmap/rtabmapviz/frame_id: base_link
 * /rtabmap/rtabmapviz/rgbd_cameras: 2
 * /rtabmap/rtabmapviz/subscribe_depth: False
 * /rtabmap/rtabmapviz/subscribe_odom_info: True
 * /rtabmap/rtabmapviz/subscribe_rgbd: True
 * /rtabmap/rtabmapviz/wait_for_transform: True
 * /use_sim_time: True

NODES
  /camera2/
    rgbd_sync (nodelet/nodelet)
  /camera1/
    rgbd_sync (nodelet/nodelet)
  /rtabmap/
    rgbd_odometry (rtabmap_ros/rgbd_odometry)
    rtabmap (rtabmap_ros/rtabmap)
    rtabmapviz (rtabmap_ros/rtabmapviz)
  /
    base_to_camera1_tf (tf/static_transform_publisher)
    base_to_camera2_tf (tf/static_transform_publisher)
    decompress_image_1 (image_transport/republish)
    decompress_image_2 (image_transport/republish)

ROS_MASTER_URI=http://localhost:11311

process[base_to_camera1_tf-1]: started with pid [10953]
process[base_to_camera2_tf-2]: started with pid [10954]
process[camera1/rgbd_sync-3]: started with pid [10956]
process[camera2/rgbd_sync-4]: started with pid [10966]
process[rtabmap/rgbd_odometry-5]: started with pid [10981]
process[rtabmap/rtabmap-6]: started with pid [10999]
process[rtabmap/rtabmapviz-7]: started with pid [11014]
process[decompress_image_1-8]: started with pid [11018]
process[decompress_image_2-9]: started with pid [11027]
[ INFO] [1531327711.913865351]: Starting node...
[ INFO] [1531327711.933639783]: Initializing nodelet with 8 worker threads.
[ INFO] [1531327711.976664274]: Initializing nodelet with 8 worker threads.
[ INFO] [1531327712.049504600]: Starting node...
[ INFO] [1531327712.144972007]: rtabmapviz: Using configuration from "/home/e4e/catkin_ws/install_isolated/share/rtabmap_ros/launch/config/rgbd_gui.ini"
[ INFO] [1531327712.368762353]: Setting odometry parameter "Odom/FillInfoData"="true"
[ INFO] [1531327712.391232488]: Setting odometry parameter "Odom/Strategy"="0"
[ INFO] [1531327712.398174622]: Setting odometry parameter "OdomF2M/MaxSize"="1000"
[ INFO] [1531327712.509171627]: Setting odometry parameter "Vis/CorNNType"="3"
[ INFO] [1531327712.513119043]: Setting odometry parameter "Vis/EstimationType"="0"
[ INFO] [1531327712.513587384]: Setting odometry parameter "Vis/FeatureType"="6"
[ INFO] [1531327712.515664469]: Setting odometry parameter "Vis/InlierDistance"="0.02"
[ INFO] [1531327712.517593978]: Setting odometry parameter "Vis/MaxDepth"="4.0"
[ INFO] [1531327712.525338920]: Setting odometry parameter "Vis/MinInliers"="20"
[ INFO] [1531327712.594649456]: 
/rtabmap/rgbd_odometry subscribed to (approx sync):
   /camera1/rgbd_image,
   /camera2/rgbd_image
[ INFO] [1531327713.177297603]: Reading parameters from the ROS server...
[ INFO] [1531327713.292348660]: Parameters read = 0
[ INFO] [1531327713.446817429]: /rtabmap/rtabmapviz: queue_size    = 10
[ INFO] [1531327713.446842358]: /rtabmap/rtabmapviz: rgbd_cameras = 2
[ INFO] [1531327713.446865886]: /rtabmap/rtabmapviz: approx_sync   = true
[ INFO] [1531327713.446886440]: Setup rgbd2 callback
[ INFO] [1531327713.460829325]: 
/rtabmap/rtabmapviz subscribed to (approx sync):
   /rtabmap/odom,
   /camera1/rgbd_image,
   /camera2/rgbd_image,
   /rtabmap/odom_info
[ INFO] [1531327713.460894812]: rtabmapviz started.
[ INFO] [1531327718.737811770, 1526756960.978493787]: /rtabmap/rtabmap(maps): map_filter_radius          = 0.000000
[ INFO] [1531327718.737921089, 1526756960.978493787]: /rtabmap/rtabmap(maps): map_filter_angle           = 30.000000
[ INFO] [1531327718.737968321, 1526756960.978493787]: /rtabmap/rtabmap(maps): map_cleanup                = true
[ INFO] [1531327718.738003175, 1526756960.978493787]: /rtabmap/rtabmap(maps): map_negative_poses_ignored = false
[ INFO] [1531327718.738040003, 1526756960.978493787]: /rtabmap/rtabmap(maps): map_negative_scan_ray_tracing = false
[ INFO] [1531327718.738074249, 1526756960.978493787]: /rtabmap/rtabmap(maps): cloud_output_voxelized     = true
[ INFO] [1531327718.738104480, 1526756960.978493787]: /rtabmap/rtabmap(maps): cloud_subtract_filtering   = false
[ INFO] [1531327718.738139635, 1526756960.978493787]: /rtabmap/rtabmap(maps): cloud_subtract_filtering_min_neighbors = 2
[ INFO] [1531327718.741870312, 1526756960.978493787]: /rtabmap/rtabmap(maps): octomap_tree_depth         = 16
[ INFO] [1531327718.741938472, 1526756960.978493787]: /rtabmap/rtabmap(maps): octomap_occupancy_thr      = 0.500000
[ INFO] [1531327718.784606164, 1526756960.979378913]: rtabmap: frame_id      = base_link
[ INFO] [1531327718.784635129, 1526756960.979378913]: rtabmap: map_frame_id  = map
[ INFO] [1531327718.784655828, 1526756960.979378913]: rtabmap: tf_delay      = 0.050000
[ INFO] [1531327718.784669984, 1526756960.979378913]: rtabmap: tf_tolerance  = 0.100000
[ INFO] [1531327718.784685706, 1526756960.979378913]: rtabmap: odom_sensor_sync   = false
[ INFO] [1531327718.857191177, 1526756961.059860926]: Setting RTAB-Map parameter "Grid/FromDepth"="false"
[ INFO] [1531327719.222771358, 1526756961.422223660]: Setting RTAB-Map parameter "Vis/EstimationType"="0"
[ INFO] [1531327719.225959277, 1526756961.422223660]: Setting RTAB-Map parameter "Vis/InlierDistance"="0.02"
[ INFO] [1531327719.231942591, 1526756961.432277476]: Setting RTAB-Map parameter "Vis/MinInliers"="10"
[ INFO] [1531327719.448483508, 1526756961.643394772]: RTAB-Map detection rate = 1.000000 Hz
[ INFO] [1531327719.449392034, 1526756961.653449071]: rtabmap: Deleted database "/home/e4e/.ros/rtabmap.db" (--delete_db_on_start or -d are set).
[ INFO] [1531327719.449411989, 1526756961.653449071]: rtabmap: Using database from "/home/e4e/.ros/rtabmap.db".
[ INFO] [1531327719.581750322, 1526756961.784405732]: rtabmap: Database version = "0.13.2".
[ INFO] [1531327719.664911139, 1526756961.865046869]: /rtabmap/rtabmap: queue_size    = 10
[ INFO] [1531327719.665015126, 1526756961.865046869]: /rtabmap/rtabmap: rgbd_cameras = 2
[ INFO] [1531327719.665059827, 1526756961.865046869]: /rtabmap/rtabmap: approx_sync   = true
[ INFO] [1531327719.665202066, 1526756961.865046869]: Setup rgbd2 callback
[ INFO] [1531327719.713316682, 1526756961.915413318]: 
/rtabmap/rtabmap subscribed to (approx sync):
   /rtabmap/odom,
   /camera1/rgbd_image,
   /camera2/rgbd_image
[ INFO] [1531327719.730040707, 1526756961.925473936]: rtabmap 0.13.2 started...
[ WARN] [1531327720.852762107, 1526756963.056739906]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756962.891669) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100998 timeout was 0.1."
[ WARN] [1531327720.985180335, 1526756963.188345356]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756963.057694) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.101341 timeout was 0.1."
[ WARN] [1531327721.086023580, 1526756963.289210496]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756963.126735) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100865 timeout was 0.1."
[ WARN] [1531327721.186873612, 1526756963.390156011]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756963.157667) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100946 timeout was 0.1."
[ WARN] [1531327721.287650311, 1526756963.491320562]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756963.325806) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.101165 timeout was 0.1."
[ WARN] [1531327721.389466850, 1526756963.592882847]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756963.457671) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.101562 timeout was 0.1."
[ WARN] [1531327721.521208013, 1526756963.723997210]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756963.557668) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.10086 timeout was 0.1."
[ WARN] [1531327721.621130791, 1526756963.824772430]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756963.591668) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100775 timeout was 0.1."
[ WARN] [1531327721.723056598, 1526756963.926772576]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756963.791678) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.102 timeout was 0.1."
[ WARN] [1531327721.854567293, 1526756964.058546934]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756963.891824) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.101495 timeout was 0.1."
[ WARN] [1531327721.956007764, 1526756964.159403910]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756964.025674) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100857 timeout was 0.1."
[ WARN] [1531327722.087055870, 1526756964.290584883]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756964.125705) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100871 timeout was 0.1."
[ WARN] [1531327722.187604572, 1526756964.391542301]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756964.225711) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100957 timeout was 0.1."
[ WARN] [1531327722.592210035, 1526756964.795643865]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756964.291667) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100993 timeout was 0.1."
[ WARN] [1531327722.693321999, 1526756964.896456602]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756964.660103) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100813 timeout was 0.1."
[ WARN] [1531327722.794324513, 1526756964.997308730]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756964.757927) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100852 timeout was 0.1."
[ WARN] [1531327722.914521247, 1526756965.118399899]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756964.958114) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100846 timeout was 0.1."
[ WARN] [1531327723.016133456, 1526756965.219279842]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756965.093834) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.10088 timeout was 0.1."
[ WARN] [1531327723.116757310, 1526756965.320114491]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756965.194328) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100835 timeout was 0.1."
[ WARN] [1531327723.217302686, 1526756965.421239076]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756965.259717) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.101125 timeout was 0.1."
[ WARN] [1531327723.318489520, 1526756965.522150723]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756965.397970) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100912 timeout was 0.1."
[ WARN] [1531327723.430105954, 1526756965.633320597]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756965.491966) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.101072 timeout was 0.1."
[ WARN] [1531327723.530804273, 1526756965.734169046]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756965.591916) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100848 timeout was 0.1."
[ WARN] [1531327723.652079260, 1526756965.855239656]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756965.725922) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100891 timeout was 0.1."
[ WARN] [1531327723.783272305, 1526756965.986421157]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756965.826246) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100883 timeout was 0.1."
[ WARN] [1531327723.783361955, 1526756965.986421157]: /rtabmap/rtabmapviz: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
/rtabmap/rtabmapviz subscribed to (approx sync):
   /rtabmap/odom,
   /camera1/rgbd_image,
   /camera2/rgbd_image,
   /rtabmap/odom_info
[ WARN] [1531327723.884350161, 1526756966.087308356]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756965.925913) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100887 timeout was 0.1."
[ WARN] [1531327723.984288366, 1526756966.188195980]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756966.035061) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100888 timeout was 0.1."
[ WARN] [1531327724.085898239, 1526756966.289038357]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756966.159911) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100842 timeout was 0.1."
[ WARN] [1531327724.196223520, 1526756966.399831183]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756966.259911) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100725 timeout was 0.1."
[ WARN] [1531327724.317868807, 1526756966.520961309]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756966.391914) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100922 timeout was 0.1."
[ WARN] [1531327724.418599678, 1526756966.621788123]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756966.491946) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100827 timeout was 0.1."
[ WARN] [1531327724.519186661, 1526756966.722708158]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756966.591908) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.10092 timeout was 0.1."
[ WARN] [1531327724.620532072, 1526756966.823887982]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756966.691913) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.10118 timeout was 0.1."
[ WARN] [1531327724.721024723, 1526756966.924824337]: /rtabmap/rtabmap: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
/rtabmap/rtabmap subscribed to (approx sync):
   /rtabmap/odom,
   /camera1/rgbd_image,
[ WARN] [1531327724.721028239, 1526756966.924824337]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756966.792272) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100936 timeout was 0.1."
   /camera2/rgbd_image
[ WARN] [1531327724.822213536, 1526756967.025693101]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756966.892008) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100869 timeout was 0.1."
[ WARN] [1531327724.932850553, 1526756967.136606740]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756966.992579) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100848 timeout was 0.1."
[ WARN] [1531327725.034156441, 1526756967.237455604]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756967.092714) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100849 timeout was 0.1."
[ WARN] [1531327725.155098766, 1526756967.358800119]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756967.228996) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.101151 timeout was 0.1."
[ WARN] [1531327725.256280047, 1526756967.459864567]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756967.325903) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.101064 timeout was 0.1."
[ WARN] [1531327725.357578480, 1526756967.560793143]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756967.426281) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.100929 timeout was 0.1."
[ WARN] [1531327725.458884494, 1526756967.661851430]: odometry: Could not get transform from base_link to camera1_rgb_optical_frame (stamp=1526756967.527545) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: source_frame camera1_rgb_optical_frame does not exist.. canTransform returned after 0.101058 timeout was 0.1."
^C[decompress_image_2-9] killing on exit
[decompress_image_1-8] killing on exit
[rtabmap/rtabmapviz-7] killing on exit
[rtabmap/rtabmap-6] killing on exit
[rtabmap/rgbd_odometry-5] killing on exit
[camera2/rgbd_sync-4] killing on exit
[camera1/rgbd_sync-3] killing on exit
[base_to_camera2_tf-2] killing on exit
[base_to_camera1_tf-1] killing on exit
[ INFO] [1531327725.535212394, 1526756967.732628221]: rtabmapviz: ctrl-c catched! Exiting Qt app...
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
rtabmap: Saving database/long-term memory... (located at /home/e4e/.ros/rtabmap.db)
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by matlabbe** [comment]
It looks like the TF for the cameras are not there. For example, you may try to launch [kinect_frames.launch](https://github.com/ros-drivers/rgbd_launch/blob/indigo-devel/launch/kinect_frames.launch) for each camera.

**Comment by frushton** [comment]
Thank you for responding. It turns out the problem was that I was suppressing both /tf and /tf_static from the bag file. I suppressed only /tf, and now the playback is working as the new /tf is being published, and the old /tf_static is gving the transforms for the cameras' rgb and depth.
