### ISSUE TITLE
ZED ros wrapper - publish map

### ISSUE THREAD

**Issue by MarcoWerth** [introlab/rtabmap_ros#278]
Hi,
found this section in tutorials of rtabmap: (http://wiki.ros.org/rtabmap_ros/Tutorials/HandHeldMapping)

> Issue when using zed odometry approach (B) with latest zed_ros_wrapper package: we should comment this line to avoid zed wrapper to publish /map -> /odom frame, which is also published by rtabmap node.

Zed_ros_wrapper provides a (new?) parameter publish_map_tf. I set this to false and now zed and rtabmap map publishing issue seems to be sovled without commenting the zed source code.

BR
Marco

**Comment by matlabbe** [comment]
Indeed, this is now fixed by https://github.com/stereolabs/zed-ros-wrapper/pull/282

I updated the [tutorial](http://wiki.ros.org/rtabmap_ros/Tutorials/HandHeldMapping), we just need to add  `publish_map_tf:=false`.

cheers,
Mathieu
