### ISSUE TITLE
CV_8UC1 Format

### ISSUE THREAD

**Issue by abylikhsanov** [introlab/rtabmap_ros#296]
My camera has a fisheye CV format of CV_8UC1 and rtabmap complains that the format is incorrect. Shouldn't it be accepting any format as OpenCV matrix is being used?

**Comment by matlabbe** [comment]
CV_8UC1 should be supported. What is exactly the error message?

**Comment by abylikhsanov** [comment]
I am sorry, for some reason, I cannot reproduce this issue and for some reason, it disappeared.
