### ISSUE TITLE
rtabmap does not recieve data

### ISSUE THREAD

**Issue by kylxyz** [introlab/rtabmap_ros#321]
Hi Matlabbe, 

I am very new on robotics,
I am using Velodyne Puck + Zed mini  to create rtabmap.db; my ros version is melodic, rtabmap is 0.19.4. 

The problem that I am facing is  
`[ WARN] [1561525074.796461195]: /rtabmap/rtabmap: Did not receive data since 5 seconds! `  and  `/rtabmap/point_cloud_assembler: Did not receive data since 5 seconds!`

here is my [tf tree and topic graph](https://drive.google.com/open?id=11yzqvWyOPGnlrtKFaA-cVIrb_MsrE3KC)

and my [screen print of runtime](https://drive.google.com/open?id=1jbXiDFORdCtOUS6R1IEgE8vdv4B70ddD)

[topic_hz_echo](https://drive.google.com/open?id=1QXPr_tW0o8VZcA90xeI7k9P0mSPgbvHW)

and the [launch file](https://drive.google.com/open?id=1RX7vJnBmGvLKHB0LUg2ZWptaPyCaXUu5)

Would you please take a look and give me some hists?

cheers

**Comment by matlabbe** [comment]
The warning on point_cloud_assembler is telling that it is subscribed to `/rtabmap/odom` (which is not puclished), not  `/mobile_base/odom`. In your launch, I would uncomment the second line here (removing the first one):
```xml
<remap from="odom"            to="odom"/>
<!--<remap from="odom"            to="$(arg odom_topic)"/>-->
```

**Comment by kylxyz** [comment]
Hi Matlabbe, 

thank you for the reply I tried with your way, it works!
