### ISSUE TITLE
/usr/bin/ld: cannot find -lrealsense2

### ISSUE THREAD

**Issue by ankitgc1** [introlab/rtabmap_ros#326]
error in make

![Screenshot from 2019-07-17 21-29-53](https://user-images.githubusercontent.com/35380717/61391356-25ade100-a8da-11e9-9389-0f740f21579e.png)

**Comment by matlabbe** [comment]
Where realsense2 library is installed?

Example:
```bash
$ ldd rtabmap | grep realsense2
	librealsense2.so.2.22 => /usr/local/lib/librealsense2.so.2.22 (0x00007f971a791000)
```

**Comment by matlabbe** [comment]
Should be fixed now with the commit above. The bug appeared only with realsense2 binaries, from source it was ok.

**Comment by themancalledjakob** [comment]
should you encounter this issue and you are on linux, look for broken symlinks.
`ls -la /usr/lib/x86_64-linux-gnu/`
the broken link would be for example `/usr/lib/x86_64-linux-gnu/librealsense2.so -> librealsense2.so.2.33` in red
just remove the symlink librealsense2.so like this: `sudo rm /usr/lib/x86_64-linux-gnu/librealsense2.so`
then:
`sudo ln -s /usr/lib/x86_64-linux-gnu/librealsense2.so.2.32 /usr/lib/x86_64-linux-gnu/librealsense2.so`

**Comment by Harimus** [comment]
@themancalledjakob  
This solved it for me, thanks! Do you know why this broken symlinks could've happened? on my PC the only thing I can think of is different cmake version.

**Comment by themancalledjakob** [comment]
@Harimus 
My guess is that a realsense developer pushed a repo with a wrong symlink by accident ;-)
This stuff easily happens if you link to a not-yet-published version (in this case `librealsense2.so.2.33`) on your disk, and therefore don't notice that it's broken for everyone else. This is only an assumption though, I actually have no idea.
