### ISSUE TITLE
OpenCV 4.1.0

### ISSUE THREAD

**Issue by abylikhsanov** [introlab/rtabmap_ros#330]
Hi,
Is it possible to compile RTABmap using OpenCV 4.1.0? When I ran cmake, it went without a problem:
`*With OpenCV 4 xfeatures2d module (SIFT/SURF/BRIEF/FREAK) = YES (License: Non commercial)`

But then the compilation gives an error:
```
 error: ‘CV_PCA_DATA_AS_ROW’ was not declared in this scope
     cv::PCA pca_analysis(pcaData, cv::Mat(), CV_PCA_DATA_AS_ROW);
```
So is there some trick that I need to use before the compilation or do I need to rewrite everything from OpenCV 3 to 4?

**Comment by matlabbe** [comment]
Thx for reporting, this was a recent new feature added that was not tested with latest OpenCV version. Normally All OpenCV versions 2-3-4 should build with the master branch.
