### ISSUE TITLE
rtab-map pose covariance

### ISSUE THREAD

**Issue by JoeyLeeNPU** [introlab/rtabmap_ros#350]
Hi~

We want to use rtab-map as a method for our drone to obtain external state information. 
But in PX4 board, its EKF2 can perform better if we input an pose estimation with the covariance.
Hence, I want to know if rtab-map can compute a pose with covariance. If can, could u tell me how to find this message in ROS package.

Thanks,
Joey

**Comment by matlabbe** [comment]
Do you mean odometry pose or localization pose? For odometry, rtabmap's odometry publishes the odometry topic (`/rtabmap/odom`) containing a covariance. On localization only, rtabmap publishes `/rtabmap/localization_pose` topic with a covariance too.

**Comment by JoeyLeeNPU** [comment]
Thanks for your help
I have found that Odom and localization mode both have the covariance, but my Odom is an external Odom (vio) and I use rtab for mapping mode rather than localization only.
So any suggestions?

Joey

**Comment by matlabbe** [comment]
`localization_pose` is published only on loop closures in mapping mode (when `map->odom` frame changes). In those cases, the covariance represents the marginal (g2o, gtsam) after graph optimization. It won't be published if no loop closures happen.

**Comment by JoeyLeeNPU** [comment]
So could I use localization_pose in mapping mode for my px4 external pose estimation? 
That is, when no loop closures happen it only pub a pose, while happened,  a pose with covariance Is published?

**Comment by matlabbe** [comment]
No pose msgs (with or without covariance) are published when there are no loop closures. 

The problem is that on loop closures, the robot may jump many meters (if the loop is large). I don't think you should feed the map correction to px4 controller. I would feed only your vio messages to px4's ekf2. On rtabmap side, I would set `RGBD/OptimizeFromGraphEnd` to true, so that the map is transformed instead of jumping the pose of the robot.

cheers,
Mathieu

**Comment by JoeyLeeNPU** [comment]
I have a try that feed only vio messages to px4's ekf2, and it do better for flights, but I want to use a more accurate position information for UAV to localize other objects (some markers), hence, I want to try the rtab's pose. Some days ago, I use the /tf to listen the pose topic and send it to ekf2, it can also do better for flights. But when I learn more about px4's ekf2, I notice that a pose with covariance is helpful for state estimation. 
So, if I want to use the **rtab's pose** optimized by loop closures detection, **which topic should I choose for px4 to subscribe**? Because I see that you say "localization_pose" will not publish pose when there are no loop closures.  Or I only can use /tf to obtain the transformation (pose without covariance)?

Thanks so much!  hah^_^
Joey

**Comment by matlabbe** [comment]
If you want the pose to be continuously published to EKF2, you would have to use TF without covariance.

**Comment by rakshith95** [comment]
@matlabbe does rtabmap update the tf  only when there's loop closure as well?

**Comment by matlabbe** [comment]
Map->odom tf is published at 20 Hz, but its transform would change only on loop closures. For example, if you start a new map, map->odom will be Identity until a loop closure is detected.

**Comment by rakshith95** [comment]
I see, thank you!
