### ISSUE TITLE
Using folder with RGB-D images as source on Linux standalone version of RTABMap

### ISSUE THREAD

**Issue by oafolabi** [introlab/rtabmap_ros#351]
Hi, 

I have a dataset of RGB-D images and I'm trying to estimate the trajectory using RTABMap. I am using the standalone version on Ubuntu 18.04 (same as the ros version but just running $rtabmap). 
I seem to be unable to set the RGB-D images as a source for RTABMap, the option is greyed out for me as shown below. This seems to work okay on my mac version, but not the Linux version. What can I do?

![20190921_235527](https://user-images.githubusercontent.com/40698973/65383520-a36fdd80-dccb-11e9-83f9-3373f4257e13.jpg)

Also is it possible to get the odometry at ~30Hz?

Thanks

**Comment by matlabbe** [comment]
It was a bug, I fixed in the commit above. Images type should be always available.

If you want to limit odometry at 30 Hz, you can set the camera input rate to 30 Hz. Note that if your computer cannot process the frames under 33 ms, the odometry frame rate may be lower.
