### ISSUE TITLE
Visualization with RVIZ giving different result when launched after some delay

### ISSUE THREAD

**Issue by ghost-60** [introlab/rtabmap_ros#360]
After running rtabmap.launch, it shows different result when I try to run rviz immediately versus when I run rviz after a few seconds. I think the issue is with synchronization when the map is loaded and when the localization occurs. 
Video for reference. [https://youtu.be/TJKAMhG1azo](url)
Here is the screenshot of what I am getting when launching after few seconds(10 seconds):
![Screenshot from 2019-10-21 14-12-20](https://user-images.githubusercontent.com/21110175/67231622-a61a3b80-f40d-11e9-8225-c94be29a9d61.png)
red line is from zed_node/odom

If I run rviz simultaneously with the launch file, it works fine.

**Comment by matlabbe** [comment]
Are you using a rosbag? We cannot see the terminal with rtabmap at the same time, but it seems rtabmap didn't not localize on its loaded map. rviz should not have any impact on localization.
