### ISSUE TITLE
curved floor in mapCloud

### ISSUE THREAD

**Issue by jungladicitta** [introlab/rtabmap_ros#361]
I have mobile robot with 1.5 meters mast. I have located Intel Realsense d435 camera near to the top of the mast and oriented to the floor.

I am visualizing mapCloud in rviz, and I see that vertical wall is vertical but floor is curved.
![0PULbfomgvE](https://user-images.githubusercontent.com/45363623/67548393-e6d6c500-f72b-11e9-835a-a3c1d13c78dd.jpg)
https://yadi.sk/i/gA5xxj3PJ8y-Uw

Why is this happening? What can I do to correct it?

**Comment by jungladicitta** [comment]
@matlabbe do you know why is this happening?

**Comment by matlabbe** [comment]
see https://answers.ros.org/question/336080/rtabmap-angled-camera/
