### ISSUE TITLE
IR+Depth only (no RGB-D) with rtabmap_ros?

### ISSUE THREAD

**Issue by toddsampson** [introlab/rtabmap_ros#37]
I am trying to get rtabmap_ros working with the Structure Sensor.  Unfortunately the Structure Sensor only has IR+Depth output -- no RGB-D.  I saw on the rtabmap release notes (https://github.com/introlab/rtabmap/releases) that it can now use an IR+Depth for the Kinect One.  Is there a way to configure rtabmap_ros to use just IR?

**Comment by matlabbe** [comment]
If the Structure Sensor is based on Structured light (like Kinect for Xbox 360), RTAB-Map cannot use the IR image as it contains the IR pattern. Example:
![](http://wiki.ros.org/openni_launch/Tutorials/IntrinsicCalibration?action=AttachFile&do=get&target=ir.jpg)
Kinect for Xbox One uses time of light (TOF) technology, so the IR image is not disturbed by any semi-random dotted pattern and RTAB-Map can do visual odometry with it.

On the iPad, they seem to have calibrated the IR camera with iPad's RGB camera: http://forums.structure.io/t/announcing-calibrator/2037

Under ROS, if you want to calibrate an IR camera with an external RGB camera, you could look at this tutorial: http://wiki.ros.org/openni_launch/Tutorials/ExtrinsicCalibrationExternal
![](http://wiki.ros.org/openni_launch/Tutorials/ExtrinsicCalibrationExternal?action=AttachFile&do=get&target=KinectProsilicaLabeled.jpg)

cheers

**Comment by toddsampson** [comment]
Great stuff... Thanks!

**Comment by arogowiec** [comment]
Hi there! Can anyone tell me how to switch to IR+Depth mode?

**Comment by matlabbe** [comment]
It is only available for Kinect v2:

![screenshot from 2017-03-31 18-25-48](https://cloud.githubusercontent.com/assets/2319645/24571486/851f441a-163f-11e7-9906-d9835980e70a.png)

![screenshot from 2017-03-31 18-25-23](https://cloud.githubusercontent.com/assets/2319645/24571491/89fca9f0-163f-11e7-9474-c231e76cd06b.png)

**Comment by nufanDK** [comment]
@toddsampson Did you get it working with a tethered Structure Sensor with no RGB? I'm trying the same just not on ros.. :-)
