### ISSUE TITLE
rtabmap pointcloud for same device looks different on 2 different computers

### ISSUE THREAD

**Issue by lingfei93** [introlab/rtabmap_ros#371]
Hello,

I am using a Kinect DK to map my surroundings. I am using rtabmap_ros to create a 3D map of the surrounding. On one computer, rtabmap_ros seems to work very well and is able to create a decent 3D and 2D map of the surrounding. The normal one looks like this.

3D map:
![rtab-normal](https://user-images.githubusercontent.com/22360449/69603240-0592e900-1055-11ea-81fe-57a6b3abc4df.png)
2D map:
![map](https://user-images.githubusercontent.com/22360449/69603373-599dcd80-1055-11ea-8c26-3e20a66067b9.png)
**On my laptop!**
**Which is all fine, until I move the computing to my laptop, then i get really weird yellow spots in the 3D map that seems like noise, but I'm having issues filtering it. The weird one looks like this:**

![laptop](https://user-images.githubusercontent.com/22360449/69603811-a2a25180-1056-11ea-9646-c2ecc110a192.jpeg)
![laptop2](https://user-images.githubusercontent.com/22360449/69604182-a84c6700-1057-11ea-824c-870472e1e891.png)

There seems to be a lot of yellow cloud noise that seems to be around the origin of the camera. This does not seem to affect the 3D map, which turns out to be fine, but it really affects my 2D map, as seen here
2D Map: 
![laptop](https://user-images.githubusercontent.com/22360449/69603941-fdd44400-1056-11ea-945d-569e984834d5.png)
I'm really curious as to what the issue is, as I am subscribing to rtabmap/rtabmap/proj_map, I thought I'd post the issue here and check. I've checked the native Kinect DK viewer and the sensor data is fine.

I'd appreciate any help and please do ping me if I have left out some information.

**Comment by matlabbe** [comment]
Can you record a rosbag wit kinect data?

**Comment by lingfei93** [comment]
[bag_files.zip](https://github.com/introlab/rtabmap_ros/files/3904793/bag_files.zip)
I've uploaded bag files. Only have the scan data, as the files are quite big in general. Hope that's okay.

**Comment by matlabbe** [comment]
If the bags are too large, it would be better to share the databases created from rtabmap (default `~/.ros/rtabmap.db`). I cannot do much with only scan_map topic.

**Comment by lingfei93** [comment]
Hi, i've uploaded them to a google drive link, but the topics only have around ~5 seconds of data. hope thats okay.

Thank you so much for your time.

https://drive.google.com/open?id=14ISuYr4AJ_pJ26mxeFErqfvJxmHMRtIz

**Comment by lingfei93** [comment]
Hi,

Sorry, on closer inspection, I realized that the depth image that I was looking
