### ISSUE TITLE
 Rtabmap ROS not working on AGX Xavier 

### ISSUE THREAD

**Issue by ahmedabuelela** [introlab/rtabmap_ros#395]
Hello,

I am trying to install Rtabmap with ROS melodic on Xavier AGX but there is no map generated, the 3D map tab in both the Rtabmap and the database viewer freezes and not responding.
On normal conditions it suppose to be a black screen but in my case it is as shown in the picture.
I have tried removing rtabmap and building it from source but still no luck.
![987a1d0398ff8ee942be4be0396dd85f5ed5f26d](https://user-images.githubusercontent.com/59337027/77527763-6f04f600-6e95-11ea-9310-437265933da2.jpeg)

**Comment by matlabbe** [comment]
The same problem happens on nano and tx2, see https://github.com/introlab/rtabmap/issues/427#issuecomment-516914817
