### ISSUE TITLE
Change value of Cloud max depth 

### ISSUE THREAD

**Issue by borcherd** [introlab/rtabmap_ros#396]
I am working on a project where I do a SLAM with rtabmap in an outdoor environment simulated in Gazebo, and navigate autonomously in that SLAM map. For the navigation I need an octomap. I know that rtabmap publishes a octomap to rtabmap/octomap_full but it looks like the range of the sensor isn't big enough to map almost anything but the street. I've tried changing the param Grid/RangeMax but that changes nothing. I have a vlp16 lidar and a realsense depth camera on my robot, tried with both and still no difference.

![image](https://user-images.githubusercontent.com/32452429/77537850-10447a00-6e9f-11ea-96b7-55ae0a150dd5.png)
Here you can see how far the depth camera sees, and how far the octomap goes.

**Comment by matlabbe** [comment]
`Grid/RangeMax` should have done the trick. Can you share a database?

**Comment by borcherd** [comment]
> `Grid/RangeMax` should have done the trick. Can you share a database?

Yes, in combination with changing the depth decimation it worked.

**Comment by iportolesrb** [comment]
> > `Grid/RangeMax` should have done the trick. Can you share a database?
> 
> Yes, in combination with changing the depth decimation it worked.

What did you do with the decimation to make it work? I have the same issue.

**Comment by matlabbe** [comment]
Increasing `Grid/DepthDecimation` would generate less cells, if it is a range problem, increase `Grid/RangeMax`.

**Comment by iportolesrb** [comment]
> Increasing `Grid/DepthDecimation` would generate less cells, if it is a range problem, increase `Grid/RangeMax`.

I tried to increase `Grid/RangeMax` but nothing changes.

**Comment by matlabbe** [comment]
Which topic are you looking at exactly?

**Comment by iportolesrb** [comment]
The mapData topic.

**Comment by matlabbe** [comment]
For mapData, if you visualize with MapCloud plugin in rviz, there is an [Cloud max depth (m)](http://wiki.ros.org/rtabmap_ros#Map_Cloud_Display) option set to 4 meters by default. In rtabmapviz, that option is under Preferences->3D Rendering panel, under Map column. rtabmap-export has also a max depth of 4 meters by default, it can be changed like this (to disable it):
```
rtabmap-export --max_range 0 rtabmap.db
```

**Comment by iportolesrb** [comment]
Oh, ok, that solved it thank you.
