### ISSUE TITLE
Turning off rgbd_odometry INFO logging

### ISSUE THREAD

**Issue by tianshiz** [introlab/rtabmap_ros#409]
I tried the rosservice for /rtabmap/log_warning but that didn't seem to stop the constant INFO logging coming out from the rgbd_odom node.

Is there's something else I need to set?

**Comment by matlabbe** [comment]
Those logs are from ROS_INFO, try:
```bash
$ rosservice call /rtabmap/rgbd_odometry/set_logger_level ros.rtabmap_ros warn

// To set ROS loggers on a specific node:
$ rosservice call /rtabmap/rgbd_odometry/get_loggers
```
The `/rtabmap/log_warning` service is used for UINFO, the log system used in rtabmap library (not ROS).

It is also possible to not set `output="screen"` in launch file to avoid printing debug to console, but would be shown in rqt_console.
