### ISSUE TITLE
is octomap_ground the same as the output from rtabmap_ros/obstacles_detection?

### ISSUE THREAD

**Issue by tianshiz** [introlab/rtabmap_ros#410]
I'm doing navigation with move_base and the local planner requires pointcloud with only the obstacles. I saw in the tutorials that the obstacles_detection nodelet was being used to segment the obstacles from the ground.
However, I'm also using octomaps later for manipulation planning, which already gives me octomap_ground. Can I just feed octomap_ground to the local planner instead?

**Comment by matlabbe** [comment]
No, the cloud sent to local planner should be timely recent and in sensor frame at high frame rate if possible. If the cloud is created from a camera, you can use `rtabmap_ros/point_cloud_xyz` to decimate the depth image and/or voxelize the point cloud before the segmentation to be faster.

`octomap_ground` is published at lower frame rate, and it grows as the map grows, which would make it inefficient for updating the local costmap. Also, as `octomap_ground` is in map frame, there is then no sensor reference for ray tracing in the local costmap, so some obstacles may be wrongly cleared.
