### ISSUE TITLE
Can not work with ICP 2D lidar in newest version

### ISSUE THREAD

**Issue by NamDinhRobotics** [introlab/rtabmap_ros#412]
Hello Mathieu,
My name Nam Dinh, 
Currently, I am working with 2D Lidar slam fusion, then find a perfect SLAM is Rtabmap.
When I tried with :
roslaunch rtabmap_ros demo_hector_mapping.launch hector:=false
in Rtabmap version 0.19.3 in Ros Kinetic, it's success and works well.
But, when updating the new version 0.19.7 or 0.20.0, in Rviz which can not show the same results( without /odom in Fixed Frame in rviz)
Would you help me and give suggestions for that?
Best regards,
Nam
![Screenshot from 2020-05-04 15-30-33](https://user-images.githubusercontent.com/30413547/80941009-440aac00-8e1c-11ea-9fc8-fd15acdb718b.png)

**Comment by matlabbe** [comment]
There were 2 bugs at the same time when we added intensity to converted scans and the complexity check by default. The commits above should fix the problem. Thnaks for reporting!

**Comment by NamDinhRobotics** [comment]
Great! Thank you so much.
