### ISSUE TITLE
Error when starting map rtabmap_ros indigo.

### ISSUE THREAD

**Issue by long-senpai** [introlab/rtabmap_ros#416]
hello matlabbe, im working with rtabmap in ros indigo with camera asus xtion + openni2. im following all step build for ros indigo and it's work well. but when i start run "roslaunch rtabmap_ros rtabmap.launch rtabmap_args:="--delete_db_on_start""
then it showing the error "Unknown substitution command [eval scan_cloud_assembling]. Valid commands are ['find', 'env', 'optenv', 'anon', 'arg']
The traceback for the exception was written to the log file"
->  i think is's problem in launch file, i can't found any solution for this problem. help me!! 

p/s: if i run rtabmap standalone without ros version, it's work properly

**Comment by matlabbe** [comment]
You are still under Indigo! ;)

On[ April 19 2020](https://github.com/introlab/rtabmap_ros/commit/dff012718e9d2f94d1f4621e59b262bd4e6e2cb8#diff-97f6486ac8f01aac761cafbe871c2f5b), for convenience for a new option called `scan_cloud_assembling`, I had to update `rtabmap.launch` in a way that had broken compatibility with ROS Indigo. On ROS indigo, we cannot use `eval` keyword in the launch files. You would have to change those lines:
https://github.com/introlab/rtabmap_ros/blob/0c4779c19e25f7a2967c2caad5ad1ffe8c04ef74/launch/rtabmap.launch#L322-L324
to original:
```xml
<remap     if="$(arg scan_cloud_filtered)" from="scan_cloud" to="odom_filtered_input_scan"/>
<remap unless="$(arg scan_cloud_filtered)" from="scan_cloud" to="$(arg scan_cloud_topic)"/>
```

cheers,
Mathieu
