### ISSUE TITLE
How to save the post-processed point-cloud in the rtabmap-ros?

### ISSUE THREAD

**Issue by armanhamzehlou** [introlab/rtabmap_ros#428]

**Comment by matlabbe** [comment]
Do you means `cloud_map` topic? See [pcl_ros/pointcloud_to_pcd](http://wiki.ros.org/pcl_ros#pointcloud_to_pcd).

**Comment by armanhamzehlou** [comment]
> Do you means `cloud_map` topic? See [pcl_ros/pointcloud_to_pcd](http://wiki.ros.org/pcl_ros#pointcloud_to_pcd).

When you process your point-cloud through Menu -> Tools -> Post-Processing, How do you save the new point cloud?

**Comment by matlabbe** [comment]
Do File->Export 3D clouds. The optimized poses by Post-Processing will be used to assemble the clouds.

**Comment by armanhamzehlou** [comment]
> Do File->Export 3D clouds. The optimized poses by Post-Processing will be used to assemble the clouds.

I don't want a ply format. I want the .db format to be actually updated. Is this possible?

**Comment by pauldeee** [comment]
Open in the DB Viewer, Tools -> Edit database... Make your changes then save the changes to the databse.

**Comment by armanhamzehlou** [comment]
> Open in the DB Viewer, Tools -> Edit database... Make your changes then save the changes to the database.

Yes, This seems actually promising, is there a way to modify the parameters of the loop closure detection in the database editor?

**Comment by pauldeee** [comment]
Rather than exporting the database, try clicking close in the Database Viewer, and click "Save" on the dialog that appears.

The options you are looking for might be found in the Core Parameters. Inside the DB Viewer, choose View -> Core Paramters.

**Comment by armanhamzehlou** [comment]
> Rather than exporting the database, try clicking close in the Database Viewer, and click "Save" on the dialog that appears.
> 
> The options you are looking for might be found in the Core Parameters. Inside the DB Viewer, choose View -> Core Parameters.

Thank you it was very helpful and time-saving.
