### ISSUE TITLE
ROS2 Install Issues

### ISSUE THREAD

**Issue by NathanDodson** [introlab/rtabmap_ros#430]
I'm attempting to install the ROS2 version of RTABMap, but during colcon build I am getting this error:
--- stderr: rtabmap_ros                                         
In file included from /home/nd/ros2_ws/src/rtabmap_ros/src/rviz/MapCloudDisplay.cpp:28:0:
/home/nd/ros2_ws/src/rtabmap_ros/src/rviz/MapCloudDisplay.h:45:10: fatal error: rviz_common/message_filter_display.hpp: No such file or directory
 #include "rviz_common/message_filter_display.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I have an install of ROS2 Dashing and the TB3 packages on Ubuntu 18.04, but not much else on the system, so I'm unsure why it can't find rviz_common/message_filter_display.hpp during build.

**Comment by matlabbe** [comment]
ROS2 build has been tested only on Eloquent, as many things were missing in Dashing.
