### ISSUE TITLE
Multiple RGBD cameras SLAM with only one master camera for VO

### ISSUE THREAD

**Issue by szx0112** [introlab/rtabmap_ros#445]
I'd like to use multiple RGBD cameras for extended FOV. I noticed that when multiple cameras are used, RTABMAP only supports the 3D-3D registration for VO. Thus, I'd like to use only one camera for VO but all the cameras for mapping.

So in rgbd_odometry:
I remap the "rgbd_image" to the rgbd image from only one master camera, and set the number of rgbd_cameras as 1.
I also set to enable BA and 3D-2D pnp for single camera VO.

In rtabmap node:
The "rgbd_cameras" are set as 4 (number of cameras) for mapping using extended FOV
And remap the 'rgbd_image' from each camera as 'rgbd_imageindex"

When I execute the launch file. I got the error:
[ERROR] (2020-07-28 10:16:48.241) RegistrationVis.cpp:1302::computeTransformationImpl() Calibrated camera required (multi-cameras not supported). Id=-1 Models=0 StereoModel=0 weight=0

As far as I know, the error is related to that the 3D-2D pnp is not supported in the multi-camera mode. However, only one camera is used for the VO in my case. How should I modify the launch file in order to make it works?

Any comment is appreciated.

**Comment by matlabbe** [comment]
It seems correct. Is the error coming from rgbd_odometry node or rtabmap node? For rtabmap node, make sure to add parameter `Vis/EstimationType` to 0.

**Comment by hagen6835** [comment]
If im only using ICP Registration (```<param name="Reg/Strategy"   value="1"/>``` ), why should this value need to be set?

**Comment by matlabbe** [comment]
What "this value" are you referring? If you are using ICP, `Vis/EstimationType` is used for visual loop closure detection even if you set `Reg/Strategy` to 1. If you don't have a multi-camera setup, you can ignore that parameter.

Note for the original question, `Vis/EstimationType=1` (default) can now work if rtabmap is built with [OpenGV](https://github.com/laurentkneip/opengv).

**Comment by hagen6835** [comment]
The value i was referring to was the Vis/EstimationType. Knowing it is used for loop closure is quite insightful! We do have a multicamera setup, I will be attaching the launch file below

3 follow up questions then:

We followed the OpenGV installation [here](https://laurentkneip.github.io/opengv/page_installation.html) without any errors, however when building rtabmap from source, we still get "With OpenGV = NO (OpenGV not found)". How do we point rtabmap to opengv?

Is using Vis/EstimationType=1 (3D->2D (PnP)) a large improvement over 3D->3D? I only ask because we are having quite poor mapping performance that results in an incorrect map->odom transform more often than not. We also think that this may be due to poor loop closure but we are quite unsure.


Here is the launch file (we are using stereo rtabmap_odom fed into a ukf filter. I can include that launch file two if necessary). Does anything stick out as obviously causing problems? do you have any general suggestions or things to try?:

<launch>

    <!-- SLAM NODE LAUNCHING -->
    <!-- args: "delete_db_on_start" and "udebug" -->
    <group ns="rtabmap_global">
        <node pkg="rtabmap_slam" type="rtabmap" name="rtabmap" output="screen" args="--delete_db_on_start">
            <!-- GENERAL STUFF -->
            <param name="subscribe_depth"                      value="false"/>
            <param name="subscribe_rgbd"                       value="true"/>
            <param name="rgbd_cameras"                         value="2"/>
            <param name="frame_id"                             value="base_link"/>

            <!-- TF/TOPIC STUFF -->
            <remap from="odom"          to="/mavros/odometry/out"/>
            <remap from="rgbd_image0"   to="/camera_front/rgbd_image"/>
            <remap from="rgbd_image1"   to="/camera_back/rgbd_image"/>
            
            
            <!-- MAPPING PARAMS -->
            <!-- LISTED PARAMS HERE: http://wiki.ros.org/rtabmap_slam -->
            <!-- this seems to remove the "Requested laser scan data" error we were getting-->
            <!-- default value is false -->
            <param name="gen_scan"                             value="true"/>
            
            <!-- defaults to false -->
            <!-- refresh grid map even if we are not moving-->
            <param name="map_always_update"                    value="true"/>        

            <!-- don't fill empty space between the generated scans-->
            <!-- defaults to "true" but only works if "map_always_update" is "true" -->
            <param name="map_empty_ray_tracing"                value="true"/> 
            
            <!-- defaults to 0 (int) -->
            <!-- Fill holes of empty pixels up to this size. Values are interpolated from neighbor depth values. 0 means disabled. -->
            <param name="gen_depth_fill_holes_size"                    value="0"/>   
            
            <!-- defaults to 0.1 -->
            <!-- Maximum depth error (m) to interpolate. -->
            <param name="gen_depth_fill_iterations"                    value="0.1"/>   
            
            <!-- defaults to 1 (int) -->
            <!-- Number of iterations to fill holes. -->
            <param name="gen_depth_fill_holes_error"                    value="1"/>   
            
            <!-- defaults to false -->
            <!-- adjusts recieved images odometry according to the time taken. -->
            <param name="odom_sensor_sync"                    value="false"/>   
            
            <!-- defaults to 0.0 -->
            <!-- only displays one node within this radius of other nodes. uses most recent option (setting to 0 disables) -->
            <param name="map_filter_radius"                    value="0.0"/>   
            
            <!-- defaults to 30.0 -->
            <!-- only displays one node within this angle of other nodes(deg??). disabled if map_filter_radius is disabled -->
            <param name="map_filter_angle"                    value="15.0"/>   





            <!-- UNLISTED PARAMS HERE: https://github.com/introlab/rtabmap/blob/master/corelib/include/rtabmap/core/Parameters.h -->

            <!-- default is 1 -->
            <!-- should be 0 for multi-cameras -->
            <!--  0:3D->3D, 1:3D->2D (PnP), 2:2D->2D (Epipolar Geometry) -->
            <!-- i think this is used only if we are doing visual registration with/instead of ICP registration -->
            <param name="Vis/EstimationType"            value="0"/>
            
            
            
            <!-- default is false -->
            <!-- When a new node is added to the graph, the transformation of its neighbor 
                    link to the previous node is refined using registration approach selected (Reg/Strategy) -->
            <param name="RGBD/NeighborLinkRefining"     value="true"/>
            
            <!-- default is true -->
            <!-- Detection over locations (in Working Memory) near in space. -->
            <param name="RGBD/ProximityBySpace"         value="true"/>
            
            <!-- default is 0.1 -->
            <!-- Minimum angular displacement (rad) to update the map. -->
            <param name="RGBD/AngularUpdate"            value="0.01"/>
            
            <!-- default is 0.1 -->
            <!-- Minimum linear displacement (m) to update the map. -->
            <param name="RGBD/LinearUpdate"             value="0.01"/>
            
            <!-- default is false -->
            <!-- Optimize graph from the newest node. If false, the graph is optimized from the oldest node of the current graph 
                (this adds an overhead computation to detect to oldest node of the current graph, but it can be useful to 
                preserve the map referential from the oldest node). Warning when set to false: when some nodes are transferred, 
                the first referential of the local map may change, resulting in momentary changes in robot/map position 
                (which are annoying in teleoperation). -->
            <!-- This is good to be false because we want our origin to remain constant -->
            <param name="RGBD/OptimizeFromGraphEnd"     value="false"/>


            
            
            <!-- MAYBE DEPRICATED FOR "Grid/Sensor". this defaults to "1" which indicates depth -->
            <param name="Grid/Sensor"                value="1"/>
            <!-- CANT FIND DEFAULT  -->
            <!-- this does the same thing as the above variable but theres no documentation for it???
            I.e. it's depricated but still works?? lol -->
            <!-- <param name="Grid/FromDepth"                value="true"/> -->
            
            <!-- default is 0.05 -->
            <!-- size of the occupational grid cells -->
            <param name="Grid/CellSize"                 value="0.025"/>
            
            <!-- default is 5.0 -->
            <param name="Grid/RangeMax"                 value="3.0"/>
            
            <!-- default is 0.0 -->
            <param name="Grid/NoiseFilteringRadius"                 value="1.0"/>
            
            <!-- default is 0.0 -->
            <param name="Grid/RayTracing"                 value="True"/>



            
            <!-- default is false -->
            <!-- our vehicle translates in 3d space and can yaw in any direction so there are at least 4dof -->
            <param name="Reg/Force3DoF"                 value="false"/>
            
            <!-- default is 0 -->
            <!-- 0=Vis, 1=Icp, 2=VisIcp -->
            <!-- 1 seems to be best -->
            <param name="Reg/Strategy"                  value="1"/>




            <!-- default is 0 -->
            <!-- ICP implementation: 0=Point Cloud Library, 1=libpointmatcher, 2=CCCoreLib -->
            <param name="Icp/Strategy"                 value="1"/>

            <!-- default is 0.2 -->
            <!-- Maximum ICP translation correction accepted (m). -->
            <param name="Icp/MaxTranslation"                 value="0.2"/>

            <!-- default is 0.78 -->
            <!-- Maximum ICP rotation correction accepted (rad). -->
            <param name="Icp/MaxRotation"                 value="0.78"/>

            <!-- default is 0.05 -->
            <!-- Uniform sampling voxel size (0=disabled) -->
            <param name="Icp/VoxelSize"                 value="0.05"/>
            
            <!-- default is 0.1 if using point to plane icp, otherwise its 0.05 -->
            <param name="Icp/MaxCorrespondenceDistance" value="0.1"/>
        
        </node>
    </group>


</launch>

**Comment by matlabbe** [comment]
For opengv, did you do `sudo make install`? You may also have to remove `-march=native` https://gist.githubusercontent.com/matlabbe/a412cf7c4627253874f81a00745a7fbb/raw/accc3acf465d1ffd0304a46b17741f62d4d354ef/opengv_disable_march_native.patch

3D->3D is very dependent to depth accuracy, while 2D->3D is less (usually better for cameras as far features can still be used for rotation estimation).

If you don't have a real lidar, I would set `gen_scan` to false. Set back `Reg/Strategy` to 0.

**Comment by hagen6835** [comment]
Thank you, i was able to fix the opengv issue by just uninstalling and then following the steps outlined [here](https://github.com/introlab/rtabmap/issues/1084#issuecomment-1624727064).

after some initial tests, 2D->3D does generally seem to perform better with the multicamera setup as well as switching back to visual registration
