### ISSUE TITLE
Ground Plane assumption in RTABmap

### ISSUE THREAD

**Issue by ibrahiminfinite** [introlab/rtabmap_ros#446]
Hi @matlabbe 

Is it possible for RTABmap to assemble maps with elevations?
Robot  Setup is single RGBD camera + 2D lidar.
Like when the map needs to be generated while you are going up or down the stairs in a building .
Or is there any assumption about the ground plane being flat and uniform?

PS : I am using Rviz with RTABmap plugin for visualization.

Thankyou

**Comment by matlabbe** [comment]
If your odometry is 6DoF, then the map will be 3D. For the 2D occupancy grid, it assumes we are moving in 3DoF.
