### ISSUE TITLE
[Possible bug] [Grid_prob_]map services

### ISSUE THREAD

**Issue by eliabntt** [introlab/rtabmap_ros#447]
Hi, I just want to let you know that the service "/rtabmap/get_prob_map" is only available if there is an active subscriber[either rviz or in code]. Is this the desired behavior? Can we enable it by default to expose the service and constantly build a map even if rviz is turned off w/o any other subscriber? [I'm a bit behind on the rtabmap revision so I may need to update but by looking at the commit history seems you haven't changed anything there]. Same applies for other (map) services.

**Comment by matlabbe** [comment]
Good point! The octomap services seem okay though. I updated in the commit above for the occupancy grid services.

cheers,
Mathieu
