### ISSUE TITLE
localization with turtlebot issue

### ISSUE THREAD

**Issue by kaygudo** [introlab/rtabmap_ros#46]
Hello,
As instructed in the tutorial [Mapping and Navigation with Turtlebot](http://wiki.ros.org/rtabmap_ros/Tutorials/MappingAndNavigationOnTurtlebot) after mapping "$ roslaunch rtabmap_ros demo_turtlebot_mapping.launch args:="--delete_db_on_start" rgbd_odometry:=true"

for localization when i try to execute the command " $ roslaunch rtabmap_ros demo_turtlebot_mapping.launch localization:=true" .

i get following error:

[ INFO] [1454339969.590369016]: rtabmap 0.10.10 started...
[ INFO] [1454339970.864339986]: Stopping device RGB and Depth stream flush.
[ WARN] [1454339972.332150185]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: Could not find a connection between 'map' and 'base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.. canTransform returned after 0.100846 timeout was 0.1.
[ WARN] [1454339974.865176406]: rtabmap: Could not get transform from odom to base_footprint after 0.100000 second!
[ WARN] [1454339974.995544194]: rtabmap: Could not get transform from odom to base_footprint after 0.100000 second!

and this goes on....

what's the issue? please guide me i am new to ROS.

Thank you

**Comment by matlabbe** [comment]
See http://answers.ros.org/question/225559/rtabmap-localization-with-turtlebot-issue/?answer=225844#post-id-225844

cheers,
Mathieu
