### ISSUE TITLE
does the occupancy grid /octomap gets updated in localization mode [question]

### ISSUE THREAD

**Issue by NicoNorena** [introlab/rtabmap_ros#476]
@matlabbe 
Does the occupancy grid and octomap in RTABmap gets updated by appending the newest node when running in localization mode? meaning whether the topic "octomap_binary" would show the new objects or moving objects without actually adding them  to the map. I am using  it in RGBD mode. 

I read that when it has a laser and RGBD, it uses the laser for updating with newest node when setting the parameter "raytracing".  Is this correct?

**Comment by matlabbe** [comment]
By default no. If you set `map_always_update` to `true` for rtabmap node, the occupancy grids/octomap will get updated without actually changing the original map (i.e., the new obstacles added won't be there if you restart rtabmap). If you enable `Grid/RayTracing` (default true for scans), it will be able to clear obstacles not here anymore.

**Comment by NicoNorena** [comment]
cool thanks, I will test it out.

can  `Grid/RayTracing` be used when only using RGBD?  basically is a scan input required when enabling `Grid/RayTracing`

**Comment by matlabbe** [comment]
`Grid/RayTracing` works with stereo and RGB-D data. You can see the Figure 7 of this [paper](https://introlab.3it.usherbrooke.ca/mediawiki-introlab/images/7/7a/Labbe18JFR_preprint.pdf) for all possible combinations:
![Screenshot from 2020-10-17 17-12-00](https://user-images.githubusercontent.com/2319645/96353626-e6051480-109b-11eb-9de7-37250a6df539.jpg)

Note that if Grid/3D is enabled, OctoMap's 3D ray tracing is done, which can be computationally expensive.
