### ISSUE TITLE
Unexpected occupancy grid map

### ISSUE THREAD

**Issue by mirellameelo** [introlab/rtabmap_ros#479]
Hi! Thanks for sharing this project!

I just started using Rtabmap and I'm having an unexpected 2D occupancy grid map. 
I'm using a stereo camera and interested in achieving the 2D occupancy grid map of a virtual scene. Since I could not find any launch file example for stereo (ROS2), [here is the one I did](https://github.com/mirellameelo/rtabmap_ros/blob/ros2/launch/ros2/stereo_launch.py). 

As follows is my output in the 'Rtarviz' viewer. There is the 3D map that is duplicated.

![Captura de tela de 2020-10-15 09-49-20](https://user-images.githubusercontent.com/34249507/96308403-2f7c3380-0fb8-11eb-9966-9d585cf1b4c3.png)

To visualize the grid map, I subscribed to the topic '/map' in Rviz, then the map generated starts detecting the wall pretty well, but then all became black. Besides the strange behavior of the grid map became all 'black', it is been built on the opposite side of the walk direction of the camera (points in red are the odometry which is consistent with the real trajectory). By the way, I set 'map_empty_ray_tracing' to true, but no ray is forming, so I believe this is not the right parameter to set. Could you please also help me with that?

![Captura de tela de 2020-10-15 17-07-36](https://user-images.githubusercontent.com/34249507/96308576-83871800-0fb8-11eb-9319-cd9be3c07136.png)

![Captura de tela de 2020-10-15 17-07-51](https://user-images.githubusercontent.com/34249507/96308596-8aae2600-0fb8-11eb-8029-9b0841374bc7.png)

Really appreciate any help, and let me know any complimentary info to add in here. Thanks!

**Comment by matlabbe** [comment]
cross-ref: https://answers.ros.org/question/363506/rtab-map-unexpected-occupancy-grid-map/ see my comment.
