### ISSUE TITLE
EnvSensor’ in namespace ‘rtabmap_ros’ does not name a type

### ISSUE THREAD

**Issue by ghokulji** [introlab/rtabmap_ros#487]
I built the rtabmap_ros package from source, I am facing the error : ‘EnvSensor’ in namespace ‘rtabmap_ros’ does not name a type
 error: ‘rtabmap_ros::EnvSensor’ has not been declared.

![rt](https://user-images.githubusercontent.com/28822039/97174598-51479880-17b8-11eb-86ec-4d08831375a2.png)

The only error coming while catkin_make is the env_sensor erroe

**Comment by matlabbe** [comment]
The message should be built: https://github.com/introlab/rtabmap_ros/blob/f748a671841be68698e3b702619e594bf62d74b0/CMakeLists.txt#L109

**Comment by ghokulji** [comment]
Yes the setup.bassh is sourced.
I reinstalled the rtabmap and rtabmap_ros packaages and now it is working fine.
