### ISSUE TITLE
Tutorials: RemoteMapping

### ISSUE THREAD

**Issue by OAkyildiz** [introlab/rtabmap_ros#49]
In the page rtabmap_ros/Tutorials/RemoteMapping of ros wiki [http://wiki.ros.org/rtabmap_ros/Tutorials/RemoteMapping](http://wiki.ros.org/rtabmap_ros/Tutorials/RemoteMapping)

In order to use the turoial with[ iai_kinect2](https://github.com/code-iai/iai_kinect2)

```
  <!-- Use same nodelet used by Freenect/OpenNI -->
  <group ns="camera">
     <node pkg="nodelet" type="nodelet" name="data_throttle" args="load rtabmap_ros/data_throttle camera_nodelet_manager" output="screen">
       <param name="rate" type="double" value="$(arg rate)"/>
```

`camera_nodelet_manager` can be changed to iai_kinect2's nodelet manager, which is the `base_name` argument in its own launch.  In that case topics to remap would be` "/$(arg namespace)/$(arg base_name)/$(arg resolution)/...`

Just wanted to put it there if anyone is using iai_kinect2 and was wondering about the throttling.

**Comment by matlabbe** [comment]
Great thx!
