### ISSUE TITLE
Multi-session mapping demo, 'Unsupported image format' Error

### ISSUE THREAD

**Issue by Kondr2** [introlab/rtabmap_ros#509]
Hi,
when launching RTABMap on Multi-Session .bag data from [this tutorial](http://wiki.ros.org/rtabmap_ros#Multi-session_mapping) got this error, resulting with messages not being received by rtabmap node:
`1389713461.311285966 ERROR /points_xyzrgb [/tmp/binarydeb/ros-noetic-compressed-depth-image-transport-1.14.0/src/codec.cpp:86(Image_<std::allocator<void> >::Ptr compressed_depth_image_transport::decodeCompressedDepthImage)] [topics: /rosout, /voxel_cloud, /points_xyzrgb/rgb/compressed/parameter_descriptions, /points_xyzrgb/rgb/compressed/parameter_updates] Unsupported image format: 16UC1; compressedDepth`

Error is traced back to [this line](https://github.com/ros-perception/image_transport_plugins/blob/noetic-devel/compressed_depth_image_transport/src/codec.cpp#L86). If I understand correctly, data in the tutorial was not updated to the new format: messages in `/data_throttled_image_depth/compressedDepth` topic have '16UC1; compressedDepth' format, that worked with [old version of that file](https://github.com/ros-perception/image_transport_plugins/blob/76d270eacd60b2576c46ee1d853164904132b928/compressed_depth_image_transport/src/codec.cpp#L73), but '16UC1; compressedDepth png' required in the new version.

**Comment by matlabbe** [comment]
This problem also happened with demo_mapping.bag: http://wiki.ros.org/rtabmap_ros#Robot_mapping, there is a note:

> fixed compressedDepth encoding format 2020/05/27

The idea is to parse the rosbag wth a python script to change all "16UC1; compressedDepth" to "16UC1; compressedDepth png". I didn't test, but it would be something like this:

```python
import rosbag
from sensor_msgs.msg import CompressedImage
with rosbag.Bag('output1.bag', 'w') as outbag:
	for topic, msg, t in rosbag.Bag('map1.bag').read_messages():
		if topic == "data_throttled_image_depth/compressedDepth":
			msg.format = msg.format + " png"
			print("Updated compressed format! \"%s\"" % (msg.format))
		outbag.write(topic, msg, t)
```
