### ISSUE TITLE
Finer Map

### ISSUE THREAD

**Issue by ManChrys** [introlab/rtabmap_ros#523]
Hello guys,

when im using zed_rtabmap_example i have this result

![Screenshot from 2021-01-11 16-51-29](https://user-images.githubusercontent.com/67521662/104197570-dba1af00-542d-11eb-8209-156869cf8a89.png)

Post processing makes it a little better but still have that "noise". Which parameters improve the pointcloud?

Thanks again guys.

**Comment by matlabbe** [comment]
You could tune zed parameters to avoid too much interpolation in textureless areas. You may tune those parameters: https://github.com/stereolabs/zed-ros-wrapper/blob/f5a691c39b01c565b7d3897c1f36f413c21d5782/zed_wrapper/params/common.yaml#L17-L18
In rtabmap standalone, we set them by default to 100 and 90 respectively.

**Comment by ManChrys** [comment]
ill try that my friend and ill inform you soon.

Thank you one more time for your help and advices. Have a nice weekend.

**Comment by ManChrys** [comment]
Hello @matlabbe, yeah it worked you were right. Thank you my friend.
