### ISSUE TITLE
Rtabmapviz on separate computer

### ISSUE THREAD

**Issue by derektan95** [introlab/rtabmap_ros#530]
Hi @matlabbe, 

I would like to clarify a confusion I currently have with rtabmapviz. This is related to how rtabmap ROS node relates to rtabmapviz ROS node. I've installed Rtab-map on my Nvidia Jetson TX2 (with ROS Melodic), but I would like to view the results on another computer with an Ubuntu 16.04 (ROS Kinetic) since I am controlling the robot remotely. While I installed Rtab-map on the TX2 from source, I installed Rtab-map on my computer via binaries for convenience sake, since it's purpose is simply to run rtabmapviz. 

My question is, would any advanced settings done on my rtabmapviz run on my other computer (ROS Kinetic) have any effects on the Rtab-map mapping node running on the Nvidia board (ROS Melodic)? For instance, if the launch file on the Nvidia board is set to 1Hz, and if I were to change that to another value on Rtabmapviz running on my other computer, would this change override the initial settings on the launch file? 

Thank you again so much for your help!

**Comment by matlabbe** [comment]
Yes, you have to make sure that computers can correctly see each other on both side. This can be done explicitly by setting the `ROS_IP` on both computers.

Then, to make the advanced settings working, launch rtabmapviz in same namespace than rtabmap so it can see rtabmap parameters when opening Preferences. For example, if rtabmap is launched in rtabmap namespace, launch rtabmapviz like this:
```
export ROS_NAMESPACE=rtabmap
rosrun rtabmap_ros rtabmapviz
```

**Comment by derektan95** [comment]
Hi Matlabbe, 

Thanks! It seems that by setting all advanced parameters in the launch file, another computer connected to the same ROS network can launch rtabmapviz with the same advanced parameters. Appreciate your reply. 

- Derek
