### ISSUE TITLE
Compilation Error on ROS Noetic

### ISSUE THREAD

**Issue by ElClopitan** [introlab/rtabmap_ros#533]
![Screenshot from 2021-01-26 12-57-13](https://user-images.githubusercontent.com/23469686/105904490-0d8e4600-5fd6-11eb-8615-6da49e9769c6.png)
Seem to have a compilation error on ROS Noetic. I am using noetic-devel for rtabmap built from source and rtabmap_ros.

**Comment by matlabbe** [comment]
The noetic-devel branch of rtabmap doesn't match the version you have, lines 993 and 994 should be:
https://github.com/introlab/rtabmap_ros/blob/b7a66e41f16ae6f450590ef6a2efd654970acd02/src/MsgConversion.cpp#L993-L994

make sure you are on noetic-devel branch with latest changes.

**Comment by ElClopitan** [comment]
Thank you! You were right that I wasn't up to date but I am still getting a different error that is outside rtabmap.
![Screenshot from 2021-01-26 13-45-53](https://user-images.githubusercontent.com/23469686/105909761-da02ea00-5fdc-11eb-93e0-015bc1f84a15.png)
If you have any advice for this it would be greatly appreciated!

**Comment by matlabbe** [comment]
This is a teb_local_planner issue. g2o has been updated their interface to c++14 recently, teb_local_planner may not have updated yet. I would recommend to build/install this version of g2o: https://github.com/RainerKuemmerle/g2o/releases/tag/20201223_git

**Comment by ElClopitan** [comment]
Okay. Thank you!
