### ISSUE TITLE
Generate new poses even when not moving

### ISSUE THREAD

**Issue by thohemp** [introlab/rtabmap_ros#538]
Hello,

I experience that there are only new poses added to the trajectory when the camera moves for a decent distance. Is there a way to force the addition of new poses even in situations where the camera is static?

Thanks in adavance

**Comment by matlabbe** [comment]
You can set `RGBD/LinearUpdate` to 0 so that new frames are added to graph if if not moving.

**Comment by thohemp** [comment]
Thanks!
