### ISSUE TITLE
How to customize rtabmap.launch to load in a custom parameter file

### ISSUE THREAD

**Issue by sisaha9** [introlab/rtabmap_ros#541]
https://github.com/introlab/rtabmap_ros/blob/master/launch/rtabmap.launch

Is there a way to load a custom set of parameters into this file instead of manually changing?

**Comment by matlabbe** [comment]
Yes, it is not meant to be modified. Look at this [example](http://official-rtab-map-forum.67519.x6.nabble.com/Is-this-the-way-to-use-lidar-IMU-efficiently-tp7496p7515.html) or those [examples](http://wiki.ros.org/rtabmap_ros/Tutorials/HandHeldMapping). You can pass RTAB-Map's parameters (`$ rtabmap --params`) in the `args` or `rtabmap_args` argument of the launch file.
