### ISSUE TITLE
cmake error due to mismatched rtabmap versions, but `apt list` shows no upgrades available

### ISSUE THREAD

**Issue by jenn-yu** [introlab/rtabmap_ros#545]
Ran `catkin_make` in a catkin workspace with rtabmap installed. 
However, I'm getting this cmake error:

![image](https://user-images.githubusercontent.com/39226391/108585219-4390c280-7315-11eb-889a-5489b2a2fa0b.png)

However, running `sudo apt-get update && apt-get upgrade` does not upgrade to the requested rtabmap. And `apt list --upgradeable` shows nothing is remaining which is upgradeable.

![image](https://user-images.githubusercontent.com/39226391/108585282-99656a80-7315-11eb-87ce-4c310c48d705.png)

**Comment by matlabbe** [comment]
This error is on purpose, it tells that you also need to build/install rtabmap library with the correct version. Make sure to uninstall rtabmap binaries to avoid wrong libraries loaded on runtime:
```
sudo apt remove ros-kinetic-rtabmap
```
