### ISSUE TITLE
Process has died error

### ISSUE THREAD

**Issue by irmas** [introlab/rtabmap_ros#55]
Hello,

When I launch rtabmap with a launch file I get the following error 
`
[rtabmap/rgbd_odometry-1] process has died [pid 4273, exit code -6, cmd /home/jb/catkin_ws/devel/lib/rtabmap_ros/rgbd_odometry rgb/image:=/camera/rgb/image_rect_color depth/image:=/camera/depth_registered/image_raw rgb/camera_info:=/camera/rgb/camera_info __name:=rgbd_odometry __log:=/home/jb/.ros/log/a5cf4b7c-e5f5-11e5-bd00-e006e641df76/rtabmap-rgbd_odometry-1.log]`

I've followed  [this guide](https://github.com/introlab/rtabmap_ros/issues/28) but unfortunately I wasn't able to get it to work.
I used gdb to get the error and this is what I got (sorry for the screenshot I couldn't copy/paste).

![screenshot from 2016-03-09 13 58 45](https://cloud.githubusercontent.com/assets/693055/13635919/1b20152e-e5ff-11e5-8200-70d16b66e8a5.png)

Thank you very much for your help and best wishes.

**Comment by matlabbe** [comment]
Hi,

I see that Qt5 binaries are loaded. Did you build manually rtabmap and against Qt5? On ROS, it is Qt4 used normally. The problem may be that wrong Qt4 or Qt5 libraries are used on runtime as in this post: http://stackoverflow.com/questions/23646718/qt-application-startup-crash

cheers
