### ISSUE TITLE
How to deal with pose jump in localization mode?

### ISSUE THREAD

**Issue by bill4u** [introlab/rtabmap_ros#551]
@matlabbe Hi, Thanks for your time. My robot pose  jumpes in my house and I have no ideas how to deal with it. It's kind of you to offer some advices.

**Rtabmap version**: 0.20.6
**My sensors**: D435i + T265 + 2d Lidar(pepperl funch R2000)
**Mapping command :** 
roslaunch rtabmap_ros rtabmap.launch 
args:="-d --Mem/UseOdomGravity true --Optimizer/GravitySigma 0.3"  
odom_topic:=/t265/odom/sample 
frame_id:=t265_link 
rgbd_sync:=true 
depth_topic:=/d400/aligned_depth_to_color/image_raw 
rgb_topic:=/d400/color/image_raw 
camera_info_topic:=/d400/color/camera_info 
approx_rgbd_sync:=false 
visual_odometry:=false 
rviz:=true 
rtabmapviz:=false 
subscribe_scan:=true

There are some parameters **added to** the default **rtabmap.launch** file: 
                    param name="RGBD/NeighborLinkRefining"              type="string" value="true"
                    param name="RGBD/ProximityBySpace"                   type="string" value="true"
                    param name="RGBD/ProximityByTime"                     type="string" value="false"
                    param name="RGBD/ProximityPathMaxNeighbors"  type="string" value="10"
                    param name="Reg/Strategy"                                      type="string" value="1"
                    param name="Vis/MinInliers"                                     type="string" value="12"
                    param name="RGBD/OptimizeFromGraphEnd"        type="string" value="false"
                    param name="RGBD/OptimizeMaxError"                  type="string" value="3"
                    param name="Reg/Force3DoF"                                 type="string" value="true"
                    param name="Grid/FromDepth"                                 type="string" value="false"
                    param name="Mem/STMSize"                                   type="string" value="30"
                    param name="RGBD/LocalRadius"                           type="string" value="5"
                    param name="Icp/CorrespondenceRatio"                 type="string" value="0.4"
                    param name="RGBD/AngularUpdate"                      type="string" value="0.1"
                    param name="RGBD/LinearUpdate"                        type="string" value="0.1"

**The poses are generate from the command** : _rosrun tf tf_echo /map /t265_link_

And the **poses** sometimes **jump quite a lot, like 50cm**.
And in the RVIZ, the TOPIC: MapCloud appears in the RIVZ if the loop closure happens, just like in the RtabMapVIZ, the left middle color is yellow or green. While the poses jump when the color is red or the MapCloud disappear in the RVIZ.

**My question is :** 
      **_How can I do to minimize the pose jump?_ 
      Do I need to add the IMU data from D435i?
      _And how can I take the advantage of the  precise result of Lidar?_ 
      In my setting, Lidar data just feed into the icp_odometry?** 

Please, I need your help. How to smooth the result. Thanks a lot.

**Comment by bill4u** [comment]
https://user-images.githubusercontent.com/12217369/109643584-62058200-7b8f-11eb-8964-830a17440970.mp4

**Comment by bill4u** [comment]
And this is my record data:
I don't know if Baidu cloud disc is accessable for you?

**Link:** https://pan.baidu.com/s/1lKM1dATmJd-M5oJDcHiokQ 
**extract code:** 9qgx

**Comment by matlabbe** [comment]
The jumps in the video are expected, because of the lidar noise and not perfect map. When you say:

> There are some parameters added to the default rtabmap.launch file

Make sure in the terminal log on startup that rtabmap is correctly loading those parameters (with Reg/Strategy=1, you should have quite accurate localization if the lidar can see walls). For 50 cm jumps, it is quite high though. 

> While the poses jump when the color is red or the MapCloud disappear in the RVIZ.

If MapCLoud disappears, it means that rtabmap detected an odometry reset, thus creating a new session. A red link means a global loop closure, which would correct odometry drift, thus the robot can jump even meters when this happens if the odometry has drifted a lot.

**Comment by bill4u** [comment]
@matlabbe , You are right, After double checking, the poor map is the main problem. But I have no idea why the loop cloure not happen when the robot visit the same position. As in the map, the chair has triple RGBD cloud assembled.
![2021-03-04 07-49-37屏幕截图](https://user-images.githubusercontent.com/12217369/109888811-2a95f300-7cbf-11eb-8ede-c3894e40f239.png)

The info of program is as follows:

[ INFO] [1614815299.601559806, 1613904692.843858298]: rztechmap (46): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.0865s, Maps update=0.0014s pub=0.0000s (local map=19, WM=19)
[ INFO] [1614815300.600044468, 1613904693.835937013]: rztechmap (47): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.0736s, Maps update=0.0009s pub=0.0000s (local map=20, WM=20)
[ INFO] [1614815301.693155633, 1613904694.930426443]: rztechmap (48): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.0778s, Maps update=0.0010s pub=0.0000s (local map=21, WM=21)
[ INFO] [1614815302.657438414, 1613904695.900737275]: rztechmap (49): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.0395s, Maps update=0.0006s pub=0.0000s (local map=22, WM=22)
[ INFO] [1614815303.899084406, 1613904697.140487045]: rztechmap (50): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.0623s, Maps update=0.0021s pub=0.0000s (local map=23, WM=23)
[ INFO] [1614815304.917955277, 1613904698.157717449]: rztechmap (51): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.0785s, Maps update=0.0016s pub=0.0000s (local map=24, WM=24)
**[ WARN] (2021-03-04 07:48:26.001) RegistrationVis.cpp:1099::computeTransformationImpl() All projected points are outside the camera. Guess (xyz=0.152261,0.381405,0.000000 rpy=0.000000,0.000000,0.762376) is wrong or images are not overlapping.**
[ INFO] [1614815306.013338719, 1613904699.257362901]: rztechmap (52): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1000s, Maps update=0.0017s pub=0.0000s (local map=25, WM=25)
[ INFO] [1614815307.161863192, 1613904700.399110117]: rztechmap (53): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1710s, Maps update=0.0016s pub=0.0000s (local map=26, WM=26)
[ INFO] [1614815308.155316631, 1613904701.392383295]: rztechmap (54): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1021s, Maps update=0.0015s pub=0.0000s (local map=27, WM=27)
[ INFO] [1614815309.146139933, 1613904702.389754975]: rztechmap (55): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1571s, Maps update=0.0017s pub=0.0000s (local map=28, WM=28)
[ INFO] [1614815310.223167089, 1613904703.462785382]: rztechmap (56): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1238s, Maps update=0.0019s pub=0.0000s (local map=29, WM=29)
[ INFO] [1614815311.306477020, 1613904704.548200015]: rztechmap (57): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1081s, Maps update=0.0021s pub=0.0000s (local map=30, WM=30)
[ INFO] [1614815312.384879056, 1613904705.623326890]: rztechmap (58): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1252s, Maps update=0.0020s pub=0.0000s (local map=31, WM=31)
[ INFO] [1614815313.472922612, 1613904706.714967048]: rztechmap (59): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1536s, Maps update=0.0016s pub=0.0000s (local map=32, WM=32)
[ INFO] [1614815314.509780678, 1613904707.747440232]: rztechmap (60): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1327s, Maps update=0.0040s pub=0.0000s (local map=33, WM=33)
[ INFO] [1614815315.635953105, 1613904708.879271544]: rztechmap (61): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1208s, Maps update=0.0022s pub=0.0000s (local map=34, WM=34)
[ INFO] [1614815316.697366126, 1613904709.941356518]: rztechmap (62): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1140s, Maps update=0.0027s pub=0.0000s (local map=35, WM=35)
[ INFO] [1614815317.792454548, 1613904711.034824977]: rztechmap (63): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1294s, Maps update=0.0018s pub=0.0000s (local map=36, WM=36)
[ **WARN] (2021-03-04 07:48:38.912) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 64 <-> 28) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 5.502707 (edge 28->64, type=2, abs error=0.026198 m, stddev=0.004761). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.**
**[ WARN] (2021-03-04 07:48:38.912) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 64 <-> 28) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 4.800178 (edge 28->64, type=2, abs error=1.309407 deg, stddev=0.004761). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:38.912) Rztechmap.cpp:3046::process() Loop closure 64->28 rejected!**
[ INFO] [1614815318.914683712, 1613904712.156242523]: rztechmap (64): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2080s, Maps update=0.0016s pub=0.0000s (local map=37, WM=37)
[ WARN] (2021-03-04 07:48:40.075) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 65 <-> 29) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 12.194030 (edge 29->65, type=2, abs error=0.040287 m, stddev=0.003304). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:40.075) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 65 <-> 29) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 6.948079 (edge 29->65, type=2, abs error=1.315243 deg, stddev=0.003304). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:40.075) Rztechmap.cpp:3046::process() Loop closure 65->29 rejected!
[ INFO] [1614815320.079045079, 1613904713.324070871]: rztechmap (65): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1739s, Maps update=0.0021s pub=0.0000s (local map=38, WM=38)
[ WARN] (2021-03-04 07:48:41.142) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 66 <-> 29) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 13.205120 (edge 29->66, type=2, abs error=0.052952 m, stddev=0.004010). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:41.142) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 66 <-> 29) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 5.716441 (edge 29->66, type=2, abs error=1.313380 deg, stddev=0.004010). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:41.142) Rztechmap.cpp:3046::process() Loop closure 66->29 rejected!
[ INFO] [1614815321.144919404, 1613904714.386090596]: rztechmap (66): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1821s, Maps update=0.0018s pub=0.0000s (local map=39, WM=39)
[ WARN] (2021-03-04 07:48:42.164) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 67 <-> 30) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 16.023304 (edge 30->67, type=2, abs error=0.062719 m, stddev=0.003914). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:42.164) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 67 <-> 30) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 5.823528 (edge 30->67, type=2, abs error=1.306046 deg, stddev=0.003914). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:42.164) Rztechmap.cpp:3046::process() Loop closure 67->30 rejected!
[ INFO] [1614815322.168797179, 1613904715.410236040]: rztechmap (67): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2128s, Maps update=0.0027s pub=0.0000s (local map=40, WM=40)
[ WARN] (2021-03-04 07:48:43.258) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 68 <-> 31) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 14.576302 (edge 31->68, type=2, abs error=0.062174 m, stddev=0.004265). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:43.258) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 68 <-> 31) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 6.399790 (edge 31->68, type=2, abs error=1.564053 deg, stddev=0.004265). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:43.258) Rztechmap.cpp:3046::process() Loop closure 68->31 rejected!
[ INFO] [1614815323.260676749, 1613904716.500670017]: rztechmap (68): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2052s, Maps update=0.0016s pub=0.0000s (local map=41, WM=41)
**[ WARN] (2021-03-04 07:48:44.352) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 69 <-> 32) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 17.581196 (edge 32->69, type=2, abs error=0.061571 m, stddev=0.003502). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.**
[ **WARN] (2021-03-04 07:48:44.352) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 69 <-> 32) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 6.088092 (edge 32->69, type=2, abs error=1.221612 deg, stddev=0.003502). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation**.
**[ WARN] (2021-03-04 07:48:44.352) Rztechmap.cpp:3046::process() Loop closure 69->32 rejected!**
[ INFO] [1614815324.355133703, 1613904717.592514998]: rztechmap (69): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1998s, Maps update=0.0016s pub=0.0000s (local map=42, WM=42)
[ WARN] (2021-03-04 07:48:45.443) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 70 <-> 32) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 9.878197 (edge 32->70, type=2, abs error=0.059220 m, stddev=0.005995). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:45.443) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 70 <-> 32) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 4.445925 (edge 32->70, type=2, abs error=1.527119 deg, stddev=0.005995). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:45.443) Rztechmap.cpp:3046::process() Loop closure 70->32 rejected!
[ INFO] [1614815325.446165615, 1613904718.685016626]: rztechmap (70): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2027s, Maps update=0.0018s pub=0.0000s (local map=43, WM=43)
[ WARN] (2021-03-04 07:48:46.582) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 71 <-> 34) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 13.127750 (edge 34->71, type=2, abs error=0.055417 m, stddev=0.004221). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:46.582) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 71 <-> 34) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 6.375618 (edge 34->71, type=2, abs error=1.542043 deg, stddev=0.004221). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:46.582) Rztechmap.cpp:3046::process() Loop closure 71->34 rejected!
[ INFO] [1614815326.586178221, 1613904719.822290210]: rztechmap (71): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2789s, Maps update=0.0025s pub=0.0000s (local map=44, WM=44)
[ WARN] (2021-03-04 07:48:47.559) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 72 <-> 35) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 11.648751 (edge 35->72, type=1, abs error=0.051307 m, stddev=0.004405). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:47.559) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 72 <-> 35) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 4.791779 (edge 35->72, type=1, abs error=1.209253 deg, stddev=0.004405). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:47.559) Rztechmap.cpp:3046::process() Loop closure 72->35 rejected!
[ INFO] [1614815327.564017535, 1613904720.801039357]: rztechmap (72): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2837s, Maps update=0.0031s pub=0.0001s (local map=45, WM=45)
[ WARN] (2021-03-04 07:48:48.566) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 73 <-> 35) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 10.794221 (edge 35->73, type=2, abs error=0.045474 m, stddev=0.004213). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:48.566) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 73 <-> 35) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 5.889152 (edge 35->73, type=2, abs error=1.421501 deg, stddev=0.004213). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:48.566) Rztechmap.cpp:3046::process() Loop closure 73->35 rejected!
[ INFO] [1614815328.569592185, 1613904721.815053607]: rztechmap (73): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2339s, Maps update=0.0022s pub=0.0000s (local map=46, WM=46)
[ WARN] (2021-03-04 07:48:49.691) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 74 <-> 38) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 7.513801 (edge 38->74, type=2, abs error=0.036403 m, stddev=0.004845). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:49.691) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 74 <-> 38) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 5.564790 (edge 38->74, type=2, abs error=1.544728 deg, stddev=0.004845). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:49.691) Rztechmap.cpp:3046::process() Loop closure 74->38 rejected!
[ INFO] [1614815329.696539815, 1613904722.940716600]: rztechmap (74): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.3160s, Maps update=0.0033s pub=0.0000s (local map=47, WM=47)
[ WARN] (2021-03-04 07:48:50.646) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 75 <-> 38) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 7.070326 (edge 38->75, type=2, abs error=0.033687 m, stddev=0.004764). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:50.646) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 75 <-> 38) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 5.705459 (edge 38->75, type=2, abs error=1.557509 deg, stddev=0.004764). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:50.646) Rztechmap.cpp:3046::process() Loop closure 75->38 rejected!
[ INFO] [1614815330.649948143, 1613904723.887207821]: rztechmap (75): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2696s, Maps update=0.0023s pub=0.0000s (local map=48, WM=48)
[ INFO] [1614815331.786795852, 1613904725.024023579]: rztechmap (76): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2841s, Maps update=0.0045s pub=0.0001s (local map=49, WM=49)
[ WARN] (2021-03-04 07:48:53.153) Rztechmap.cpp:2582::process() Rejected loop closure 47 -> 77: Not enough inliers 0/12 (matches=23) between 47 and 77
[ INFO] [1614815333.159710650, 1613904726.405383564]: rztechmap (77): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.6546s, Maps update=0.0037s pub=0.0000s (local map=50, WM=50)
[ INFO] [1614815333.732220055, 1613904726.976398317]: rztechmap (78): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1503s, Maps update=0.0070s pub=0.0000s (local map=51, WM=51)
[ INFO] [1614815334.720135612, 1613904727.962229786]: rztechmap (79): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1343s, Maps update=0.0038s pub=0.0000s (local map=52, WM=52)
[ WARN] (2021-03-04 07:48:55.736) RegistrationVis.cpp:1099::computeTransformationImpl() All projected points are outside the camera. Guess (xyz=0.009106,0.316412,0.000000 rpy=0.000000,0.000000,0.752901) is wrong or images are not overlapping.
[ INFO] [1614815335.773947015, 1613904729.009781086]: rztechmap (80): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1339s, Maps update=0.0039s pub=0.0000s (local map=53, WM=53)
[ INFO] [1614815336.881973294, 1613904730.116898984]: rztechmap (81): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1806s, Maps update=0.0066s pub=0.0001s (local map=54, WM=54)
[ INFO] [1614815337.888224317, 1613904731.127002414]: rztechmap (82): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.1250s, Maps update=0.0046s pub=0.0000s (local map=54, WM=54)
[ WARN] (2021-03-04 07:48:58.986) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 83 <-> 28) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 9.023143 (edge 28->83, type=1, abs error=0.036125 m, stddev=0.004004). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:58.986) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 83 <-> 28) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 8.813869 (edge 28->83, type=1, abs error=2.021815 deg, stddev=0.004004). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:48:58.986) Rztechmap.cpp:3046::process() Loop closure 83->28 rejected!
[ INFO] [1614815338.996161630, 1613904732.233043385]: rztechmap (83): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2200s, Maps update=0.0062s pub=0.0000s (local map=54, WM=54)
[ WARN] (2021-03-04 07:49:00.042) Rztechmap.cpp:2582::process() Rejected loop closure 28 -> 84: Cannot compute transform (cor=446 corrRatio=0.395741/0.400000 maxLaserScans=1127)
[ INFO] [1614815340.050291250, 1613904733.286545435]: rztechmap (84): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2231s, Maps update=0.0048s pub=0.0000s (local map=54, WM=54)
[ WARN] (2021-03-04 07:49:01.144) Rztechmap.cpp:2582::process() Rejected loop closure 28 -> 85: Cannot compute transform (cor=433 corrRatio=0.384206/0.400000 maxLaserScans=1127)
[ INFO] [1614815341.151934195, 1613904734.396612669]: rztechmap (85): Rate=1.00s, Limit=0.000s, RZTECH-Map=0.2554s, Maps update=0.0036s pub=0.0000s (local map=54, WM=54)
[ WARN] (2021-03-04 07:49:02.133) Rztechmap.cpp:2997::process() Rejecting all added loop closures (1, first is 86 <-> 28) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 7.211219 (edge 28->86, type=1, abs error=0.036469 m, stddev=0.005057). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:49:02.133) Rztechmap.cpp:3021::process() Rejecting all added loop closures (1, first is 86 <-> 28) in this iteration because a wrong loop closure has been detected after graph optimization, resulting in a maximum graph error ratio of 6.933837 (edge 28->86, type=1, abs error=2.009127 deg, stddev=0.005057). The maximum error ratio parameter "RGBD/OptimizeMaxError" is 3.000000 of std deviation.
[ WARN] (2021-03-04 07:49:02.133) Rztechmap.cpp:3046::process() Loop closure 86->28 rejected!
