### ISSUE TITLE
undefined reference to `cv::ocl::integral(cv::ocl::oclMat const&, cv::ocl::oclMat&)'

### ISSUE THREAD

**Issue by somebodyus** [introlab/rtabmap_ros#56]
an error occurs when building rtabmap_ros

/usr/local/lib/libopencv_nonfree.so.2.4: undefined reference to `cv::ocl::integral(cv::ocl::oclMat const&, cv::ocl::oclMat&)'

I am now using OpenCV 2.4.11 and the latest rtabmap built from source.

**Comment by matlabbe** [comment]
See this post: http://official-rtab-map-forum.67519.x6.nabble.com/catkin-make-ros-pkg-failed-tp22p24.html

**Comment by somebodyus** [comment]
Problem solved after updating the rtabmap_ros to the latest version.
