### ISSUE TITLE
rtabmap: Could not get transform from base_footprint to camera_depth_frame after 0.100000 second!

### ISSUE THREAD

**Issue by somebodyus** [introlab/rtabmap_ros#57]
[ WARN] [1458096517.558391078]: rtabmap: Could not get transform from base_footprint to camera_depth_frame after 0.100000 second!
[ERROR] [1458096517.558518276]: TF of received laser scan topic at time 1458096517.418607s is not set, aborting rtabmap update.

Note that I have written the static_transform_publisher in my launch file.
`<node pkg="tf" type="static_transform_publisher" name="base_footprint_xtion" args="0 0 0 0 0 0 1 /base_footprint /camera_rgb_optical_frame 100"/>`

I use the `Kinect + Odometry + Fake 2D laser from Kinect` configuration.

**Comment by somebodyus** [comment]
problem solved
please delete this thread

**Comment by stevemartinov** [comment]
How did you solve this?

**Comment by matlabbe** [comment]
You can debug tf tree with:
```
rosrun tf2_tools view_frames.py
```
to find which frames are missing or not connected to others.
