### ISSUE TITLE
Using URDF model in RTABMap

### ISSUE THREAD

**Issue by MrOCW** [introlab/rtabmap_ros#571]
Hi @matlabbe, I created a .urdf file for my robot car. How do I use it in rtabmap? Are there specific TF frames to add as I only have base_link, camera_link, and 4 wheel links. Read from the other forum that there should be a /map and /odom? Do I need to create these in the URDF file as well?
![tree](https://user-images.githubusercontent.com/67644448/114663511-094c0c00-9d2d-11eb-80f0-ab195e630292.jpg)

**Comment by MrOCW** [comment]
Apologies I have figured it out. Just had to change camera_link to base_link. Thanks!

**Comment by matlabbe** [comment]
`rtabmap.launch` uses `frame_id:=camera_link` by default (mostly for the hand-held camera mapping examples which all have camera_link as base frame), but `frame_id` should really be set to base frame of your robot, in your case `base_link`.
