### ISSUE TITLE
Much drift when stop and resume rtabmap

### ISSUE THREAD

**Issue by Clay-Cui** [introlab/rtabmap_ros#573]
Hi all,

I'm doing a VLP project using project tango (I know...it's old...but that's what the university asked...) and rtamap. The experiment process is basicly walking around to generate the map, and stop tango as well as rtabmap, take a picture to do the VLP algorithm, and then turn on tango again. When taking the picture, the phone remains still. What I assume is that rtabmap should remain unchanged or at least recognize where the phone is. But I had much drift or shift when resuming the rtabmap causing the result not usable at all.

Is there a way that can solve the problem? Make the rtabmap not moved when resuming?

Any hints will be greatly appreciated!

Thank you in advanced!

**Comment by matlabbe** [comment]
crossref: http://official-rtab-map-forum.67519.x6.nabble.com/Much-drift-when-stop-and-resume-rtabmap-td7824.html#a7891
