### ISSUE TITLE
the obstacle on the ground cannot be captured in grid map in demo_turtlebot_mapping demo

### ISSUE THREAD

**Issue by TouchDeeper** [introlab/rtabmap_ros#582]
Hello Mathieu,

I test the `demo_turtlebot_mapping` [demo](http://wiki.ros.org/rtabmap_ros/Tutorials/MappingAndNavigationOnTurtlebot) in gazebo. 

I found that an obstacle on the ground cannot be captured in the grid map, as the image below shows:
![Screenshot from 2021-05-14 17-34-01](https://user-images.githubusercontent.com/39310744/118252853-ce7bf600-b4db-11eb-8892-eb670543b4f1.png)

![Screenshot from 2021-05-14 17-43-30](https://user-images.githubusercontent.com/39310744/118253084-1569eb80-b4dc-11eb-8431-8a8bef0d14ea.png)

I tuned the `scan_height` of `depthimage_to_laserscan`, but it has no effect.

Could you please provide some advice? Thanks a lot.

**Comment by matlabbe** [comment]
To detect all objects over the ground in field of view of the camera, I would use `Grid/FromDepth=true`. For flat obstacles like that, the default ground plane segmentation may label it as ground. You could use `Grid/NormalsSegmentation=false` `Grid/MaxGoundHeight=0.05` if so.

**Comment by TouchDeeper** [comment]
@matlabbe 
Thanks for your reply.

I add these parameters to `rtabmap_ros`:
```
  <param name="Grid/3D" value="false"/>
  <param name="Grid/NormalsSegmentation" value="false"/>
  <param name="Grid/MaxGroundHeight" value="0.02"/>\
  <param name="Grid/RayTracing" value="true"/>
```

But it make no effect.

Is it relevant to the `depthimage _to_laserscan`?

**Comment by matlabbe** [comment]
Add also `<param name="Grid/FromDepth" value="true"/>` to `rtabmap` node.

**Comment by TouchDeeper** [comment]
@matlabbe 
Thanks for your reply. it works.
