### ISSUE TITLE
Include Issue after successfully compiling (VSCode)

### ISSUE THREAD

**Issue by Wangxz195** [introlab/rtabmap_ros#587]
![IncludeIssue](https://user-images.githubusercontent.com/82255186/119220395-a3e8f900-baea-11eb-8b17-469490f699a3.png)
![step2install](https://user-images.githubusercontent.com/82255186/119220396-a51a2600-baea-11eb-9729-1144c701cac1.png)
![step2make](https://user-images.githubusercontent.com/82255186/119220397-a5b2bc80-baea-11eb-9d32-101846f6ca8a.png)
![step3catkinmake](https://user-images.githubusercontent.com/82255186/119220398-a5b2bc80-baea-11eb-9590-efa0739e9810.png)

I followed the steps to install RTAB-Map standalone libraries and to install the RTAB-Map_ros package. Every step was successfullly done. However, when I use VSCode open the *.cpp files, there are still include errors detected. Could anyone please help me solve the problem? Thank you very much in advanced.

**Comment by matlabbe** [comment]
It is an error of vscode (indexing), not the compiler. You may have to tell vscode where are the includes. You may check the cmake plugin that can be installed in vscode, then use `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON` ([ref](https://stackoverflow.com/questions/36122358/visual-studio-code-c-include-path))

**Comment by Wangxz195** [comment]
@matlabbe Thank you very much for your hint. I have read the reference, and I have tried the solution mentioned while failing.  I am sorry for asking a stupid question: Where should I add this syntax? (Since I have no idea how is your code working and I am new to ubuntu&vscode...) Thank you again if you could help me with more details.

Best regards

**Comment by matlabbe** [comment]
I don't use VSCode often, but based on this page: https://code.visualstudio.com/docs/cpp/cmake-linux
You can download "CMake Tools" extension (click on the gear icon at the bottom left, then click on Extensions, or jsut do "ctrl-shift-x", then search for CMake Tools and install it).

If you do File->Open Folder, select rtabmap folder. At the bottom of the window (blue toolbar), you can execute CMake on Release mode, then do Build afterwards. On my computer, the includes were correctly found and autocompletion working already.
![Screenshot from 2021-05-23 18-10-08](https://user-images.githubusercontent.com/2319645/119278286-48a22e00-bbf2-11eb-9407-5b24d3d6142a.jpg)

For rtabmap_ros, you may download this extension: https://marketplace.visualstudio.com/items?itemName=ms-iot.vscode-ros, then open your `catkin_ws` folder in VSCode (as above, the includes and autocompletion should work):
![Screenshot from 2021-05-23 18-18-09](https://user-images.githubusercontent.com/2319645/119278469-7d62b500-bbf3-11eb-8759-2a62d10ecb1e.jpg)

**Comment by Wangxz195** [comment]
@matlabbe Thank you very much, your hints are really helpful. And I have solved my problem by following your hints.
Best reagrds.
