### ISSUE TITLE
Could you tell me the tf between Kinect and base_link in hand_held case?

### ISSUE THREAD

**Issue by somebodyus** [introlab/rtabmap_ros#59]
Could you tell me the tf between Kinect and base_link in hand_held case?

I am using:
`<node pkg="tf" type="static_transform_publisher" name="kinect_base_link" args="0 0 0 0 0 0 /base_link /camera_link 10"/>`

The built map is not vertical to the grid in RVIZ.

**Comment by matlabbe** [comment]
Which package do you use for the Kinect? normally, the TFs are already published (including optical rotation) with [openni_launch](http://wiki.ros.org/openni_launch) or [freenect_launch](http://wiki.ros.org/freenect_launch) with `/camera_link` as the kinect link. You could then set 

```
<node pkg="tf" type="static_transform_publisher" name="kinect_base_link" args="0 0 0 0 0 0 /base_link /camera_link"/>
```

**Comment by somebodyus** [comment]
Yes, I set the TF exactly as you mentioned, but the built map is not parallel with the horizontal.

**Comment by matlabbe** [comment]
The referential of the map is set as the first camera position. This means that if the camera is tilted, for example, according to the horizon, the whole map will be tilted.

**Comment by somebodyus** [comment]
Noted with thanks.
Is there any possibility to rectify the map pose? This is a critical problem because we need the projected 2-D occupancy map. If the whole map is tilted, we will get a useless projected map.

**Comment by matlabbe** [comment]
If it is on a robot and the camera is fixed with an angle, you can set TF between /base_link and /camera_link to include this angle. 

For hand-held mapping (where the camera can be arbitrary started with any angle), you could create a node detecting the ground plane, compute camera orientation/height then reset odometry at this pose (even reset rtabmap too to clear the map built so far).

**Comment by somebodyus** [comment]
OK. Thanks.
It seems that giving the camera on a ground plane at start is easier.
