### ISSUE TITLE
Missing <run_depend> on theora_image_transport

### ISSUE THREAD

**Issue by caioaamaral** [introlab/rtabmap_ros#599]
# Configuration
- **OS**: ubuntu 16.04 (docker container)
- **ROS DISTRO**: kinetic (**but I belive this affects all distros**)

# Description

Looking into rtabmap.launch file, the argument `rgb_image_transport`suggest that it does support `theora` compression.

https://github.com/introlab/rtabmap_ros/blob/eb6bc7ff5c4036bbdb2a0b63c7ab2aa7e54a084f/launch/rtabmap.launch#L84

Which is not the case, since the package does not define a dependency against `theora_image_transport`. Manifest only shows run dependencies for `compressed` and `compressedDepth`: 

https://github.com/introlab/rtabmap_ros/blob/b7a66e41f16ae6f450590ef6a2efd654970acd02/package.xml#L60

#

**Comment by matlabbe** [comment]
Yes, thx for the pull request, I will merge it.
