### ISSUE TITLE
Where does RTABMap accumulate data ?

### ISSUE THREAD

**Issue by adbidwai** [introlab/rtabmap_ros#603]
After running a simulation (Gazebo + RTABMap) for some time I noticed maybe around GBs of my free space has been reduced. 
I am aware that RTABMap stores the map in `.ros/rtabmap.db`. 
Apart from this, is there any other location where it might accumulating or adding up data, and will it be free to delete it?

TIA

**Comment by matlabbe** [comment]
ros save logs in `~/.ros` too, you may check if they grow fast. RTAB-Map saves only data in the database (default `~/.ros/rtabmap.db`)
