### ISSUE TITLE
Is there any possibility to use monocular vision?

### ISSUE THREAD

**Issue by somebodyus** [introlab/rtabmap_ros#61]
Is there any possibility to use monocular vision?
Could you give me an example launch file?

**Comment by matlabbe** [comment]
Monocular is not supported.

**Comment by matlabbe** [comment]
For Monocular SLAM, I recommend to look at these projects: [LSD-SLAM](https://github.com/tum-vision/lsd_slam) or [ORB-SLAM](https://github.com/raulmur/ORB_SLAM).
