### ISSUE TITLE
Is stereo mapping ported to ROS2 yet ? 

### ISSUE THREAD

**Issue by jediofgever** [introlab/rtabmap_ros#624]
Hi,
I have got an ZED stereo cam and would like to try out mapping. I see that you have ported RGBD and there is an example for that, however I don’t see stereo, are required executables for stereo ported ?

**Comment by matlabbe** [comment]
To do stereo ZED mapping, it is possible, look on this page instead: http://wiki.ros.org/rtabmap_ros/Tutorials/StereoHandHeldMapping
