### ISSUE TITLE
nabble forum is off

### ISSUE THREAD

**Issue by Mikor-mkr** [introlab/rtabmap_ros#631]
Hello, nabble forum seems off, is it going up  soon again?

**Comment by matlabbe** [comment]
Unfortunatly, nabble changed their server, the forum is now here: http://m.official-rtab-map-forum.206.s1.nabble.com/

See also the following address if you want to recover previous links: http://official-rtab-map-forum.206.s1.nabble.com/Forum-address-has-changed-how-fixing-old-reference-links-not-working-anymore-td8425.html

**Comment by Mikor-mkr** [comment]
Once again, thanks!
