### ISSUE TITLE
ROS2 Eloquent colcon build issue - rtabmap_ros

### ISSUE THREAD

**Issue by jed87** [introlab/rtabmap_ros#634]
Hi,

i am having difficulty installing for ROS2 Eloquent, Jetson Xavier NX Ubuntu 18.04.

1. fatal error: image_transport/image_transport.hpp: No such file or directory (Seems` like there isn't a .hpp file. only .h file.)

2. ros2_ws/src/rtabmap_ros/src/rviz/MapCloudDisplay.cpp:509:75: error: ‘rclcpp::FutureReturnCode’ has not been declared
    if (rclcpp::spin_until_future_complete(node, result_future) != rclcpp::FutureReturnCode::SUCCESS)

**Comment by matlabbe** [comment]
Hi, 
1. looks like this [commit](https://github.com/introlab/rtabmap_ros/commit/3452eed63d1402bb5b2d74259bcb872ab6682a26) has broken eloquent. 
2. `rclcpp::FutureReturnCode` has been [added](https://github.com/ros2/rclcpp/commit/df3c2ffa8a9d0b1b6f5cf707986accbc091575f9#diff-5560cc69598dae75afc60cfbb060f8f0a2a51be818d8f4bdb7cd38a6b69a71c5R33) on April 2020 (after eloquent)

Can you use Foxy instead? Eloquent is EOL as Foxy is LTS. As Foxy seems the most stable release yet of ROS2 (and also is LTS), I won't go back fixing older ROS2 distros.
