### ISSUE TITLE
Catkin_make error

### ISSUE THREAD

**Issue by Xulei346** [introlab/rtabmap_ros#637]
/usr/include/pcl-1.10/pcl/pcl_config.h:7:4: error: #error PCL requires C++14 or above

I try add set( CMAKE_CXX_FLAGS "-std=c++11 -msse -msse2 -msse3 -msse4 -msse4.1 -msse4.2" ) in CMakeLists.txt
but its not work. 
please help thanks :)

**Comment by matlabbe** [comment]
I fixed the problem, this is because I explicitly added c++11 for kinetic build, but at the same time on noetic PCL requires c++14. I removed that flag for noetic, see commit above
