### ISSUE TITLE
No map generating in rviz

### ISSUE THREAD

**Issue by pamico** [introlab/rtabmap_ros#64]
I have my fixed and reference frame set to odom and PointCloud2 topic set to /voxel_cloud and I do not see any output in rviz even though I am seeing a map being created in the rtabmap application. Any idea what I'm doing wrong? The only way I see any output from the kinect2 I'm using is when I switch my PointCloud2 topic to either kinect2/qhd/points or one of the other quality point clouds however when I do this it does not create a saved map.

Edit: So after a while of running it seems that I am getting a small amount of map data and that it requires a very long time to register and record points in the rtab map and only those few points are what it sends to rviz

**Comment by matlabbe** [comment]
Can you show your launch file or which ones are used? rtabmap binaries or built from source? In examples, `voxel_cloud` is an output and it is used only for visualization. 

You said "requires a very long time to register", can you show the terminal output of rtabmap to see processing time used by rtabmap node?

**Comment by matlabbe** [comment]
closed for inactivity
