### ISSUE TITLE
Misalignment of the map

### ISSUE THREAD

**Issue by zyh0333** [introlab/rtabmap_ros#661]
I am new to rtabmap...

My camera is Realsense L515, ros version is melodic. I follow the tutorial of "RGB-D Handheld Mapping", every time before I export the cloud file, I post-processing it, and export it as organized map with regeneration.
and I have the following issues:
![3rdfloor01](https://user-images.githubusercontent.com/90935306/137538786-413e5547-8bfd-4a5a-ad0f-2614dd564656.png)
I find this map is a little bit twisted...

![room corner00](https://user-images.githubusercontent.com/90935306/137538962-70d3c9dc-96c3-440f-baa0-adfbc2d9b8a8.png)
This one repeated the same thing for twice...

![wall00](https://user-images.githubusercontent.com/90935306/137539023-14952dd6-f9be-41bc-9072-44517a0d6150.png)
![wall_up_view01](https://user-images.githubusercontent.com/90935306/137539036-72d67c95-af8f-4acc-8382-e462cb2b0166.png)
This one seems better, but from the up view, there's three layers of walls (not a big deal compared with former two problems)

Every time I ran the rtabmap_ros with default commands same as http://wiki.ros.org/rtabmap_ros/Tutorials/HandHeldMapping
and I added some more arguments when launching:
```
roslaunch rtabmap_ros rtabmap.launch\
    rtabmap_args:="\
      --Icp/VoxelSize 0.05 \
      --Icp/PointToPlaneRadius 0 \
      --Icp/PointToPlaneK 20 \
      --Icp/CorrespondenceRatio 0.2 \
      --Icp/PMOutlierRatio 0.65 \
      --Icp/Epsilon 0.005 \
      --Icp/PointToPlaneMinComplexity 0 \
      --Odom/ScanKeyFrameThr 0.7 \
      --OdomF2M/ScanMaxSize 15000 \
      --Optimizer/GravitySigma 0.3 \
      --RGBD/NeighborLinkRefining true \
      --RGBD/LinearUpdate 0.01 \
      --RGBD/AngularUpdate 0.01 \
      --RGBD/ProximityBySpace true \
      --RGBD/ProximityByTime false \
      --Vis/MinInliers 12 \
      --RGBD/OptimizeFromGraphEnd false \
      --RGBD/OptimizeMaxError 4 \
      --Mem/STMSize 30 \
      --RGBD/LocalRadius 5\
      --Icp/CorrespondenceRatio 0.2 \
      --Icp/MaxCorrespondenceDistance 0.15 \
      --Reg/Strategy 1" \
```

there's also some other maps, I may also made same mistakes for these maps
![robot_arm00](https://user-images.githubusercontent.com/90935306/137539834-d7e8b014-2e54-472f-9bbc-1795aecb674f.png)
![add00](https://user-images.githubusercontent.com/90935306/137539853-e36ec2b8-92c2-4cff-9af7-7199418cfd6c.png)

**Comment by eliabntt** [comment]
the double wall problem is something I've seen too especially in simulation. It seems to get better if I set the rate of the camera from 30fps to 60ps which, however, is not always possible in the real world.
