### ISSUE TITLE
wrong localization 

### ISSUE THREAD

**Issue by smileyenot983** [introlab/rtabmap_ros#687]
Robot localizes itself with it's last coordinates before rtabmap was closed. 

What i want to do is the following:
1. launch rtabmap for creating the map with param localization=False, close rtabmap
2. change the robot's position while rtabmap is off. 
3. launch rtabmap for navigation with param localization = True. And here the problem occurs. Robot localizes itself at the same place where it was at the moment when i finished creating the map at step 1. 

Here is visualization of step 3 at rviz and gazebo:

In gazebo robot stays at the initial position(but that could be some other position, which is not the same as final position at step 1):

![msg217047166-38233](https://user-images.githubusercontent.com/54511486/144418727-3b7b3ca5-ecf5-468e-8e61-87d1e7d2c9bd.jpg)

In rviz(rectangle) it shows like the robot is at completely different position(position at which mapping was finished at step 1): 

![msg217047166-38234](https://user-images.githubusercontent.com/54511486/144418870-cd12965d-40a1-4fcb-86d6-9bc439b8e4fe.jpg)

**Comment by smileyenot983** [comment]
For some reason such behavior is only observed when parameter "Mem/IncrementalMemory" is set to false. In localization mode it is set to false by default. When i change it to true localization is done correctly.
Is that ok?

**Comment by matlabbe** [comment]
> In rviz(rectangle) it shows like the robot is at completely different position(position at which mapping was finished at step 1):

Yes, by default the robot thinks it is restarting from the last location where it shut down. See this parameter to change this behavior (if you want the robot to restart from origin of the map instead):

- Param: RGBD/StartAtOrigin = "false"                        [If true, rtabmap will assume the robot is starting from origin of the map. If false, rtabmap will assume the robot is restarting from the last saved localization pose from previous session (the place where it shut down previously). Used only in localization mode (Mem/IncrementalMemory=false).]

**Comment by smileyenot983** [comment]
> > In rviz(rectangle) it shows like the robot is at completely different position(position at which mapping was finished at step 1):
> 
> Yes, by default the robot thinks it is restarting from the last location where it shut down. See this parameter to change this behavior (if you want the robot to restart from origin of the map instead):
> 
>     * Param: RGBD/StartAtOrigin = "false"                        [If true, rtabmap will assume the robot is starting from origin of the map. If false, rtabmap will assume the robot is restarting from the last saved localization pose from previous session (the place where it shut down previously). Used only in localization mode (Mem/IncrementalMemory=false).]

Thanks for elaboration. Seems like the problem is solved.
