### ISSUE TITLE
Problem with OpenCV nonfree

### ISSUE THREAD

**Issue by NCharabaruk** [introlab/rtabmap_ros#69]
Hello,

I followed the installation instructions for the non-free OpenCV as I'd like to compare the results with different settings, yet I still get `[ WARN] (2016-04-15 13:40:12.441) Features2d.cpp:349::create() SURF/SIFT features cannot be used because OpenCV was not built with nonfree module. ORB is used instead.` Any idea why rtabmap is not finding the nonfree module?

**Comment by matlabbe** [comment]
See http://answers.ros.org/question/232015/problem-with-rtabmap_ros-and-nonfree-opencv/?answer=232030#post-id-232030

cheers

**Comment by NCharabaruk** [comment]
Yup, that did it. Thanks
