### ISSUE TITLE
Table is not visible in the gridmap during mapping

### ISSUE THREAD

**Issue by benoit-robotics** [introlab/rtabmap_ros#691]
I am using only a rgbd camera to map an environment. In the GIF, you can see the issue that I am experiencing : the table ( in white ) doesn't appear in the gridmap, nonetheless it's clearly visible in the rtabmap accumulated point cloud. The other obstacles, like the yellow chair, appear in the gridmap.
![resized](https://user-images.githubusercontent.com/41473839/145593134-20940e0a-cd8e-43d6-81b6-b512021e29b8.gif)

Here are the parameters that I use :

> 
>           <param name="RGBD/NeighborLinkRefining" type="string" value="true"/>
>           <param name="RGBD/ProximityBySpace"     type="string" value="true"/>
>           <param name="RGBD/AngularUpdate"        type="string" value="0.01"/>
>           <param name="RGBD/LinearUpdate"         type="string" value="0.01"/>
>           <param name="RGBD/OptimizeFromGraphEnd" type="string" value="false"/>
>           <param name="Grid/FromDepth"            type="string" value="true"/> 
>           <param name="Grid/RayTracing"            type="string" value="true"/>
>           <param name="Reg/Force3DoF"             type="string" value="true"/>
>           <param name="Reg/Strategy"              type="string" value="1"/> 

Is there a way to tweak the parameters of rtabmap to include the table in the gridmap ?

**Comment by matlabbe** [comment]
You may try this parameter:
```xml
<param name="Grid/MaxGroundHeight"            type="string" value="0.3"/> 
```
All flat surfaces over 30 cm will be considered obstacles.

**Comment by benoit-robotics** [comment]
Thank you. Is it 30 cm over the base frame ? If it's that, I am sure that the table is higher than that, but I will play with this parameter.

**Comment by matlabbe** [comment]
Yes it is over the base frame (`frame_id` parameter of rtabmap node) of the robot. I guessed that the table was easily over 30 cm.

**Comment by benoit-robotics** [comment]
This parameter doesn't seem to have any effect on my problem. Do you have any other input to give me ?

**Comment by matlabbe** [comment]
Can you share that database?

**Comment by benoit-robotics** [comment]
You can download the database here : https://drive.google.com/file/d/1g72_uYbzIOyOgh0THqQU6-1XQIjXE6Ce/view?usp=sharing . Cheers

**Comment by matlabbe** [comment]
Hi,

here are some options you have (starting from your current parameters):

1) Your current solution:
![Capture d’écran, le 2021-12-13 à 20 45 35](https://user-images.githubusercontent.com/2319645/145918061-78ae3b9d-6135-4d65-be54-f7b04788e8d9.png)

2) With `Grid/MaxGroundHeight=0.3`:
![Capture d’écran, le 2021-12-13 à 20 42 48](https://user-images.githubusercontent.com/2319645/145918135-30bab748-721c-4943-ad82-b89b8e7299b4.png)

3) With `Grid/MaxGroundHeight=0.3` and using `octomap_grid` topic:
![Capture d’écran, le 2021-12-13 à 20 43 00](https://user-images.githubusercontent.com/2319645/145918493-aa523138-6854-466b-bbef-28fb9211562f.png)

4) With `Grid/MaxGroundHeight=0.3` and `Grid/3D=False`:
![Capture d’écran, le 2021-12-13 à 20 39 35](https://user-images.githubusercontent.com/2319645/145918229-9cb47c68-bf2f-4590-90fe-f90896db7bf0.png)

5) With `Grid/MaxGroundHeight=0.3` and `Grid/RayTracing=False`:
![Capture d’écran, le 2021-12-13 à 20 46 32](https://user-images.githubusercontent.com/2319645/145918352-cb87f6b0-fab6-4ace-8691-03d7758f9747.png)

You can play with Grid parameters with rtabmap-databaseViewer, then do Edit->Regenerate local grids... to update the map. To show OctoMap result, make sure to check OctoMap checkbox under Gui Parameters -> Grid/Cloud Generation panel. "Show empty space" checkbox can be check or unchecked to better see obstacles or ray tracing. Check Grid checkbox under 3D View to show local grids, while pressing '2' key to show green/red segmentation.
![Enregistrement d’écran, le 2021-12-13 à 20 57 30](https://user-images.githubusercontent.com/2319645/145919186-32f70e04-7416-411f-8893-9b5c0596dfc3.gif)

**Comment by benoit-robotics** [comment]
Thank you a lot for your analysis, I can now fix my problem.

**Comment by snakehaihai** [comment]
HI
Im also not able to use the MaxGroundHeight parameter to detect the table seems whatever I change, It does not affect that's being show in gridmap. I`m still only able to see the table leg and not the projected table-top occupancy  

and also i have an additional issue in viewer

![20221107_020511](https://user-images.githubusercontent.com/6070995/200187427-f347741f-85cf-4d36-913a-d867b2155252.jpg)

can you help to address it? @matlabbe

**Comment by matlabbe** [comment]
Try `Edit->Regenerate local grids...`. I see Grid/3D parameter is set, it should recreate the grid in 3D. If there is nothing shown, maybe there is an issue with the sensor used.
