### ISSUE TITLE
librtabmap_ros.so: undefined reference to `rviz::OrbitViewController::onTargetFrameChanged(Ogre::Vector3 const&, Ogre::Quaternion const&)'

### ISSUE THREAD

**Issue by somebodyus** [introlab/rtabmap_ros#70]
I met an compilation error when building the 0.11.4 rtabmap_ros.
I am using the latest version rtabmap and Ubuntu 14.04.3 and ROS indigo.

Error:

`librtabmap_ros.so: undefined reference to rviz::OrbitViewController::onTargetFrameChanged(Ogre::Vector3 const&, Ogre::Quaternion const&)' `

**Comment by matlabbe** [comment]
Thx, that means that latest RVIZ has been just released. This commit should fix this: https://github.com/introlab/rtabmap_ros/commit/446026a5f47743fd63f9d99e3a80cbe3a346deb3

**Comment by somebodyus** [comment]
It works. Thank you for your solution.
