### ISSUE TITLE
local_grid_obstacle topic

### ISSUE THREAD

**Issue by muratkoc503** [introlab/rtabmap_ros#704]
@matlabbe , Hi,
/rtabmap/local_grid_obstacle topic does not publish anything. but /rtabmap/cloud_obstacles publish topic(observed rostopic echo). i dont understandt, what is reason. İ want to use /rtabmap/local_grid_obstacle for costmap parameter for local (dynamic) obstacle detection.
Thanks

**Comment by muratkoc503** [comment]
this reason probably `queue_size`. i increase this paramater value, obstacle is observed in local map.

**Comment by matlabbe** [comment]
In general, for the local costmap, I prefer sending directly a point cloud from the sensor to the costmap as the frame rate would be higher than rtabmap update rate.

**Comment by muratkoc503** [comment]
thanks. after, i try it hopefully. now, i use pointcloud_to_scan package. That is fast too.
