### ISSUE TITLE
rtabmap received signal SIGABRT only with rviz!

### ISSUE THREAD

**Issue by hichamhendy** [introlab/rtabmap_ros#711]
![rvitandrtabmap](https://user-images.githubusercontent.com/45830803/151515477-7b8576a7-a818-4e2e-83b3-b037878d3ced.png)

I am trying to launch rtabmap with RVIz but I can't. I really can't understand where the issue is! I must say it works fine with only  rtabmapviz! It's mainly related wit RVIZ. Bit I do use rviz for other purposes without problems!!

Here some parameters 

SUMMARY
========

CLEAR PARAMETERS
 * /points_xyzrgb/
 * /rtabmap/icp_odometry/
 * /rtabmap/rtabmap/

PARAMETERS
 * /points_xyzrgb/approx_sync: False
 * /points_xyzrgb/decimation: 4.0
 * /points_xyzrgb/voxel_size: 0.0
 * /rosdistro: melodic
 * /rosversion: 1.14.12
 * /rtabmap/icp_odometry/config_path: 
 * /rtabmap/icp_odometry/expected_update_rate: 0.0
 * /rtabmap/icp_odometry/frame_id: camera_link
 * /rtabmap/icp_odometry/ground_truth_base_frame_id: 
 * /rtabmap/icp_odometry/ground_truth_frame_id: 
 * /rtabmap/icp_odometry/guess_frame_id: 
 * /rtabmap/icp_odometry/guess_min_rotation: 0.0
 * /rtabmap/icp_odometry/guess_min_translation: 0.0
 * /rtabmap/icp_odometry/max_update_rate: 0.0
 * /rtabmap/icp_odometry/odom_frame_id: odom
 * /rtabmap/icp_odometry/publish_tf: True
 * /rtabmap/icp_odometry/queue_size: 10
 * /rtabmap/icp_odometry/scan_cloud_max_points: 0
 * /rtabmap/icp_odometry/wait_for_transform_duration: 0.2
 * /rtabmap/icp_odometry/wait_imu_to_init: True
 * /rtabmap/rtabmap/Mem/IncrementalMemory: true
 * /rtabmap/rtabmap/Mem/InitWMWithAllNodes: false
 * /rtabmap/rtabmap/approx_sync: False
 * /rtabmap/rtabmap/config_path: 
 * /rtabmap/rtabmap/database_path: ~/.ros/rtabmap.db
 * /rtabmap/rtabmap/frame_id: camera_link
 * /rtabmap/rtabmap/gen_depth: False
 * /rtabmap/rtabmap/gen_depth_decimation: 1
 * /rtabmap/rtabmap/gen_depth_fill_holes_error: 0.1
 * /rtabmap/rtabmap/gen_depth_fill_holes_size: 0
 * /rtabmap/rtabmap/gen_depth_fill_iterations: 1
 * /rtabmap/rtabmap/gen_scan: False
 * /rtabmap/rtabmap/ground_truth_base_frame_id: 
 * /rtabmap/rtabmap/ground_truth_frame_id: 
 * /rtabmap/rtabmap/landmark_angular_variance: 9999.0
 * /rtabmap/rtabmap/landmark_linear_variance: 0.0001
 * /rtabmap/rtabmap/map_frame_id: map
 * /rtabmap/rtabmap/odom_frame_id: 
 * /rtabmap/rtabmap/odom_frame_id_init: 
 * /rtabmap/rtabmap/odom_sensor_sync: False
 * /rtabmap/rtabmap/odom_tf_angular_variance: 0.001
 * /rtabmap/rtabmap/odom_tf_linear_variance: 0.001
 * /rtabmap/rtabmap/publish_tf: True
 * /rtabmap/rtabmap/queue_size: 10
 * /rtabmap/rtabmap/scan_cloud_max_points: 0
 * /rtabmap/rtabmap/subscribe_depth: True
 * /rtabmap/rtabmap/subscribe_odom_info: True
 * /rtabmap/rtabmap/subscribe_rgb: True
 * /rtabmap/rtabmap/subscribe_rgbd: False
 * /rtabmap/rtabmap/subscribe_scan: False
 * /rtabmap/rtabmap/subscribe_scan_cloud: True
 * /rtabmap/rtabmap/subscribe_scan_descriptor: False
 * /rtabmap/rtabmap/subscribe_stereo: False
 * /rtabmap/rtabmap/subscribe_user_data: False
 * /rtabmap/rtabmap/wait_for_transform_duration: 0.2

NODES
  /
    points_xyzrgb (nodelet/nodelet)
    rviz (rviz/rviz)
  /rtabmap/
    icp_odometry (rtabmap_ros/icp_odometry)
    rtabmap (rtabmap_ros/rtabmap)

ROS_MASTER_URI=http://localhost:11311

process[rtabmap/icp_odometry-1]: started with pid [10870]
process[rtabmap/rtabmap-2]: started with pid [10871]
process[rviz-3]: started with pid [10872]
process[points_xyzrgb-4]: started with pid [10873]
type is rtabmap_ros/point_cloud_xyzrgb
[ INFO] [1643359376.708105184]: Approximate time sync = false
^C[points_xyzrgb-4] killing on exit
[rviz-3] killing on exit
[rtabmap/icp_odometry-1] killing on exit
[rtabmap/rtabmap-2] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

By the way, I already rebuilt only rtabmap as suggested in this post https://github.com/introlab/rtabmap/issues/343#issuecomment-443476732 to solve this problem but nothing changes

I also installed PCl at the very beginning through this steps
`sudo apt install ros-noetic-rtabmap ros-noetic-rtabmap-ros
&& sudo apt remove ros-noetic-rtabmap ros-noetic-rtabmap-ros`

An insight in the cmake of rtabmap
shows the following 

...
-- PCL definitions don't contain "-march=native", make sure all libraries using Eigen are also compiled without that flag to avoid some segmentation faults (with gdb referring to some Eigen functions).
...
-- Info :
--   RTAB-Map Version =     0.20.17
--   CMAKE_VERSION =        3.10.2
--   CMAKE_INSTALL_PREFIX = /usr/local
--   CMAKE_BUILD_TYPE =     Release
--   CMAKE_INSTALL_LIBDIR = lib
--   BUILD_APP =            ON
--   BUILD_TOOLS =          ON
--   BUILD_EXAMPLES =       ON
--   BUILD_SHARED_LIBS =    ON
--   CMAKE_CXX_FLAGS =  -fmessage-length=0  -fopenmp -std=c++14
--   FLANN_KDTREE_MEM_OPT = OFF
--   PCL_DEFINITIONS =  ;-DDISABLE_ENSENSO;-DDISABLE_DAVIDSDK;-DDISABLE_DSSDK;-DDISABLE_PCAP;-DDISABLE_PNG;-DDISABLE_LIBUSB_1_0;-DFLANN_STATIC;-Dqh_QHpointer;-DDISABLE_RSSDK
--   PCL_VERSION = 1.8.1
....

the error 
[rtabmap/rtabmap-2] process has died [pid 15165, exit code -6, cmd /home/rnd/catkin_ws/devel/lib/rtabmap_ros/rtabmap --delete_db_on_start --Icp/VoxelSize 0.05 --Icp/PointToPlaneRadius 0 --Icp/PointToPlaneK 20 --Icp/CorrespondenceRatio 0.2 --Icp/PMOutlierRatio 0.65 --Icp/Epsilon 0.005 --Icp/PointToPlaneMinComplexity 0 --Odom/ScanKeyFrameThr 0.7 --OdomF2M/ScanMaxSize 15000 --Optimizer/GravitySigma 0.3 --RGBD/ProximityPathMaxNeighbors 1 --Reg/Strategy 1 rgb/image:=/camera/color/image_raw depth/image:=/camera/aligned_depth_to_color/image_raw rgb/camera_info:=/camera/color/camera_info rgbd_image:=rgbd_image_relay left/image_rect:=/stereo_camera/left/image_rect_color right/image_rect:=/stereo_camera/right/image_rect left/camera_info:=/stereo_camera/left/camera_info right/camera_info:=/stereo_camera/right/camera_info scan:=/scan scan_cloud:=/cloud scan_descriptor:=/scan_descriptor user_data:=/user_data user_data_async:=/user_data_async gps/fix:=/gps/fix tag_detections:=/tag_detections fiducial_transforms:=/fiducial_transforms odom:=odom imu:=/rtabmap/imu __name:=rtabmap __log:=/home/rnd/.ros/log/bf98d8fa-801f-11ec-96c1-709cd1531f15/rtabmap-rtabmap-2.log].
log file: /home/rnd/.ros/log/bf98d8fa-801f-11ec-96c1-709cd1531f15/rtabmap-rtabmap-2*.log
[roslaunch.pmon][INFO] 2022-01-28 10:51:45,477: ProcessMonitor.unregister[rtabmap/rtabmap-2] starting
[roslaunch.pmon][INFO] 2022-01-28 10:51:45,477: ProcessMonitor.unregister[rtabmap/rtabmap-2] complete
[roslaunch.pmon][INFO] 2022-01-28 10:51:47,558: ProcessMonitor.shutdown

[roslaunch-rnd-XMG-ULTRA-17-XUL17M20-15148.txt](https://github.com/introlab/rtabmap_ros/files/7957642/roslaunch-rnd-XMG-ULTRA-17-XUL17M20-15148.txt)

**Comment by matlabbe** [comment]
Can you type 'bt' in rtabmap gdb terminal?

**Comment by hichamhendy** [comment]
I unfortunately managed to solve the problem by using only the binaries in preference to the source.
