### ISSUE TITLE
how to connect map->odom tf ?

### ISSUE THREAD

**Issue by kdhRGT** [introlab/rtabmap_ros#721]
**my System**
```
ROS1 melodic.
ubuntu 18.04
sensor : rgb-d camera(d435) only
```

Hello author!

I can run rtapmap by your help.

but now I have a small problem.

I can run rtabmap by my rosbag dataset. but it said some errors.

**This is my command for rtabmap**

```
roslaunch rtabmap_ros rtabmap.launch launch_prefix:="xterm -e gdb -ex run --args" rviz:=true rtabmapviz:=false rgb_topic:=/camera/color/image_raw depth_registered_topic:=/camera/depth/image_raw camera_info_topic:=/camera/color/camera_info frame_id:=base_link rtabmap_args:="--delete_db_on_start" estimation:=1
```

**frame id setting in launch file**
```
<arg name="frame_id"                default="base_link"/>    
<arg name="odom_frame_id"           default="camera_color_optical_frame"/>               
<arg name="odom_frame_id_init"      default=""/>        
```

**firstly rtabmap said errors like this**

```
could not get transform from base_link to camera_color_optical_frame (stamp = ~~~) ~~~
```
![Screenshot from 2022-02-20 19-02-59](https://user-images.githubusercontent.com/99226572/154837838-550d1a10-9692-414e-a91a-7d329fcce85c.png)

**This is my tf free from rosbag**

[frames_rosbag.pdf](https://github.com/introlab/rtabmap_ros/files/8103731/frames_rosbag.pdf)

**So I found a similar issue on it**

https://answers.ros.org/question/224250/rtabmap_ros-with-realsense-odometry-could-not-get-transform-from-base_link-to-camera_color_optical_frame/

I followed a similar solution for my system.

**I added some commands on the launch file like this in rtabmap.launch**

```
<node pkg="tf" type="static_transform_publisher"  name="base_to_realsense"
      args="0 0 0 0 0 0 /base_link /camera_link 100" /> 
```

**so now my current tf tree is this**

[frames.pdf](https://github.com/introlab/rtabmap_ros/files/8103732/frames.pdf)
![Screenshot from 2022-02-20 19-09-18](https://user-images.githubusercontent.com/99226572/154837827-2b5b2d30-d2aa-4a15-acd8-957e74e6fee0.png)

but.. I don't know how can I connect map frame to odom.

I can watch the odometry results in odom frame in rviz.

**but map results don't show me anything.**

![Screenshot from 2022-02-20 18-52-56](https://user-images.githubusercontent.com/99226572/154837272-f69330c1-afcd-48cc-84cc-b8e488096603.png)

can you help me with how to connect odom frame with map frame?

thank you so much

best regards

**Comment by matlabbe** [comment]
If you do "enter" on gdb terminal of rtabmap to continue? If it is crashed, type "bt" in the gdb terminal to show the backtrace if so. Is rtabmap built from source or binaries?

**Comment by kdhRGT** [comment]
@matlabbe Thanks for replying to me.

now I am doing a source build~!

I put the "enter" on gdb terminal of rtabmap to continue.

and then it does not show me any errors.

But it shows an error when I play my rosbag file

odometry works very well but the mapping part does not work well.

Can you guess which I did a mistake?

Thank you so much for your help.

**Comment by matlabbe** [comment]
Right there you can type "bt" in gdb after the seg fault to see the full backtrace (from which function in rtabmap is happened). 

Is rtabmap built from source or binaries?

**Comment by kdhRGT** [comment]
Hello, author~!

My workspace is built from source~!

I also instated a binary program.

Sorry I think I misunderstand what you wanted because I was not friendly with gdb.

**Here, I attached what I had errors from gdb.**

![Screenshot from 2022-02-23 15-46-40](https://user-images.githubusercontent.com/99226572/155273953-76a07619-9350-4593-8b3c-2975b4fce180.png)

![Screenshot from 2022-02-23 15-50-18](https://user-images.githubusercontent.com/99226572/155273966-17ff7444-9779-49fb-b8f8-acb747b6641d.png)

![Screenshot from 2022-02-23 16-03-03](https://user-images.githubusercontent.com/99226572/155274288-1dc2f1bf-8426-4930-a2c0-436ac6584929.png)

The image resolution is very low so I am not sure that you can see it correctly or not

#0 in cv::Mat::copySize(cv::Mat const&)  () at /usr/lib/x86_64-linux...
#1 in  rtabmap::transform::transform(rtabmap::transform const&)
....

Are all these are errors? I am not sure that that is the reason why I attached a full picture of the error window.

**Comment by matlabbe** [comment]
Thank you, it is what I wanted. However, crashing in Transform constructor with cv::Mat may be related to which libraries are loaded on runtime, corrupting memory.

I suggest to uninstall rtabmap built from source and use the binaries one. You can do in rtabmap/build:
```bash
cd rtabmap/build
make
sudo make uninstall
```
This will remove rtabmap from /usr/local path. Remove afterwards rtabmap_ws from your `ROS_PACKAGE_PATH` (just don't source `/rtabmap_ws/devel/setup.bash`). 

for the binaries:
```bash
sudo apt install ros-melodic-rtabmap-ros
```

**Comment by kdhRGT** [comment]
@matlabbe

Thank you so much, sir.

I am successful to build the ROS workspace!!!!!!

i solved the problem by this process.

go to rtabmap/build folder

```
cd ~/rtabmap/build
make
sudo make uninstall
````

after that, uninstall the binaries.

```
sudo apt-get remove ros-melodic-rtabmap ros-melodic-rtabmap-ros
```

and install rtabmap again.

```
cd ~/rtabmap/build
sudo make install
```

and catkin_my_workspace


```
cd ~/rtabmap_ros
```

I should remove all folders about devel, build before building the workspace.

and it works!!!

I got some hints from your last answer.

Thank you so much

Best regards


![Screenshot from 2022-02-24 13-01-16](https://user-images.githubusercontent.com/99226572/155456097-38a82ea8-e388-40a3-bcd9-4b7c29688cf8.png)

**Comment by matlabbe** [comment]
If the rtabmap binaries were installed before building rtabmap_ros, rtabmap_ros could have been using headers from /usr/local instead of the binaries in /opt/ros, then on runtime the wrong version of rtabmap libraries were loaded causing the crash.

Glad that you've found a solution,
Mathieu
