### ISSUE TITLE
I'm using Ubuntu 18.04 ROS Melodic while installing RTAB-Map ros-pkg in your src folder of your Catkin workspace. I am getting this error

### ISSUE THREAD

**Issue by adarsha4** [introlab/rtabmap_ros#722]
####
-- Using CATKIN_DEVEL_PREFIX: /home/syncmaster/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/syncmaster/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 18 packages in topological order:
-- ~~  - turtlebot3 (metapackage)
-- ~~  - turtlebot3_autorace (metapackage)
-- ~~  - turtlebot3_autorace_control
-- ~~  - turtlebot3_autorace_core
-- ~~  - turtlebot3_msgs
-- ~~  - turtlebot3_navigation
-- ~~  - turtlebot3_simulations (metapackage)
-- ~~  - hls_lfcd_lds_driver
-- ~~  - turtlebot3_autorace_camera
-- ~~  - turtlebot3_autorace_detect
-- ~~  - turtlebot3_bringup
-- ~~  - turtlebot3_example
-- ~~  - turtlebot3_fake
-- ~~  - turtlebot3_gazebo
-- ~~  - turtlebot3_slam
-- ~~  - turtlebot3_teleop
-- ~~  - rtabmap_ros
-- ~~  - turtlebot3_description
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'turtlebot3'
-- ==> add_subdirectory(turtlebot3/turtlebot3)
-- +++ processing catkin metapackage: 'turtlebot3_autorace'
-- ==> add_subdirectory(turtlebot3_autorace/turtlebot3_autorace)
-- +++ processing catkin package: 'turtlebot3_autorace_control'
-- ==> add_subdirectory(turtlebot3_autorace/turtlebot3_autorace_control)
-- +++ processing catkin package: 'turtlebot3_autorace_core'
-- ==> add_subdirectory(turtlebot3_autorace/turtlebot3_autorace_core)
-- +++ processing catkin package: 'turtlebot3_msgs'
-- ==> add_subdirectory(turtlebot3_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- turtlebot3_msgs: 3 messages, 0 services
-- +++ processing catkin package: 'turtlebot3_navigation'
-- ==> add_subdirectory(turtlebot3/turtlebot3_navigation)
-- +++ processing catkin metapackage: 'turtlebot3_simulations'
-- ==> add_subdirectory(turtlebot3_simulations/turtlebot3_simulations)
-- +++ processing catkin package: 'hls_lfcd_lds_driver'
-- ==> add_subdirectory(hls_lfcd_lds_driver)
-- Boost version: 1.65.1
-- +++ processing catkin package: 'turtlebot3_autorace_camera'
-- ==> add_subdirectory(turtlebot3_autorace/turtlebot3_autorace_camera)
-- +++ processing catkin package: 'turtlebot3_autorace_detect'
-- ==> add_subdirectory(turtlebot3_autorace/turtlebot3_autorace_detect)
-- +++ processing catkin package: 'turtlebot3_bringup'
-- ==> add_subdirectory(turtlebot3/turtlebot3_bringup)
-- +++ processing catkin package: 'turtlebot3_example'
-- ==> add_subdirectory(turtlebot3/turtlebot3_example)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Generating .msg files for action turtlebot3_example/Turtlebot3 /home/syncmaster/catkin_ws/src/turtlebot3/turtlebot3_example/action/Turtlebot3.action
-- turtlebot3_example: 7 messages, 0 services
-- +++ processing catkin package: 'turtlebot3_fake'
-- ==> add_subdirectory(turtlebot3_simulations/turtlebot3_fake)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'turtlebot3_gazebo'
-- ==> add_subdirectory(turtlebot3_simulations/turtlebot3_gazebo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   signals
--   system
--   filesystem
--   program_options
--   regex
--   iostreams
--   date_time
--   chrono
--   atomic
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
-- Boost version: 1.65.1
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread;-lpthread (found suitable version "3.0.0", minimum required is "2.3.0") 
-- Config-file not installed for ZeroMQ -- checking for pkg-config
-- Checking for module 'libzmq >= 4'
--   Found libzmq , version 4.2.5
-- Checking for module 'uuid'
--   Found uuid, version 2.31.1
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 6.0.0
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- FreeImage.pc not found, we will search for FreeImage_INCLUDE_DIRS and FreeImage_LIBRARIES
-- Checking for module 'gts'
--   Found gts, version 0.7.6
-- Checking for module 'libswscale'
--   Found libswscale, version 4.8.100
-- Checking for module 'libavdevice >= 56.4.100'
--   Found libavdevice , version 57.10.100
-- Checking for module 'libavformat'
--   Found libavformat, version 57.83.100
-- Checking for module 'libavcodec'
--   Found libavcodec, version 57.107.100
-- Checking for module 'libavutil'
--   Found libavutil, version 55.78.100
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Checking for module 'yaml-0.1'
--   Found yaml-0.1, version 0.1.7
-- Checking for module 'libzip'
--   Found libzip, version 1.1.2
-- +++ processing catkin package: 'turtlebot3_slam'
-- ==> add_subdirectory(turtlebot3/turtlebot3_slam)
-- +++ processing catkin package: 'turtlebot3_teleop'
-- ==> add_subdirectory(turtlebot3/turtlebot3_teleop)
-- +++ processing catkin package: 'rtabmap_ros'
-- ==> add_subdirectory(rtabmap_ros)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Warning at rtabmap_ros/CMakeLists.txt:31 (find_package):
  By not providing "Findfiducial_msgs.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "fiducial_msgs", but CMake did not find one.

  Could not find a package configuration file provided by "fiducial_msgs"
  with any of the following names:

    fiducial_msgsConfig.cmake
    fiducial_msgs-config.cmake

  Add the installation prefix of "fiducial_msgs" to CMAKE_PREFIX_PATH or set
  "fiducial_msgs_DIR" to a directory containing one of the above files.  If
  "fiducial_msgs" provides a separate development package or SDK, be sure it
  has been installed.

-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- RTABMAP_SYNC_MULTI_RGBD = OFF
-- RTABMAP_SYNC_USER_DATA  = OFF
-- rtabmap_ros: 18 messages, 16 services
-- WITH octomap_msgs
-- WITH apriltag_ros
-- WITH find_object_2d
-- WITH rviz
-- WITH costmap_2d
-- +++ processing catkin package: 'turtlebot3_description'
-- ==> add_subdirectory(turtlebot3/turtlebot3_description)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/syncmaster/catkin_ws/build
####
####
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target _turtlebot3_msgs_generate_messages_check_deps_Sound
[  0%] Built target _turtlebot3_msgs_generate_messages_check_deps_SensorState
[  0%] Built target _turtlebot3_msgs_generate_messages_check_deps_VersionInfo
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target roscpp_generate_messages_py
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target turtlebot3_autorace_camera_gencfg
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target diagnostic_msgs_generate_messages_py
[  1%] Built target turtlebot3_autorace_detect_gencfg
[  1%] Built target diagnostic_msgs_generate_messages_cpp
[  1%] Built target diagnostic_msgs_generate_messages_eus
[  1%] Built target diagnostic_msgs_generate_messages_nodejs
[  1%] Built target diagnostic_msgs_generate_messages_lisp
[  1%] Built target _turtlebot3_example_generate_messages_check_deps_Turtlebot3Action
[  1%] Built target _turtlebot3_example_generate_messages_check_deps_Turtlebot3ActionGoal
[  1%] Built target _turtlebot3_example_generate_messages_check_deps_Turtlebot3ActionResult
[  1%] Built target _turtlebot3_example_generate_messages_check_deps_Turtlebot3Goal
[  1%] Built target actionlib_msgs_generate_messages_eus
[  1%] Built target _turtlebot3_example_generate_messages_check_deps_Turtlebot3ActionFeedback
[  1%] Built target _turtlebot3_example_generate_messages_check_deps_Turtlebot3Feedback
[  1%] Built target actionlib_msgs_generate_messages_nodejs
[  1%] Built target actionlib_msgs_generate_messages_py
[  1%] Built target actionlib_msgs_generate_messages_lisp
[  1%] Built target _turtlebot3_example_generate_messages_check_deps_Turtlebot3Result
[  1%] Built target nav_msgs_generate_messages_py
[  1%] Built target actionlib_msgs_generate_messages_cpp
[  1%] Built target tf_generate_messages_py
[  1%] Built target tf2_msgs_generate_messages_cpp
[  1%] Built target tf_generate_messages_cpp
[  1%] Built target tf_generate_messages_eus
[  1%] Built target tf2_msgs_generate_messages_eus
[  1%] Built target tf_generate_messages_lisp
[  1%] Built target nav_msgs_generate_messages_lisp
[  1%] Built target actionlib_generate_messages_eus
[  1%] Built target tf_generate_messages_nodejs
[  1%] Built target tf2_msgs_generate_messages_nodejs
[  1%] Built target actionlib_generate_messages_cpp
[  1%] Built target actionlib_generate_messages_lisp
[  1%] Built target actionlib_generate_messages_nodejs
[  1%] Built target actionlib_generate_messages_py
[  1%] Built target nav_msgs_generate_messages_eus
[  1%] Built target tf2_msgs_generate_messages_lisp
[  1%] Built target tf2_msgs_generate_messages_py
[  1%] Built target nav_msgs_generate_messages_cpp
[  1%] Built target nav_msgs_generate_messages_nodejs
[  1%] Built target trajectory_msgs_generate_messages_nodejs
[  1%] Built target dynamic_reconfigure_generate_messages_eus
[  1%] Built target dynamic_reconfigure_generate_messages_lisp
[  1%] Built target dynamic_reconfigure_generate_messages_cpp
[  1%] Built target dynamic_reconfigure_generate_messages_py
[  1%] Built target dynamic_reconfigure_generate_messages_nodejs
[  1%] Built target std_srvs_generate_messages_py
[  1%] Built target dynamic_reconfigure_gencfg
[  1%] Built target std_srvs_generate_messages_lisp
[  1%] Built target std_srvs_generate_messages_eus
[  1%] Built target std_srvs_generate_messages_cpp
[  1%] Built target std_srvs_generate_messages_nodejs
[  1%] Built target gazebo_msgs_generate_messages_cpp
[  1%] Built target gazebo_msgs_generate_messages_eus
[  1%] Built target gazebo_msgs_generate_messages_lisp
[  1%] Built target trajectory_msgs_generate_messages_py
[  1%] Built target gazebo_msgs_generate_messages_nodejs
[  1%] Built target trajectory_msgs_generate_messages_lisp
[  1%] Built target trajectory_msgs_generate_messages_cpp
[  1%] Built target gazebo_msgs_generate_messages_py
[  1%] Built target gazebo_ros_gencfg
[  1%] Built target trajectory_msgs_generate_messages_eus
[  1%] Built target flat_world_imu_node
[  1%] Built target rtabmap_costmap_plugins2
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_Point3f
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_Point2f
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_GetNodeData
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_Link
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_GetPlan
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_UserData
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_ScanDescriptor
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_SetLabel
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_EnvSensor
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_GetMap2
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_Goal
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_LoadDatabase
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_GlobalDescriptor
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_PublishMap
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_AddLink
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_GetNodesInRadius
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_NodeData
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_RGBDImages
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_GetMap
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_Path
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_MapData
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_KeyPoint
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_OdomInfo
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_DetectMoreLoopClosures
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_GlobalBundleAdjustment
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_ListLabels
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_Info
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_GPS
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_SetGoal
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_ResetPose
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_MapGraph
[  1%] Built target _rtabmap_ros_generate_messages_check_deps_RemoveLabel
[  2%] Built target rtabmap_ros_gencfg
[  2%] Built target _rtabmap_ros_generate_messages_check_deps_RGBDImage
[  2%] Built target _rtabmap_ros_generate_messages_check_deps_CleanupLocalGrids
[  3%] Built target rtabmap_point_cloud_aggregator
[  3%] Built target rtabmap_point_cloud_assembler
[  3%] Built target rtabmap_rgb_sync
[  4%] Built target rtabmap_stereo_sync
[  5%] Built target rtabmap_rgbdx_sync
[  6%] Built target rtabmap_rgbd_sync
[  7%] Built target rtabmap_icp_odometry
[  8%] Built target rtabmap_rgbd_odometry
[  9%] Built target rtabmap
[ 10%] Built target rtabmap_costmap_voxel_markers
[ 10%] Built target rtabmap_stereo_odometry
[ 10%] Built target rtabmap_rgbdicp_odometry
[ 11%] Built target rtabmap_costmap_plugins
[ 12%] Built target rtabmap_pointcloud_to_depthimage
[ 12%] Built target rtabmap_rgbd_relay
[ 13%] Built target turtlebot3_msgs_generate_messages_eus
[ 13%] Built target turtlebot3_description_xacro_generated_to_devel_space_
[ 13%] Built target rtabmap_imu_to_tf
[ 15%] Built target turtlebot3_msgs_generate_messages_py
[ 15%] Built target turtlebot3_msgs_generate_messages_nodejs
[ 16%] Built target turtlebot3_msgs_generate_messages_cpp
[ 17%] Built target turtlebot3_msgs_generate_messages_lisp
[ 17%] Built target hlds_laser_segment_publisher
[ 19%] Built target turtlebot3_example_generate_messages_eus
[ 20%] Built target hlds_laser_publisher
[ 22%] Built target turtlebot3_example_generate_messages_py
[ 24%] Built target turtlebot3_example_generate_messages_nodejs
[ 26%] Built target turtlebot3_example_generate_messages_lisp
[ 28%] Built target turtlebot3_example_generate_messages_cpp
[ 29%] Built target turtlebot3_fake_node
[ 49%] Built target rtabmap_ros_generate_messages_nodejs
[ 49%] Built target turtlebot3_drive
[ 49%] Built target rtabmap_ros_generate_messages_py
[ 58%] Built target rtabmap_ros_generate_messages_lisp
[ 69%] Built target rtabmap_ros_generate_messages_eus
[ 78%] Built target rtabmap_ros_generate_messages_cpp
[ 78%] Built target turtlebot3_msgs_generate_messages
[ 79%] Built target turtlebot3_diagnostics
[ 79%] Built target turtlebot3_example_generate_messages
[ 79%] Built target rtabmap_ros_generate_messages
[ 79%] Built target rtabmap_camera
[ 80%] Built target rtabmap_ros
[ 80%] Built target rtabmap_data_player
[ 81%] Built target rtabmap_external_loop_detectionexample
[ 82%] Built target rtabmap_stereo_camera
[ 86%] Built target rtabmap_rviz_plugins
[ 86%] Built target rtabmap_map_optimizer
[ 86%] Built target rtabmap_save_objects_example
[ 87%] Built target rtabmap_map_assembler
[ 88%] Built target rtabmap_odom_msg_to_tf
[ 88%] Built target rtabmap_wifi_signal_pub
[ 88%] Building CXX object rtabmap_ros/CMakeFiles/rtabmap_sync.dir/src/CoreWrapper.cpp.o
[ 89%] Built target rtabmap_wifi_signal_sub
[ 95%] Built target rtabmap_plugins
/home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp: In member function ‘void rtabmap_ros::CoreWrapper::commonDepthCallbackImpl(const string&, const UserDataConstPtr&, const std::vector<boost::shared_ptr<const cv_bridge::CvImage> >&, const std::vector<boost::shared_ptr<const cv_bridge::CvImage> >&, const std::vector<sensor_msgs::CameraInfo_<std::allocator<void> > >&, const LaserScan&, const PointCloud2&, const OdomInfoConstPtr&, const std::vector<rtabmap_ros::GlobalDescriptor_<std::allocator<void> > >&, const std::vector<std::vector<rtabmap_ros::KeyPoint_<std::allocator<void> > > >&, const std::vector<std::vector<rtabmap_ros::Point3f_<std::allocator<void> > > >&, const std::vector<cv::Mat>&)’:
/home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp:1426:27: error: no matching function for call to ‘rtabmap_ros::CoreWrapper::process(ros::Time&, rtabmap::SensorData&, rtabmap::Transform&, const string&, cv::Mat&, rtabmap::OdometryInfo&, double)’
    timerConversion.ticks());
                           ^
In file included from /home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp:28:0:
/home/syncmaster/catkin_ws/src/rtabmap_ros/include/rtabmap_ros/CoreWrapper.h:194:7: note: candidate: void rtabmap_ros::CoreWrapper::process(const ros::Time&, rtabmap::SensorData&, const rtabmap::Transform&, const std::vector<float>&, const string&, const cv::Mat&, const rtabmap::OdometryInfo&, double)
  void process(
       ^~~~~~~
/home/syncmaster/catkin_ws/src/rtabmap_ros/include/rtabmap_ros/CoreWrapper.h:194:7: note:   no known conversion for argument 4 from ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const std::vector<float>&’
/home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp: In member function ‘virtual void rtabmap_ros::CoreWrapper::commonStereoCallback(const OdometryConstPtr&, const UserDataConstPtr&, const CvImageConstPtr&, const CvImageConstPtr&, const CameraInfo&, const CameraInfo&, const LaserScan&, const PointCloud2&, const OdomInfoConstPtr&, const std::vector<rtabmap_ros::GlobalDescriptor_<std::allocator<void> > >&, const std::vector<rtabmap_ros::KeyPoint_<std::allocator<void> > >&, const std::vector<rtabmap_ros::Point3f_<std::allocator<void> > >&, const cv::Mat&)’:
/home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp:1674:27: error: no matching function for call to ‘rtabmap_ros::CoreWrapper::process(ros::Time&, rtabmap::SensorData&, rtabmap::Transform&, std::__cxx11::string&, cv::Mat&, rtabmap::OdometryInfo&, double)’
    timerConversion.ticks());
                           ^
In file included from /home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp:28:0:
/home/syncmaster/catkin_ws/src/rtabmap_ros/include/rtabmap_ros/CoreWrapper.h:194:7: note: candidate: void rtabmap_ros::CoreWrapper::process(const ros::Time&, rtabmap::SensorData&, const rtabmap::Transform&, const std::vector<float>&, const string&, const cv::Mat&, const rtabmap::OdometryInfo&, double)
  void process(
       ^~~~~~~
/home/syncmaster/catkin_ws/src/rtabmap_ros/include/rtabmap_ros/CoreWrapper.h:194:7: note:   no known conversion for argument 4 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘const std::vector<float>&’
/home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp: In member function ‘virtual void rtabmap_ros::CoreWrapper::commonLaserScanCallback(const OdometryConstPtr&, const UserDataConstPtr&, const LaserScan&, const PointCloud2&, const OdomInfoConstPtr&, const GlobalDescriptor&)’:
/home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp:1809:27: error: no matching function for call to ‘rtabmap_ros::CoreWrapper::process(ros::Time&, rtabmap::SensorData&, rtabmap::Transform&, std::__cxx11::string&, cv::Mat&, rtabmap::OdometryInfo&, double)’
    timerConversion.ticks());
                           ^
In file included from /home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp:28:0:
/home/syncmaster/catkin_ws/src/rtabmap_ros/include/rtabmap_ros/CoreWrapper.h:194:7: note: candidate: void rtabmap_ros::CoreWrapper::process(const ros::Time&, rtabmap::SensorData&, const rtabmap::Transform&, const std::vector<float>&, const string&, const cv::Mat&, const rtabmap::OdometryInfo&, double)
  void process(
       ^~~~~~~
/home/syncmaster/catkin_ws/src/rtabmap_ros/include/rtabmap_ros/CoreWrapper.h:194:7: note:   no known conversion for argument 4 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘const std::vector<float>&’
/home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp: In member function ‘virtual void rtabmap_ros::CoreWrapper::commonOdomCallback(const OdometryConstPtr&, const UserDataConstPtr&, const OdomInfoConstPtr&)’:
/home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp:1867:27: error: no matching function for call to ‘rtabmap_ros::CoreWrapper::process(ros::Time&, rtabmap::SensorData&, rtabmap::Transform&, std::__cxx11::string&, cv::Mat&, rtabmap::OdometryInfo&, double)’
    timerConversion.ticks());
                           ^
In file included from /home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp:28:0:
/home/syncmaster/catkin_ws/src/rtabmap_ros/include/rtabmap_ros/CoreWrapper.h:194:7: note: candidate: void rtabmap_ros::CoreWrapper::process(const ros::Time&, rtabmap::SensorData&, const rtabmap::Transform&, const std::vector<float>&, const string&, const cv::Mat&, const rtabmap::OdometryInfo&, double)
  void process(
       ^~~~~~~
/home/syncmaster/catkin_ws/src/rtabmap_ros/include/rtabmap_ros/CoreWrapper.h:194:7: note:   no known conversion for argument 4 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘const std::vector<float>&’
/home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp: At global scope:
/home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp:1872:6: error: prototype for ‘void rtabmap_ros::CoreWrapper::process(const ros::Time&, rtabmap::SensorData&, const rtabmap::Transform&, const string&, const cv::Mat&, const rtabmap::OdometryInfo&, double)’ does not match any in class ‘rtabmap_ros::CoreWrapper’
 void CoreWrapper::process(
      ^~~~~~~~~~~
In file included from /home/syncmaster/catkin_ws/src/rtabmap_ros/src/CoreWrapper.cpp:28:0:
/home/syncmaster/catkin_ws/src/rtabmap_ros/include/rtabmap_ros/CoreWrapper.h:194:7: error: candidate is: void rtabmap_ros::CoreWrapper::process(const ros::Time&, rtabmap::SensorData&, const rtabmap::Transform&, const std::vector<float>&, const string&, const cv::Mat&, const rtabmap::OdometryInfo&, double)
  void process(
       ^~~~~~~
rtabmap_ros/CMakeFiles/rtabmap_sync.dir/build.make:254: recipe for target 'rtabmap_ros/CMakeFiles/rtabmap_sync.dir/src/CoreWrapper.cpp.o' failed
make[2]: *** [rtabmap_ros/CMakeFiles/rtabmap_sync.dir/src/CoreWrapper.cpp.o] Error 1
CMakeFiles/Makefile2:8546: recipe for target 'rtabmap_ros/CMakeFiles/rtabmap_sync.dir/all' failed
make[1]: *** [rtabmap_ros/CMakeFiles/rtabmap_sync.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4" failed

**Comment by matlabbe** [comment]
Sorry for this issue, it was a wrong commit yesterday, it should be fixed by https://github.com/introlab/rtabmap_ros/commit/8570fe3179fb7434863706a6b03b59dae440aad0

**Comment by adarsha4** [comment]
Thank you so much. Now it is working
