### ISSUE TITLE
test stereo_outdoor_mapping with other bag file

### ISSUE THREAD

**Issue by kimhwichang** [introlab/rtabmap_ros#724]
I want to test performance of rtabmap_ros with other bag file, not demo bagfile.
In the bag file, topic of stereo image and camera info is as below

left_image : nerian_left/image_color
left_camera_info : nerian_left/camera_info
right_image : nerian_right/image_color
right_camera : nerian_right/camera_info

![image](https://user-images.githubusercontent.com/45867799/155728701-9153f190-e89a-4ef4-856b-83d3379effb8.png)

I just modified demo_stereo_outdoor.launch file as below

<launch>   

   
   <arg name="rviz" default="true" />
   <arg name="rtabmapviz" default="false" />
   <arg name="local_bundle" default="true" />
   <arg name="stereo_sync" default="false" />
    
   <param name="use_sim_time" type="bool" value="True"/>
   
     
   
   <node pkg="stereo_image_proc" type="stereo_image_proc" name="stereo_image_proc" output="screen">
      
      <remap from="left/image_raw"    to="nerian_left/image_color"/>
      <remap from="right/image_raw"   to="nerian_right/image_color"/>
      <remap from="left/camera_info"  to="nerian_left/camera_info"/>      
      <remap from="right/camera_info" to="nerian_right/camera_info"/>
      <param name="disparity_range" value="128"/>
   </node>
   
   <node if="$(arg stereo_sync)" pkg="nodelet" type="nodelet" name="stereo_sync" args="standalone rtabmap_ros/stereo_sync">
   <remap from="left/image_rect"   to="nerian_left/image_color"/>
   <remap from="right/image_rect"   to="nerian_right/image_color"/>
   <remap from="left/camera_info"   to="nerian_left/camera_info"/>
   <remap from="right/camera_info"   to="nerian_right/camera_info"/>
   </node>
   
            
   <group ns="rtabmap">   
   
         
      <node pkg="rtabmap_ros" type="stereo_odometry" name="stereo_odometry" output="screen">
         <remap from="left/image_rect"       to="/left/image_rect"/>
         <remap from="right/image_rect"      to="/right/image_rect"/>
         <remap from="left/camera_info"      to="/nerian_left/camera_info"/>
         <remap from="right/camera_info"     to="/nerian_right/camera_info"/>
         <remap from="rgbd_image"            to="/stereo_camera/rgbd_image"/>
         <remap from="odom"                  to="/stereo_odometry"/>

         <param name="subscribe_rgbd"  type="bool" value="$(arg stereo_sync)"/>
         <param name="frame_id"        type="string" value="base_footprint"/>
         <param name="odom_frame_id"   type="string" value="odom"/>

         <param name="Odom/Strategy"      type="string" value="0"/> 
         <param name="Vis/EstimationType" type="string" value="1"/> 
         <param name="Vis/MaxDepth"       type="string" value="0"/>
         <param name="Odom/GuessMotion" type="string" value="true"/>
         <param name="Vis/MinInliers"     type="string" value="10"/>
         <param unless="$(arg local_bundle)" name="OdomF2M/BundleAdjustment" type="string" value="0"/>
         <param name="OdomF2M/MaxSize"    type="string" value="1000"/> 
         <param name="GFTT/MinDistance"   type="string" value="10"/>
         <param name="GFTT/QualityLevel"  type="string" value="0.00001"/> 
         <param name="GFTT/QualityLevel"  type="string" value="0.00001"/>
      </node>
   
      
      <node name="rtabmap" pkg="rtabmap_ros" type="rtabmap" output="screen" args="--delete_db_on_start">
         <param name="frame_id"         type="string" value="base_footprint"/>
         <param unless="$(arg stereo_sync)" name="subscribe_stereo" type="bool" value="true"/>
         <param name="subscribe_depth"  type="bool" value="false"/>
         <param name="subscribe_rgbd"      type="bool" value="$(arg stereo_sync)"/>

         <remap from="left/image_rect"       to="/left/image_rect"/>
         <remap from="right/image_rect"      to="/right/image_rect"/>
         <remap from="left/camera_info"      to="/nerian_left/camera_info"/>
         <remap from="right/camera_info"     to="/nerian_right/camera_info"/>
         <remap from="rgbd_image"        to="/stereo_camera/rgbd_image"/>

         <remap from="odom" to="/stereo_odometry"/>

         <param name="queue_size" type="int" value="30"/>
         <param name="map_negative_poses_ignored" type="bool" value="true"/>

         
         <param name="Rtabmap/TimeThr"                   type="string" value="700"/>
         <param name="Grid/DepthDecimation"              type="string" value="4"/>
         <param name="Grid/FlatObstacleDetected"         type="string" value="true"/>
         <param name="Kp/MaxDepth"                       type="string" value="0"/>
         <param name="Kp/DetectorStrategy"               type="string" value="6"/>  
         <param name="Vis/EstimationType"                type="string" value="1"/>   
         <param name="Vis/MaxDepth"                      type="string" value="0"/>
         <param name="RGBD/CreateOccupancyGrid"          type="string" value="true"/>       
      </node>
      
      
      <node if="$(arg rtabmapviz)" pkg="rtabmap_ros" type="rtabmapviz" name="rtabmapviz" args="-d $(find rtabmap_ros)/launch/config/rgbd_gui.ini" output="screen">
         <param unless="$(arg stereo_sync)" name="subscribe_stereo"    type="bool" value="true"/>
         <param name="subscribe_odom_info" type="bool" value="true"/>
         <param name="subscribe_rgbd"      type="bool" value="$(arg stereo_sync)"/>
         <param name="queue_size"          type="int" value="10"/>
         <param name="frame_id"            type="string" value="base_footprint"/>
         
         <remap from="left/image_rect"       to="left/image_rect"/>
         <remap from="right/image_rect"      to="right/image_rect"/>
         <remap from="left/camera_info"      to="nerian_left/camera_info"/>
         <remap from="right/camera_info"     to="nerian_right/camera_info"/>
         <remap from="rgbd_image"        to="/stereo_camera/rgbd_image"/>
         <remap from="odom_info"         to="odom_info"/>
         <remap from="odom"              to="/stereo_odometry"/>
         <remap from="mapData"           to="mapData"/>
      </node>
         
   </group>
  
    
   <node if="$(arg rviz)" pkg="rviz" type="rviz" name="rviz" args="-d $(find rtabmap_ros)/launch/config/demo_stereo_outdoor.rviz"/>

</launch>

However, when i rolaunch this launch file with bag file , the following error occurred.

[ WARN] [1645798400.662309044, 1581791683.708373921]: odometry: Could not get transform from base_footprint to nerian_left (stamp=1581791683.491196) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)! Error="canTransform: target_frame base_footprint does not exist. canTransform: source_frame nerian_left does not exist.. canTransform returned after 0.100901 timeout was 0.1."

How can i solve this problem?
I'm beginner in this research field, so I don't know which part is wrong and which part should be changed further.
Could anyone please elaborate on how to solve the current problem or what to do if I want to use a different bag file?

**Comment by matlabbe** [comment]
On the robot, we had a TF tree from base_footprint to camera frames. If you don't have a TF tree, change `frame_id` to frame set in your left camera topic (here `nerian_left`).
