### ISSUE TITLE
add IPC to rtabmap_ros

### ISSUE THREAD

**Issue by felrock** [introlab/rtabmap_ros#742]
Are there any plans to add support for IPC in the nodes in rtabmap_ros, this would reduce the amount of copying that needs to be done. 

[link_about_ipc](https://design.ros2.org/articles/intraprocess_communications.html)

**Comment by matlabbe** [comment]
I would expect that this is already the case, accordingly to all conditions stated in the link you shared. I don't think the developper has to explicitly set a publisher using shared memory or serialization, this would be done by ros api under the hood if it detects that our publisher is linked to a subscribed in same process. Similarly to nodelets in ROS1, the ros API was able to switch between those modes depending on the connections. However I am not enough expert in ROS2 to know all the subtleties, I was expecting that ROS2 by default behave like nodelets. So depending on how you launch the nodes, you may compose some in same process and other in different processes.

I checked fast the documentation and I've found this https://docs.ros.org/en/foxy/Tutorials/Intra-Process-Communication.html with corresponding code here: https://github.com/ros2/demos/tree/foxy/intra_process_demo

It seems that without having to modify existing nodes, it is possible to make a new node including others to use the shared memory.
