### ISSUE TITLE
error: temporary of non-literal type  in a constant expression

### ISSUE THREAD

**Issue by Zhaogaog** [introlab/rtabmap_ros#746]
Does anyboby knows these errors when i execute this command 'make -j6'in the terminal?Desparate for help!
![命令](https://user-images.githubusercontent.com/103256521/162426563-13807c0c-9cf8-4fdf-8472-654b46910700.png)

![g2o报错](https://user-images.githubusercontent.com/103256521/162426395-993c1522-8e0e-4472-aeb1-12eb70730e0c.png)

**Comment by matlabbe** [comment]
Latest melodic build with g2o binaries working: https://github.com/introlab/rtabmap/actions/runs/3555309659/jobs/5971928057
