### ISSUE TITLE
How to turn down logging?

### ISSUE THREAD

**Issue by catmanjan** [introlab/rtabmap_ros#752]
I'm using rtabmap_ros and the INFO logs are very annoying, it makes it impossible to see whats going on when my terminal is full of unuseful odom messages

How can I make these messages not appear?

**Comment by matlabbe** [comment]
If you are using a launch file, remove `output="screen"` option from the odometry node. If you are using `rtabmap.launch`, there is an argument `output` (default screen), set it to `log`.

**Comment by catmanjan** [comment]
Perfect, thanks
