### ISSUE TITLE
No mapData

### ISSUE THREAD

**Issue by krishnraj** [introlab/rtabmap_ros#76]
I played the bagfile stereo outdoorA but it doesn't show any data on the topic /rtabmap/mapData. It says 
WARNING: no messages received and simulated time is active.
Is /clock being published?

Please help.

**Comment by matlabbe** [comment]
When playing a bag file with TF included, you should play it as this:
```bash
$ roscore
$ rosparam set use_sim_time true
$ rosbag play --clock stereo_outdoorA.bag
```

In the [Stereo Mapping tutorial](http://wiki.ros.org/rtabmap_ros/Tutorials/StereoOutdoorMapping), parameter `use_sim_time` is set in the launch file.

The topic `/rtabmap/mapData` will be published by `rtabmap` node using the tutorial launch file. The bag contains only left/right images and TF.

cheers
