### ISSUE TITLE
Robot constantly jumps back and forth with localization=true and EKF

### ISSUE THREAD

**Issue by MrOCW** [introlab/rtabmap_ros#760]
![image](https://user-images.githubusercontent.com/67644448/169031216-5b361306-82fa-4ccf-ad0d-0f578f434cf1.png)
Hi,
I ran rtabmap in localization mode using rgbd odometry (D455). I then fused rtabmap/odom with imu and lidar pose in an ekf node. ekf odom0 relative is set to true. However, my robot constantly jumps back and forth during navigation between visual odometry and the ekf's odometry. I set publish_tf_map and publish_tf_odom to false but the jump is still there.  In the image, the jump is between the 2 circles

**Comment by matlabbe** [comment]
To debug this, you may have t show also the TF tree (`rosrun tf2_tools view_frames.py`) to make sure tf from rtabmap and visual odometry nodes are disabled. 

If you are fusing rtabmap's visual odometry with imu and lidar, if the output of EKF filter smooth? If not, you may have to override the covariance of your input odometries to filter the jumps.

For rtabmap's localization, it will always jump at each localization, it is like a GPS.
