### ISSUE TITLE
TUM RGBD dataset on rtabmap_ros showing blank screen

### ISSUE THREAD

**Issue by AbhiKhoyani** [introlab/rtabmap_ros#770]
Hii Mathieu,

I was following rgbdslam_datasets.launch for loading TUM RGBD dataset and followed all the steps mentioned initially in that file and your other responses in issue also but I'm not getting any frames in rviz and rtabmapviz. 
Using this launch file: https://github.com/introlab/rtabmap_ros/blob/master/launch/tests/rgbdslam_datasets.launch

Here, I've uploaded the snapshot of rviz.
![image](https://user-images.githubusercontent.com/64613041/173253368-1591a418-40fa-4856-8883-4b19627f5a53.png)

My environment is I'm running Linux on WSL, with ros noetic, python3 and for GUI using Xserver launch.
I tried demo_robot_mapping.launch with demo_mapping.bag and it's working perfectly in rviz as well as rtabmapviz so I'm sure there must not be environment problem. For TUM, I tried it on both of the below file with compressed and decompressed, with and without python renamed world->kinect to world->kinect_gt but no luck.
$ wget http://vision.in.tum.de/rgbd/dataset/freiburg3/rgbd_dataset_freiburg3_long_office_household.bag
$ wget https://vision.in.tum.de/rgbd/dataset/freiburg1/rgbd_dataset_freiburg1_xyz.bag

any hint/help is appreciated.   
-Abhi

**Comment by matlabbe** [comment]
I don't know about WSL, but on native ubuntu just re-did the instructions in https://github.com/introlab/rtabmap_ros/blob/master/launch/tests/rgbdslam_datasets.launch and it works as expected:
![Screenshot from 2022-10-09 15-05-51](https://user-images.githubusercontent.com/2319645/194781733-9843c65d-d09e-4314-aa1e-8975fc93285d.png)

**Comment by SYLJSTK** [comment]
I have the same situation with you. Have you solved it?

**Comment by wz8530** [comment]
Hi, @matlabbe, I have the same problem.
I use this [rgbdslam_datesets.launch](https://github.com/introlab/rtabmap_ros/blob/0.20.23-melodic/launch/tests/rgbdslam_datasets.launch).
![rtab_rgdbslam_1](https://user-images.githubusercontent.com/59405417/235089223-75fb85f7-d493-4636-be43-63db2e8f9de6.png)

I can confirm that the subscription topic was successful.. Do you have any suggestions to solve this problem?

**Comment by matlabbe** [comment]
Are you on noetic or melodic?

On noetic, it seems working following those [instructions](https://github.com/introlab/rtabmap_ros/blob/0bd2190f77a5be191b1cebd438dea4c61d960c99/rtabmap_examples/launch/rgbdslam_datasets.launch#L5-L12):
![Screenshot from 2023-04-30 13-54-57](https://user-images.githubusercontent.com/2319645/235375797-ef23dbca-73bf-4314-ad80-faffb7273806.png)

**Comment by wz8530** [comment]
> Are you on noetic or melodic?
> 
> On noetic, it seems working following those [instructions](https://github.com/introlab/rtabmap_ros/blob/0bd2190f77a5be191b1cebd438dea4c61d960c99/rtabmap_examples/launch/rgbdslam_datasets.launch#L5-L12): ![Screenshot from 2023-04-30 13-54-57](https://user-images.githubusercontent.com/2319645/235375797-ef23dbca-73bf-4314-ad80-faffb7273806.png)

Hi, @matlabbe , I'm sorry for replying so late. I installed `ros-melodic` on my computer. After restarting the computer, it seems to be working normally, which is very strange.
![rtab-rgbdslam_2](https://user-images.githubusercontent.com/59405417/236125046-c8f959ba-afb8-4224-9de9-f4aa89b0adc0.png)
