### ISSUE TITLE
Velodyne VLP16 ground segmentation

### ISSUE THREAD

**Issue by felrock** [introlab/rtabmap_ros#801]
Hello, I was wondering if there is any setting for segmenting ground. I've tried setting **Grid/GroundIsObstacle: "true"** but i get a super noisy map. Could be because the ground is not completly flat. What are the parameters that I can tweak for this? Thanks in advance

**Comment by matlabbe** [comment]
For VLP16, it depends on the normal computation parameters. You may try this parameter `Icp/PointToPlaneGroundNormalsUp=0.9` to make sure points on ground have normals up. This will help approach `Grid/NormalsSegmentation=true` to correctly segment the ground. You may also increase `Grid/CellSize` and `Grid/ClusterRadius` parameters.

For convenience, as it takes long to restart the stack every time you want to change a parameter, I recommend to use `rtabmap-databaseViewer` to regenerate local grids (see Edit menu) based on the parameters set in the UI (see Core Parameters view -> Grid). So change a parameter in Core Parameters view, click on Edit->Regenerate local grid and see how it looks in 3D Map view (check Grid and Map checkboxes). You can also press keypad "2" to show ground (green) and obstacle (red) points segmented.

If the velodyne is always parallel to ground, you may set `Grid/NormalsSegmentation` to false to use a passthrough filtering approach, while adjusting `Grid/MaxGroundHeight`
