### ISSUE TITLE
Noise and points in the air in PLY files generated from rtabmapviz

### ISSUE THREAD

**Issue by kosmonauta144** [introlab/rtabmap_ros#805]
Hi Everyone!

My setup
ROS Noetic
RTABMAP_ROS installed from binaries
Sensor: Azure Kinect
Topics subscribed /rgb_to_depth/image_raw + camera info
/depth/image_raw + camera info
/points2

Everything works fine with mapping, but in exported .ply files I have a "noise" or "points in the air". Points are more and more dense closer to the sensor and it makes them difficult to filter in post-processing so I would like to find a cause of this.

Here is the exported .ply with points in the air which has the same color as obstacle in the background behind them
![image](https://user-images.githubusercontent.com/52200790/188632498-a0db4da6-4427-4371-a977-db7d4a93ac17.png)

Here are the yelow points which I suppose are the same "air points" but in rtabmapviz
![image](https://user-images.githubusercontent.com/52200790/188635365-f3e23ea3-c803-4382-a456-34f20fa2bf1c.png)

and with different background color to show the black dots in the air
![image](https://user-images.githubusercontent.com/52200790/188638530-4724dc56-9a66-4aef-803c-29df8fa59d40.png)

I don't know if I should use some specific filter in rtabmap.ini file or change the topics. I thought that I will deal with it by _scan_cloud_  but it didn't help. 

I will be more than thankfull for every idea how to improve the final pointcloud.

UPDATE:
is RTABMAP generate the pointcloud from /voxel_cloud topic? because voxel_cloud is messed by the colored data from the visual odometry

![image](https://user-images.githubusercontent.com/52200790/188840887-b8775c34-8001-431e-a65e-0737542d9d17.png)

**Comment by kosmonauta144** [comment]
alright,

it appeared that in kinect_azure ros launcher (https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/melodic/launch/slam_rtabmap.launch) which I use, has to nedelets for rectifying rgb and depth image and the rectified depth image was extremely noised. After removing the nodelets, everything works great as expected, so I will close the issue as an issue with launcher from different package

**Comment by matlabbe** [comment]
For Kinect Azure under ROS, I've made a pull request long time ago: https://github.com/microsoft/Azure_Kinect_ROS_Driver/pull/166
You may check this out.

**Comment by kosmonauta144** [comment]
> For Kinect Azure under ROS, I've made a pull request long time ago: [microsoft/Azure_Kinect_ROS_Driver#166](https://github.com/microsoft/Azure_Kinect_ROS_Driver/pull/166) You may check this out.
> 
> > Updated depth rectification interpolation method to NearestNeighbor instead of Linear. This avoids a lot of noisy points in the 3D point cloud. This would also fix [microsoft/Azure_Kinect_ROS_Driver#103](https://github.com/microsoft/Azure_Kinect_ROS_Driver/issues/103) at the same time.

Thank You very much for your reply!

I've taken a closer look and your commit works very well. Noise is gone.

Although I have a question, because I observe strange think and I am trying to understand.
![image](https://user-images.githubusercontent.com/52200790/189104296-e15aa12e-050e-45ba-8f30-a8b3d840198a.png)

In rtabmapviz and rviz also, the /rgb/image_rect is disturbed a little bit in the centre. I noticed it while looking at the edge of the image. I noticed also that if I am not using image_proc/rectify, the /rgb/image_raw is perfectly rectangular. @matlabbe do you know the reason why is the disturbance occur? Also do you know whether it does not affect the map?
