### ISSUE TITLE
Using Localization with other SLAM algorithm with rtabmap_ros

### ISSUE THREAD

**Issue by tugbakara** [introlab/rtabmap_ros#808]
Which SLAM algorithms are compatible with RTABMAP_ROS package? mcptam, rgbdslam  etc...?

**Comment by matlabbe** [comment]
No SLAM algorithms are compatible with RTAB-Map, only visual [intertial] odometry algorithms are. For a SLAM approach to be compatible with RTAB-Map, you would have to disable their back-end (loop closure detection),and  just use their front-end (odometry).

As an example, we integrated ORB_SLAM2 and ORB_SLAM3 inside RTAB-Map (https://github.com/introlab/rtabmap/blob/master/corelib/src/odometry/OdometryORBSLAM.cpp), but we only use their visual odometry approach (loop closure detection, global bundle adjustment, re-localization are all disabled).

**Comment by tugbakara** [comment]
Thanks @matlabbe ! Have a nice day :)
