### ISSUE TITLE
Setting subscribe_scan to true makes RTAB Map Visualizer display nothing

### ISSUE THREAD

**Issue by brianzhan** [introlab/rtabmap_ros#81]
I am hoping to set subscribe_scan to true because I am working in a flat environment (so z-axis wouldn't change)

When I try setting the subscribe_scan parameter in the rgbd_mapping.launch file to true, and then run roslaunch rtabmap_ros rgbd_mapping.launch rtabmap_args:="--delete_db_on_start", the RTAB-Map interface only shows the xyz (in red green blue axis) with a black background instead of what the camera sees. The nodes that are subscribed to   (/camera/rgb/image_rect_color,  /camera/depth_registered/image_raw,  /camera/rgb/camera_info, /rtabmap/odom), are still outputting data.

**Comment by matlabbe** [comment]
Hi,

When you set `subscribe_scan` to true, `rtabmap` [will subscribe to a laser scan topic](https://github.com/introlab/rtabmap_ros/blob/8391a21e75af94a3920d709d1cd9cc95ba7db6a9/launch/rgbd_mapping.launch#L65). If no laser scans are published, the map will not be updated/published. The messages you see may come from `rgbd_odometry` node, which doesn't need the laser scan.

If you want to constraint odometry/mapping to 3DoF, use these arguments (assuming you have rtabmap 0.11):
```bash
$ roslaunch rtabmap_ros rgbd_mapping.launch rtabmap_args:="--Optimizer/Slam2D true --Reg/Force3DoF true"
```

cheers
