### ISSUE TITLE
Make rtabmap_ros_INSTALL_PREFIX relative to current install directory 

### ISSUE THREAD

**Issue by lucasw** [introlab/rtabmap_ros#813]
In the install generated file install/share/rtabmap_ros/cmake/rtabmap_rosConfig.cmake there are hard-coded absolute paths to the install directory of the build system:

```
set(rtabmap_ros_INSTALL_PREFIX /home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws/install)
set(rtabmap_ros_PREFIX ${rtabmap_ros_INSTALL_PREFIX})
...

if(NOT "include;/home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws/install/lib/rtabmap-0.20/../../include/rtabmap-0.20;/usr/include/opencv4 " STREQUAL " ")
  set(rtabmap_ros_INCLUDE_DIRS "")
...
```

(and a few more)

If these could be made to only refer to `install/` then it would be possible to build in one location, zip up the whole of `install/` and use it on another system- in this case this github action https://github.com/lucasw/ros_from_src/blob/core/.github/workflows/ubuntu_22_04.yml with the deploy target being a different github action that doesn't want to rebuild rtabmap every build.

I can solve this for now with a search and replace sed command on the deploy target, or by creating the same /home/runner/work/ros_from_src... path and extracting into that

```
sed -i "s@/home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws@`pwd`@" install/share/rtabmap_ros/cmake/rtabmap_rosConfig.cmake
```

but I suspect with a little digging the cmake commands that generated the above could be modified to fix that, have the generated file use CMAKE_CURRENT_LIST_DIR or similar.

**Comment by matlabbe** [comment]
Those absolute paths are populated from upstream `rtabmap` library. I opened an issue on rtabmap repo: https://github.com/introlab/rtabmap/issues/903
