### ISSUE TITLE
Error while trying to launch rtab mapping launch

### ISSUE THREAD

**Issue by abdulahad01** [introlab/rtabmap_ros#823]
I was following the official RTAB_ROS tutorial [here](http://wiki.ros.org/rtabmap_ros/Tutorials/SetupOnYourRobot) on a gazebo simulation [here](https://github.com/abdulahad01/ROS_differential_drive_robot) and ran into this issue.

```
/opt/ros/noetic/lib/rtabmap_ros/rtabmap: error while loading shared libraries: libavcodec-ffmpeg.so.56: cannot open shared object file: No such file or directory
type is rtabmap_ros/rgbd_sync

```

I've rechecked and updated my OpenCV and RTAB installations but the issue persists. Can someone guide me to a proper solution?
Thanks

**Comment by matlabbe** [comment]
Is `libavcodec-ffmpeg.so` exist on the system? If no, try re-installing it.
