### ISSUE TITLE
Change rtabmap parameters while nodes are running

### ISSUE THREAD

**Issue by csvicbot-7** [introlab/rtabmap_ros#832]
Hi,
I have a mobile robot that has a robotic arm attached to the base. We need the following parameters to change dynamically according to the arm movement, these parameters are:
Grid/FootprintHeight
Grid/FootprintLength
Grid/FootprintWidth
Is there any way to change the values of these parameters while the rtabmap ros nodes are running?
Thank you.

**Comment by matlabbe** [comment]
You can change them with rosparam, then when all parameters are changed, call `update_parameters` service:
```bash
rosparam set /rtabmap/rtabmap/Grid/FootprintHeight 1
rosparam set /rtabmap/rtabmap/Grid/FootprintLength 0.6
rosparam set /rtabmap/rtabmap/Grid/FootprintWidth 0.4
rosservice call /rtabmap/update_parameters
```
