### ISSUE TITLE
rtabmap: Did not receive data since 5 seconds

### ISSUE THREAD

**Issue by cate1717** [introlab/rtabmap_ros#837]
Hi everyone, thanks for sharing this project.
I am new in rtabmap and ros2.

ubuntu and ros version: 20.04 and ros2 foxy
rtabmap and rtabmpa_ros branches: foxy-devel 

I am working with only an OS-0 128 ouster 3D lidar.

these are my launch lines:
`ros2 launch rtabmap_ros rtabmap.launch.py \
    rtabmap_args:="--delete_db_on_start" \
    frame_id:=laser_sensor_frame \
    subscribe_scan_cloud:=true scan_cloud_topic:=/points \
    imu_topic:=/imu \
    approx_sync:=true \
    qos:=2 \
    rviz:=true\
    visual_odometry:=false \
`

these are my warnings:

> [rtabmap-1] [WARN] [1667916138.691786750] [rtabmap.rtabmap]: rtabmap: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10). 
[rtabmap-1] rtabmap subscribed to (approx sync):
[rtabmap-1]    /rtabmap/odom \
[rtabmap-1]    /camera/rgb/image_rect_color \
[rtabmap-1]    /camera/depth_registered/image_raw \
[rtabmap-1]    /camera/rgb/camera_info \
[rtabmap-1]    /points

this is my rqt_graph, in which points and imu are connected:
![image](https://user-images.githubusercontent.com/116339844/200592805-e7fc665e-4992-4118-9a5a-b0bb17587586.png)

this my frames graph:
![image](https://user-images.githubusercontent.com/116339844/200592993-efce3424-82b2-4473-9cb2-a515c6a31360.png)

my topics /points and /imu are published, at 10Hz and 100Hz (from ros2 topic hz tool)

nothing is shown on rviz and is only told that the fram 'map' does not exist

I ve already seen that there are many issue like this, but I can't find a solution. (already tried to increase 'queue_size' and 'approx_sync' to true/false)

also: should I install and use ROS1 to be able to use "test_ouster_gen2.launch"  or can I get the same some results with the launch file for ros2?

thanks in advance!

**Comment by matlabbe** [comment]
I don't have examples in ROS2 for ouster, onlyhttps://github.com/introlab/rtabmap_ros/blob/master/launch/tests/test_ouster_gen2.launch for ros1. I don't have access to an ouster anymore, so it will be difficult for me to port the example on ROS2 in the short term...
