### ISSUE TITLE
first and last stamps in the scan are the same, ouster lidar launch file

### ISSUE THREAD

**Issue by cate1717** [introlab/rtabmap_ros#841]
Hi everyone, thanks for sharing this project.
I am new in rtabmap and ros.
ubuntu and ros version: 20.04 and ros noetic
I am working with only an OS-0 128 ouster 3D lidar.

I have these errors when launching test_ouster_gen2.launch file
![image](https://user-images.githubusercontent.com/116339844/201683461-c5353abd-e022-4e62-805c-180cf6062765.png)

these are my param in the launch file:

![image](https://user-images.githubusercontent.com/116339844/201683843-ff8fc388-6d46-4625-9323-be41bceeff46.png)

these are my graphes:
![image](https://user-images.githubusercontent.com/116339844/201684146-db747026-4875-48bc-955c-321e4ce9954d.png)
![image](https://user-images.githubusercontent.com/116339844/201684253-8a176878-c10a-428c-ac9e-60f29e8a7a9e.png)

Has anyone any suggestion? thanks a lot in advance!

**Comment by matlabbe** [comment]
`os_sensor_stabilized`frame should be published by imu filter here:
https://github.com/introlab/rtabmap_ros/blob/42947061893f4769dbd08c1cdb0d887b33a8a3a6/launch/tests/test_ouster_gen2.launch#L64-L78

Did you have errors at the beggining telling that one of this node has not been found?  e.g.:
```
sudo apt install ros-noetic-imu-filter-madgwick
```
