### ISSUE TITLE
Using my own bag data

### ISSUE THREAD

**Issue by takahiko-hasegawa-hdjp** [introlab/rtabmap_ros#843]
I'm using noetic version of rtabmap and trying to configure the launch file (topic names for now) to match the rosbag data that I have. 

However, with my own custom bag data there is always the same error and seems like i cannot mitigate the error.

**/rtabmap/rtabmap: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set. If topics are coming from different computers, make sure the clocks of the computers are synchronized ("ntpdate"). If topics are not published at the same rate, you could increase "queue_size" parameter (current=10).
/rtabmap/rtabmap subscribed to (approx sync): **

It seems like the code is trying to use approximate sync to sync the rgb depth and camera info but it looks like the callback is not called.

here is my launch file 

<launch>

  
  
  

  
  <arg name="rviz" default="false" />
  <arg name="rtabmapviz" default="true" /> 
  
  <param name="use_sim_time" type="bool" value="True"/>
  
  
  <arg name="localization"      default="false"/>
  <arg     if="$(arg localization)" name="rtabmap_args"  default=""/>
  <arg unless="$(arg localization)" name="rtabmap_args"  default="--delete_db_on_start"/>

  <group ns="rtabmap">
    
    
    <node name="rtabmap" pkg="rtabmap_ros" type="rtabmap" output="screen" args="$(arg rtabmap_args)">
	  <param name="frame_id"           type="string" value="base_footprint"/>
	  <param name="wait_for_transform" type="bool" value="false"/>
	
	  <param name="subscribe_depth" type="bool" value="true"/>
	  <param name="subscribe_scan"  type="bool" value="false"/>
	
	  
	  <param name="odom_frame_id"            type="string" value="odom"/>
	  <param name="odom_tf_linear_variance"  type="double" value="0.001"/>
	  <param name="odom_tf_angular_variance" type="double" value="0.001"/>

	  <remap from="scan" to="/jn0/base_scan"/>

	  <remap from="rgb/image"       to="/zed_front/rgb"/>
  	<remap from="depth/image"     to="/zed_front/depth"/>
  	<remap from="rgb/camera_info" to="/camera_info"/>
  	
	  <param name="rgb/image_transport"   type="string" value="raw"/>
	  <param name="depth/image_transport" type="string" value="raw"/>

	  
	  <param name="RGBD/NeighborLinkRefining" type="string" value="true"/>  
	  <param name="RGBD/ProximityBySpace"     type="string" value="true"/>  
	  <param name="RGBD/ProximityByTime"      type="string" value="false"/> 
	  <param name="RGBD/ProximityPathMaxNeighbors" type="string" value="10"/> 
	  <param name="Reg/Strategy"              type="string" value="1"/>     
	  <param name="Vis/MinInliers"        type="string" value="12"/>   
	  <param name="RGBD/OptimizeFromGraphEnd" type="string" value="false"/> 
	  <param name="RGBD/OptimizeMaxError"     type="string" value="4"/>	    
	  <param name="Reg/Force3DoF"             type="string" value="true"/>  
	  <param name="Grid/FromDepth"            type="string" value="false"/> 
	  <param name="Mem/STMSize"               type="string" value="30"/>    
	  <param name="RGBD/LocalRadius"          type="string" value="5"/>     
	  <param name="Icp/CorrespondenceRatio"   type="string" value="0.2"/>   
	  <param name="Icp/PM"                    type="string" value="false"/>
	  <param name="Icp/PointToPlane"          type="string" value="false"/>
	  <param name="Icp/MaxCorrespondenceDistance"  type="string" value="0.15"/>
	  <param name="Icp/VoxelSize"             type="string" value="0.05"/>
	  
	  
	  <param     if="$(arg localization)" name="Mem/IncrementalMemory" type="string" value="false"/>
	  <param unless="$(arg localization)" name="Mem/IncrementalMemory" type="string" value="true"/>
	  <param name="Mem/InitWMWithAllNodes" type="string" value="$(arg localization)"/>
   </node>
    
    
    <node if="$(arg rtabmapviz)" pkg="rtabmap_ros" type="rtabmapviz" name="rtabmapviz" args="-d $(find rtabmap_ros)/launch/config/rgbd_gui.ini" output="screen">
  	  <param name="subscribe_depth"    type="bool" value="true"/>
      <param name="subscribe_scan"     type="bool" value="true"/>
      <param name="frame_id"           type="string" value="base_footprint"/>
      <param name="wait_for_transform" type="bool" value="true"/>

      
      
      
    </node>
  </group>
  
  
  <node if="$(arg rviz)" pkg="rviz" type="rviz" name="rviz" args="-d $(find rtabmap_ros)/launch/config/demo_robot_mapping.rviz" output="screen"/>
   <node pkg="nodelet" type="nodelet" name="points_xyzrgb" args="standalone rtabmap_ros/point_cloud_xyzrgb">
    
    
    
    
    <param name="queue_size" type="int" value="10"/>
    <param name="voxel_size" type="double" value="0.01"/>
  </node>

    
  
  

</launch>

**Comment by matlabbe** [comment]
For me, this looks wrong (I would expect `camera_info` topic to have zed prefix too):
```xml
<remap from="rgb/image"       to="/zed_front/rgb"/>
<remap from="depth/image"     to="/zed_front/depth"/>
<remap from="rgb/camera_info" to="/camera_info"/>
```
1. Make sure they are all published at the same rate:
```
rostopic hz /zed_front/rgb /zed_front/depth /camera_info
```
2. As `camera_info` is not formatted like the others, how is it generated? with same timestamp? Normally with ZED, `approx_sync` could be false.

**Comment by takahiko-hasegawa-hdjp** [comment]
Thanks for your advice! The problem was actually with the topic not having the correct timestamp hence the callback function not being called as they were not synced properly


Thanks!
