### ISSUE TITLE
Rtabmap-ros not working as rtabmap with visual odometry.

### ISSUE THREAD

**Issue by brayanpa** [introlab/rtabmap_ros#853]
Hi @matlabbe, I continue testing rtabmap and rgbd_odometry on ROS Galactic. I have odometry working correctly thanks to your feedback at https://github.com/introlab/rtabmap_ros/issues/851 . But I don't get a good result when mapping. I think it's because when I turn off the IR emitter, the depth image becomes very bad as shown the images below.

IR Emitter ON             |  IR Emitter OFF
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/92322014/207702529-a0975d33-19de-48dd-a7e9-cc68f6ae61b7.png)  |  ![image](https://user-images.githubusercontent.com/92322014/207702434-f97f2fc9-8d35-410e-b904-6084a71d961e.png)

On the other hand, if I launch rtabmap without ROS and configure the sensor driver as shown in the following image.

![image](https://user-images.githubusercontent.com/92322014/207687278-3296a573-d6d3-470d-a449-ddf5f8e2a972.png)

Keeping all the default configurations, odometry and rtabmap work perfectly. Even though the realsense has the IR emitter active.

If you could answer some questions I would really appreciate it.

What is the difference between odometry with ROS and without ROS? 
Why does it affect so much to enable the IR emitter in ROS and without ROS it does not affect?
How can I configure rtabmap-ros to work as well as rtabmap?

**Comment by matlabbe** [comment]
How did you launch with ros? Did you try this one? https://github.com/introlab/rtabmap_ros/blob/ros2/launch/ros2/realsense_d435i_infra.launch.py
```
ros2 launch realsense2_camera rs_launch.py enable_gyro:=true enable_accel:=true unite_imu_method:=1 enable_infra1:=true enable_infra2:=true enable_sync:=true

ros2 param set /camera/camera depth_module.emitter_enabled 0

ros2 launch rtabmap_ros realsense_d435i_infra.launch.py
```

The standalone uses RGB + Depth as default, it is why you don't need to disable the emitter. However, even with the standalone, I prefer using IR-Depth mode with IR emitter off:
![2022-12-14_19-55](https://user-images.githubusercontent.com/2319645/207768997-8dd33ebf-10e1-4a3e-a3fb-860561907f80.jpg)

But yes, indeed the depth image is less dense, but odometry VSLAM should be fine as it won't extract features on blank walls anyway.
