### ISSUE TITLE
Source and Calculation files for rtabmap_ros

### ISSUE THREAD

**Issue by gabrielarpino** [introlab/rtabmap_ros#88]
Hi, I am trying to find the program files that do the SLAM calculations. I looked all over the src folder but couldnt find them. I would like to modify these for my project, something similar to this :  https://github.com/introlab/rtabmap/blob/master/corelib/src/BayesFilter.cpp

, but for rtabmap_ros and not just rtabmap. Thanks :)

**Comment by matlabbe** [comment]
`rtabmap_ros` is a ROS wrapper of the `rtabmap` library. To modify the SLAM approach, you have to modify the library, in particular the `Rtabmap` class. For example the main SLAM function [Rtabmap::process()](https://github.com/introlab/rtabmap/blob/be13a9b967c7b47531cd3b0ca8bf45380eac3d76/corelib/src/Rtabmap.cpp#L801-L2605) is called from [here](https://github.com/introlab/rtabmap_ros/blob/cc0591c60aa8f8003505dcf6edf13e9ed3308c70/src/CoreWrapper.cpp#L1443) in `rtabmap_ros`.

cheers

**Comment by gabrielarpino** [comment]
Thanks!

**Comment by gabrielarpino** [comment]
Cool thanks :)
