### ISSUE TITLE
node crashing right at the beginning

### ISSUE THREAD

**Issue by cy-2022** [introlab/rtabmap_ros#882]
Hello~~I'd like to ask about an issue we haven't managed to resolve yet. In our case, building and running rtabmap alone without ROS worked fine. With ZED2, mapping looks all normal. 
Building rtabmap_ros looked successful without an error, while there were warnings regarding possible conflicts of different versions of boost, etc.. 
![build_rtabmap_ros_warnings](https://user-images.githubusercontent.com/104560236/216211810-892038c0-61f4-49c0-8270-bbcc6e222e43.png)

However, when we tried to start rtabmap via roslaunch..., it crashed right at the beginning. So is this issue very likely to result from the existence of different versions of libraries? Thank you very much!

![rtabmap_ros_crashing](https://user-images.githubusercontent.com/104560236/216211820-5402caa1-6ed8-4612-8e44-4c4ca26b1bc3.png)

**Comment by cy-2022** [comment]
Indeed it was due to the existence of different versions of boost, and now this specific issue has been solved. However, as I tested with one of the TUM datasets, the "malloc.c"-related error occurred. 
![Uploading Screenshot from 2023-02-04 19-15-24.png…]()

**Comment by matlabbe** [comment]
Thread following here: https://github.com/introlab/rtabmap_ros/issues/881#issuecomment-1416726827
