### ISSUE TITLE
interface for ROS2 yaml config file 

### ISSUE THREAD

**Issue by takahiko-hasegawa-hdjp** [introlab/rtabmap_ros#883]
I want to create my own config file (yaml file) for rtabmap ros  but just wondering if there is already an interface for this where I can start from? or do I need to create one myself?

**Comment by joserafaelrebelo** [comment]
Hello, do you found a way to pass this custom yaml file to a launch file?

**Comment by matlabbe** [comment]
Maybe this link could help https://roboticsbackend.com/ros2-yaml-params/#From_a_launch_file
