### ISSUE TITLE
Error in compiling rtabmap_ros: undefined reference to `g2o::csparse::CSparse::solve(double*, double*) const'

### ISSUE THREAD

**Issue by wz8530** [introlab/rtabmap_ros#889]
Hi, the following problems occurred when compiling rtabmap_ros using `catkin_make`:
[ 74%] Built target rtabmap_ros_generate_messages
[ 74%] Building CXX object rtabmap_ros/CMakeFiles/rtabmap_camera.dir/src/CameraNode.cpp.o
[ 75%] Building CXX object rtabmap_ros/CMakeFiles/rtabmap_ros.dir/src/MapsManager.cpp.o
[ 75%] Building CXX object rtabmap_ros/CMakeFiles/rtabmap_ros.dir/src/MsgConversion.cpp.o
[ 75%] Building CXX object rtabmap_ros/CMakeFiles/rtabmap_ros.dir/src/OdometryROS.cpp.o
[ 75%] Building CXX object rtabmap_ros/CMakeFiles/rtabmap_ros.dir/src/PluginInterface.cpp.o
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::solve(double*, double*) const'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::CSparse()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::hasSymbolic() const'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::sparseView()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::freeFactor()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::sparseView()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::amd(g2o::csparse::CSparse::SparseView const&, Eigen::Matrix<int, -1, 1, 0, -1, 1>&)'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::analyze_p(int*)'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::analyze_p(int*)'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::choleskyNz() const'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::writeSparse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::freeFactor()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::solve(double*, double*) const'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::choleskyNz() const'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::~CSparse()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::SBACam::setKcam(double, double, double, double, double)'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::Factory::registerType(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<g2o::AbstractHyperGraphElementCreator> const&)'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::Cholmod()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::factor()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::EdgeSE3XYZPrior::EdgeSE3XYZPrior()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::freeSymbolic()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::factor()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::simplifyFactor()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::factorize()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::amd(g2o::cholmod::Cholmod::SparseView&, int*)'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::hasFactor() const'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::SBACam::SBACam(Eigen::Quaternion<double, 0> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&)'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::~Cholmod()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::csparse::CSparse::analyze()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::analyze()'
/home/wz/project/ws_rtabmap-0.21.0/devel/lib/librtabmap_core.so.0.21.0: undefined reference to `g2o::cholmod::Cholmod::factorize()'
collect2: error: ld returned 1 exit status
rtabmap_ros/CMakeFiles/rtabmap_rgbdicp_odometry.dir/build.make:862: recipe for target '/home/wz/project/ws_rtabmap-0.21.0/devel/lib/rtabmap_ros/rgbdicp_odometry' failed
make[2]: *** [/home/wz/project/ws_rtabmap-0.21.0/devel/lib/rtabmap_ros/rgbdicp_odometry] Error 1
CMakeFiles/Makefile2:3070: recipe for target 'rtabmap_ros/CMakeFiles/rtabmap_rgbdicp_odometry.dir/all' failed
make[1]: *** [rtabmap_ros/CMakeFiles/rtabmap_rgbdicp_odometry.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

system env:
1. Ubuntu 18.04
2. ROS melodic
3. OpenCV 3.2.0 (default)
4. g2o (https://github.com/RainerKuemmerle/g2o)
5. RTABMap v0.21.0

rtabmap cmake Configuring, and Compiled successfully:
$ cmake -DCMAKE_INSTALL_PREFIX=~/project/ws_rtabmap-0.21.0/devel -DWITH_CERES=ON -DWITH_CVSBA=0N ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- MOBILE_BUILD=OFF
-- Checking for module 'eigen3'
--   Found eigen3, version 3.4.0
-- Found eigen: /usr/local/include/eigen3  
-- Checking for module 'libopenni'
--   Found libopenni, version 1.5.4.0
-- Found openni: /usr/lib/libOpenNI.so  
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- Found libusb-1.0: /usr/include  
-- Checking for module 'flann'
--   Found flann, version 1.9.1
-- Found Flann: /usr/lib/x86_64-linux-gnu/libflann_cpp_s.a  
-- Found qhull: /usr/lib/x86_64-linux-gnu/libqhull.so  
-- Found PCL_COMMON: /usr/lib/x86_64-linux-gnu/libpcl_common.so  
-- Found PCL_OCTREE: /usr/lib/x86_64-linux-gnu/libpcl_octree.so  
-- Found PCL_IO: /usr/lib/x86_64-linux-gnu/libpcl_io.so  
-- Found PCL_KDTREE: /usr/lib/x86_64-linux-gnu/libpcl_kdtree.so  
-- Found PCL_SEARCH: /usr/lib/x86_64-linux-gnu/libpcl_search.so  
-- Found PCL_SURFACE: /usr/lib/x86_64-linux-gnu/libpcl_surface.so  
-- Found PCL_FILTERS: /usr/lib/x86_64-linux-gnu/libpcl_filters.so  
-- Found PCL_2D: /usr/include/pcl-1.8  
-- Found PCL_FEATURES: /usr/lib/x86_64-linux-gnu/libpcl_features.so  
-- Found PCL_REGISTRATION: /usr/lib/x86_64-linux-gnu/libpcl_registration.so  
-- Found PCL_SAMPLE_CONSENSUS: /usr/lib/x86_64-linux-gnu/libpcl_sample_consensus.so  
-- Found PCL_GEOMETRY: /usr/include/pcl-1.8  
-- Found PCL_ML: /usr/lib/x86_64-linux-gnu/libpcl_ml.so  
-- Found PCL_SEGMENTATION: /usr/lib/x86_64-linux-gnu/libpcl_segmentation.so  
-- Found PCL_VISUALIZATION: /usr/lib/x86_64-linux-gnu/libpcl_visualization.so  
-- PCL definitions don't contain "-march=native", make sure all libraries using Eigen are also compiled without that flag to avoid some segmentation faults (with gdb referring to some Eigen functions).
-- Found Sqlite3: /usr/include /usr/lib/x86_64-linux-gnu/libsqlite3.so
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5") found components:  C CXX 
-- Found OpenMP: /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- Add PCL_OMP to definitions
-- Found OpenCV: /usr/include;/usr/include/opencv
-- Found PCL: /usr/include/pcl-1.8;/usr/local/include/eigen3;/usr/include;/usr/include/ni;/usr/include/openni2;/usr/include/vtk-6.3;/usr/include/freetype2;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include;/usr/lib/x86_64-linux-gnu/openmpi/include;/usr/include/python2.7;/usr/include/x86_64-linux-gnu;/usr/include/hdf5/openmpi;/usr/include/libxml2;/usr/include/jsoncpp;/usr/include/tcl
-- Found ZLIB: /usr/include
-- VTK_RENDERING_BACKEND=OpenGL
-- Found Freenect: /usr/include
-- Found OpenNI2: /usr/include/openni2
-- Found DC1394: /usr/include/dc1394
-- Found g2o (targets)
-- g2o include dir: /usr/local/include/g2o/core;/usr/local/include
-- Latest g2o factory version detected with shared ptr (factory file: /usr/local/include/g2o/core/factory.h).
-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include
-- FlyCapture2_INCLUDE_DIR=FlyCapture2_INCLUDE_DIR-NOTFOUND
-- FlyCapture2_LIBRARY=FlyCapture2_LIBRARY-NOTFOUND
-- Triclops_INCLUDE_DIR=Triclops_INCLUDE_DIR-NOTFOUND
-- Triclops_LIBRARY=Triclops_LIBRARY-NOTFOUND
-- FlyCaptureBridge_LIBRARY=FlyCaptureBridge_LIBRARY-NOTFOUND
-- Found cvsba: /usr/local/include
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   filesystem
--   system
--   program_options
--   date_time
--   chrono
--   atomic
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   filesystem
--   system
--   program_options
--   date_time
--   chrono
--   atomic
-- Found libpointmatcher: /opt/ros/melodic/include;/usr/include/eigen3
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   filesystem
--   system
--   program_options
--   date_time
--   chrono
--   atomic
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   filesystem
--   system
--   program_options
--   date_time
--   chrono
--   timer
--   serialization
--   atomic
-- Found RealSense2: 
-- Found octomap 1.9.8: /opt/ros/melodic/include
-- A library with BLAS API found.
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found METIS: /usr/include (found version "5.1.0") 
-- Found ceres 2.1.0: 
-- Architecture: x86_64
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Found Pthreads
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- --------------------------------------------
-- Info :
--   RTAB-Map Version =     0.21.0
--   CMAKE_VERSION =        3.10.2
--   CMAKE_INSTALL_PREFIX = /home/wz/project/ws_rtabmap-0.21.0/devel
--   CMAKE_BUILD_TYPE =     Release
--   CMAKE_INSTALL_LIBDIR = lib
--   BUILD_APP =            ON
--   BUILD_TOOLS =          ON
--   BUILD_EXAMPLES =       ON
--   BUILD_SHARED_LIBS =    ON
--   CMAKE_CXX_FLAGS =  -fmessage-length=0  -fopenmp -std=c++14
--   FLANN_KDTREE_MEM_OPT = OFF
--   PCL_DEFINITIONS =  ;-DDISABLE_ENSENSO;-DDISABLE_DAVIDSDK;-DDISABLE_DSSDK;-DDISABLE_PCAP;-DDISABLE_PNG;-DDISABLE_LIBUSB_1_0;-DFLANN_STATIC;-Dqh_QHpointer;-DDISABLE_RSSDK
--   PCL_VERSION = 1.8.1
-- 
-- Optional dependencies ('*' affects some default parameters) :
--  *With OpenCV 3.2.0 xfeatures2d = NO, nonfree = NO (License: BSD)
--   With Qt 5.9.5            = YES (License: Open Source or Commercial)
--   With VTK 6.3              = YES (License: BSD)
--   With external SQLite3     = YES (License: Public Domain)
--   With ORB OcTree           = YES (License: GPLv3)
--   With SupertPoint          = NO (WITH_TORCH=OFF)
--   With Python3              = NO (WITH_PYTHON=OFF)
--   With Madgwick             = YES (License: GPL)
--   With FastCV               = NO (FastCV not found)
--   With PDAL                 = NO (PDAL not found)
-- 
--  Solvers:
--   With TORO                 = YES (License: Creative Commons [Attribution-NonCommercial-ShareAlike])
--  *With g2o 1.0.0            = YES (License: BSD)
--  *With GTSAM           = YES (License: BSD)
--  *With Ceres 2.1.0         = YES (License: BSD)
--   With MRPT                 = NO (MRPT not found)
--   With VERTIGO              = YES (License: GPLv3)
--   With cvsba                = YES (License: GPLv2)
--  *With libpointmatcher 1.3.1 = YES (License: BSD)
--   With CCCoreLib            = NO (WITH_CCCORELIB=OFF)
--   With Open3D               = NO (WITH_OPEN3D=OFF)
--   With OpenGV               = NO (WITH_OPENGV=OFF)
-- 
--  Reconstruction Approaches:
--   With OCTOMAP 1.9.8        = YES (License: BSD)
--   With CPUTSDF              = NO (WITH_CPUTSDF=OFF)
--   With OpenChisel           = NO (WITH_OPENCHISEL=OFF)
--   With AliceVision          = NO (WITH_ALICE_VISION=OFF)
-- 
--  Camera Drivers:
--   With Freenect             = YES (License: Apache v2 and/or GPLv2)
--   With OpenNI2              = YES (License: Apache v2)
--   With Freenect2            = NO (libfreenect2 not found)
--   With Kinect for Windows 2 = NO (Kinect for Windows 2 SDK not found)
--   With Kinect for Azure     = NO (Kinect for Azure SDK not found)
--   With dc1394               = YES (License: LGPL)
--   With FlyCapture2/Triclops = NO (Point Grey SDK not found)
--   With ZED                  = NO (ZED sdk and/or cuda not found)
--   With ZEDOC                = NO (ZED Open Capture not found)
--   With RealSense            = NO (librealsense not found)
--   With RealSense2 2.50.0    = YES (License: Apache-2)
--   With MyntEyeS             = NO (mynteye s sdk not found)
--   With DepthAI              = NO (WITH_DEPTHAI=OFF)
-- 
--  Odometry Approaches:
--   With loam_velodyne        = NO (WITH_LOAM=OFF)
--   With floam                = NO (WITH_FLOAM=OFF)
--   With libfovis             = NO (WITH_FOVIS=OFF)
--   With libviso2             = NO (WITH_VISO2=OFF)
--   With dvo_core             = NO (WITH_DVO=OFF)
--   With okvis                = NO (WITH_OKVIS=OFF)
--   With msckf_vio            = NO (WITH_MSCKF_VIO=OFF)
--   With VINS-Fusion          = NO (WITH_VINS=OFF)
--   With OpenVINS             = NO (WITH_OPENVINS=OFF)
--   With ORB_SLAM             = NO (WITH_ORB_SLAM=OFF)
-- Show all options with: cmake -LA | grep WITH_
-- --------------------------------------------
-- Configuring done
-- Generating done

Can you give me some suggestions?

**Comment by wz8530** [comment]
Through the `ldd xxx` command, it is found that the librtabmap_core.so.0.21.0 is linked to the ros-melodic-libg2o. 
Uninstalling the g2o library can solve this problem.
`$ sudo apt-get purge ros-melodic-libg2o`

**Comment by dolikemedo** [comment]
Hi!

I had a similar issue with **gtsam**. 
I'm building on ros:noetic-ros-base for a deployable slam container.

```
[ 83%] Building CXX object rtabmap_ros/rtabmap_util/CMakeFiles/rtabmap_util_plugins.dir/src/nodelets/disparity_to_depth.cpp.o
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Point2::equals(gtsam::Point2 const&, double) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Pose3::range(gtsam::Point3 const&, gtsam::OptionalJacobian<1, 6>, gtsam::OptionalJacobian<1, 3>) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Point3::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Point2::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::fpEqual(double, double, double)'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Rot2::rotate(gtsam::Point2 const&, gtsam::OptionalJacobian<2, 1>, gtsam::OptionalJacobian<2, 2>) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Pose2::bearing(gtsam::Point2 const&, gtsam::OptionalJacobian<1, 3>, gtsam::OptionalJacobian<1, 2>) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Pose3::bearing(gtsam::Point3 const&, gtsam::OptionalJacobian<2, 6>, gtsam::OptionalJacobian<2, 3>) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Rot3::xyz() const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Pose2::range(gtsam::Point2 const&, gtsam::OptionalJacobian<1, 3>, gtsam::OptionalJacobian<1, 2>) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Rot3::RzRyRx(double, double, double)'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Point3::equals(gtsam::Point3 const&, double) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Rot3::operator*(gtsam::Point3 const&) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::NoiseModelFactor::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (unsigned long)> const&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [rtabmap_ros/rtabmap_util/CMakeFiles/rtabmap_map_optimizer.dir/build.make:639: /opt/husky/robo_ws/devel/lib/rtabmap_util/map_optimizer] Error 1
[ 84%] Building CXX object rtabmap_ros/rtabmap_util/CMakeFiles/rtabmap_util_plugins.dir/src/nodelets/pointcloud_to_depthimage.cpp.o
make[1]: *** [CMakeFiles/Makefile2:5257: rtabmap_ros/rtabmap_util/CMakeFiles/rtabmap_map_optimizer.dir/all] Error 2
[ 84%] Building CXX object rtabmap_ros/rtabmap_util/CMakeFiles/rtabmap_util_plugins.dir/src/nodelets/obstacles_detection.cpp.o
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Point2::equals(gtsam::Point2 const&, double) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Pose3::range(gtsam::Point3 const&, gtsam::OptionalJacobian<1, 6>, gtsam::OptionalJacobian<1, 3>) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Point3::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Point2::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::fpEqual(double, double, double)'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Rot2::rotate(gtsam::Point2 const&, gtsam::OptionalJacobian<2, 1>, gtsam::OptionalJacobian<2, 2>) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Pose2::bearing(gtsam::Point2 const&, gtsam::OptionalJacobian<1, 3>, gtsam::OptionalJacobian<1, 2>) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Pose3::bearing(gtsam::Point3 const&, gtsam::OptionalJacobian<2, 6>, gtsam::OptionalJacobian<2, 3>) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Rot3::xyz() const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Pose2::range(gtsam::Point2 const&, gtsam::OptionalJacobian<1, 3>, gtsam::OptionalJacobian<1, 2>) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Rot3::RzRyRx(double, double, double)'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Point3::equals(gtsam::Point3 const&, double) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::Rot3::operator*(gtsam::Point3 const&) const'
/usr/bin/ld: /usr/local/lib/librtabmap_core.so.0.21.4: undefined reference to `gtsam::NoiseModelFactor::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (unsigned long)> const&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [rtabmap_ros/rtabmap_util/CMakeFiles/rtabmap_data_player.dir/build.make:639: /opt/husky/robo_ws/devel/lib/rtabmap_util/data_player] Error 1
make[1]: *** [CMakeFiles/Makefile2:5635: rtabmap_ros/rtabmap_util/CMakeFiles/rtabmap_data_player.dir/all] Error 2
```

I removed `ros-noetic-gtsam` and catkin_make finished. 
**Won't this be an issue further down the line?**    
Will start testing tomorrow.    

I had:
```
root@BB-8:/# apt list --installed | grep gtsam

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libgtsam-dev/focal,now 4.0.3-1ubuntu1 amd64 [installed]
libgtsam-unstable-dev/focal,now 4.0.3-1ubuntu1 amd64 [installed]
libgtsam-unstable4/focal,now 4.0.3-1ubuntu1 amd64 [installed,automatic]
libgtsam4/focal,now 4.0.3-1ubuntu1 amd64 [installed,automatic]
ros-noetic-gtsam/focal,now 4.2.0-2focal.20230620.181134 amd64 [installed,auto-removable]
```
Hmm It says auto-removeable.
Maybe there's something with "easiest way to install deps is to install and remove rtabmap".    
I guess you should not install with "--no-install-recommends" flag in apt.    
Many ros packages show up as no longer required since they were not specificly installed but a package was which was removed later. 
```
root@BB-8:/# apt remove ros-noetic-gtsam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libasound2-dev libcaca-dev libpulse-dev libsdl-image1.2 libsdl-image1.2-dev libsdl1.2-dev libsdl1.2debian libslang2-dev python3-serial ros-noetic-amcl ros-noetic-apriltag ros-noetic-apriltag-ros ros-noetic-base-local-planner
  ros-noetic-clear-costmap-recovery ros-noetic-costmap-2d ros-noetic-ddynamic-reconfigure ros-noetic-dwa-local-planner ros-noetic-filters ros-noetic-find-object-2d ros-noetic-gmapping ros-noetic-grid-map-core ros-noetic-grid-map-cv
  ros-noetic-grid-map-msgs ros-noetic-grid-map-ros ros-noetic-hector-mapping ros-noetic-hls-lfcd-lds-driver ros-noetic-husky-navigation ros-noetic-imu-filter-madgwick ros-noetic-kdl-conversions ros-noetic-librealsense2
  ros-noetic-map-server ros-noetic-move-base ros-noetic-nav-core ros-noetic-navfn ros-noetic-octomap ros-noetic-octomap-msgs ros-noetic-openslam-gmapping ros-noetic-realsense2-camera ros-noetic-rosserial-python
  ros-noetic-rotate-recovery ros-noetic-rtabmap-costmap-plugins ros-noetic-rtabmap-msgs ros-noetic-rtabmap-python ros-noetic-tf-conversions ros-noetic-turtlebot3-bringup ros-noetic-turtlebot3-description ros-noetic-turtlebot3-gazebo
  ros-noetic-turtlebot3-msgs ros-noetic-turtlebot3-navigation ros-noetic-turtlebot3-teleop ros-noetic-velodyne-driver ros-noetic-velodyne-laserscan ros-noetic-velodyne-msgs ros-noetic-velodyne-pointcloud ros-noetic-voxel-grid
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  ros-noetic-gtsam
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 11.0 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 132235 files and directories currently installed.)
Removing ros-noetic-gtsam (4.2.0-2focal.20230620.181134) ...
Processing triggers for libc-bin (2.31-0ubuntu9.15) ...
```

Sorry if I misunderstand :-)
Thanks for any info.

**Comment by matlabbe** [comment]
The latest ros package now depends on `ros-noetic-gtsam` and `ros-noetic-libg2o` so you don't have to install those packages individually. However, if you installed gtsam or g2o another way at the same time, there could be issue like above. You can have to uninstall one the version.
