### ISSUE TITLE
build rtabmap_ros with linkage of rtabmap form /usr/local/lib

### ISSUE THREAD

**Issue by willdzeng** [introlab/rtabmap_ros#90]
Deal with ROS sometimes need to delete /devel directory in workspace very often.
Maybe change the linkage of rtabmap to /usr/local/lib to make re-compile of rtabmap_ros easier?

**Comment by matlabbe** [comment]
rtabmap can be installed in `/usr/local` (default install directory), catkin_make will still be able to find it.

**Comment by matlabbe** [comment]
Missclick on "close and comment"... In https://github.com/introlab/rtabmap_ros#build-from-source, I recommended to install in `catkin_ws/devel` but it is optional.

**Comment by matlabbe** [comment]
I updated the [step 2](https://github.com/introlab/rtabmap_ros#build-from-source) or the install instructions.

**Comment by willdzeng** [comment]
I see, I guess the reason I failed to compile with /user/local is I didn't delete the old build folder.
Now I this is fixed.
