### ISSUE TITLE
rtab stops creating map after some time 

### ISSUE THREAD

**Issue by raviS123-dot** [introlab/rtabmap_ros#901]
[rtabmap-2] [ERROR] (2023-03-02 14:37:48.377) Rtabmap.cpp:1341::process() RGB-D SLAM mode is enabled, memory is incremental but no odometry is provided. Image 0 is ignored!

[rtabmap-2] [ WARN] (2023-03-02 14:37:36.243) Rtabmap.cpp:4334::process() Republishing data of requested node(s) 1 (Rtabmap/MaxRepublished=2)
![test](https://user-images.githubusercontent.com/58106153/222384583-69857d79-a1b4-4d0e-be88-793e0a29a5c2.png)

[rtabmapviz-3] [ WARN] (2023-03-02 14:38:05.815) MsgConversion.cpp:1758::getTransform() (can transform odom -> camera_link?) Lookup would require extrapolation into the past.  Requested time 210.399000 but the earliest data is at time 1677748075.932202, when looking up transform from frame [camera_link] to frame [odom]. canTransform returned after 0.203269 timeout was 0.2. (wait_for_transform=0.200000)

[rgbd_odometry-1] [ WARN] (2023-03-02 14:38:06.458) OdometryF2M.cpp:557::computeTransform() Registration failed: "Not enough inliers 0/20 (matches=17) between -1 and 172"

[rgbd_odometry-1] [ WARN] (2023-03-02 14:38:05.609) OdometryF2M.cpp:557::computeTransform() Registration failed: "Not enough inliers 0/20 (matches=16) between -1 and 169"

**Comment by matlabbe** [comment]
Odometry is lost, see https://github.com/introlab/rtabmap/wiki/Kinect-mapping#lostodometry for events that could cause that.
