### ISSUE TITLE
weird map with oakd camera

### ISSUE THREAD

**Issue by an99990** [introlab/rtabmap_ros#907]
HI,
I am using rtabmap ros along with the oak-d camera. The camera is put on top of a small vehicule. The generated map is a bit weird. Is it because the floor is shinning ? what could cause the map to be like that

```
roslaunch depthai_examples stereo_inertial
_node.launch depth_aligned:=false
```

`roslaunch rtabmap_ros rtabmap.launch     args:="--delete_db_on_start"     stereo:=true     left_image_topic:=/stereo_inertial_publisher/left/image_rect     right_image_topic:=/stereo_inertial_publisher/right/image_rect     left_camera_info_topic:=/stereo_inertial_publisher/left/camera_info     right_camera_info_topic:=/stereo_inertial_publisher/right/camera_info     imu_topic:=/stereo_inertial_publisher/imu     frame_id:=oak-d_frame     approx_sync:=true     wait_imu_to_init:=true`

![map_generated](https://user-images.githubusercontent.com/87030365/223264462-14a1a6f8-9945-48ca-a0f6-b920be340e5b.png)

![rtabmap_ui_env](https://user-images.githubusercontent.com/87030365/223265323-d42266a0-aaaf-424f-9c11-730225fd1d35.png)

**Comment by matlabbe** [comment]
It is expected, the floor acts like a mirror. To fill the empty space, try with `Grid/RayTracing=true` and `Grid/3D=false`.

cheers,
Mathieu

**Comment by an99990** [comment]
are those arguments in the rtabmap.launch file ?

**Comment by matlabbe** [comment]
With rtabmap.launch, you can do this:
```bash
roslaunch rtabmap_ros rtabmap.launch \
    args:="--delete_db_on_start --Grid/RayTracing true --Grid/3D false" \
    stereo:=true \
    left_image_topic:=/stereo_inertial_publisher/left/image_rect \
    right_image_topic:=/stereo_inertial_publisher/right/image_rect \
    left_camera_info_topic:=/stereo_inertial_publisher/left/camera_info \
    right_camera_info_topic:=/stereo_inertial_publisher/right/camera_info \
    imu_topic:=/stereo_inertial_publisher/imu \
    frame_id:=oak-d_frame \
    approx_sync:=true \
   wait_imu_to_init:=true
```

**Comment by an99990** [comment]
wow it made such an improvement, thank you !
