### ISSUE TITLE
cloudFromDepthRGB() Cloud with only NaN values created!

### ISSUE THREAD

**Issue by JayParikh20** [introlab/rtabmap_ros#909]
Point cloud fails to generate for most of the datasets
getting this error,
      
      [ INFO] [1678312002.799662227]: rtabmap 0.20.23 started...
      [ WARN] [1678312003.812500837]: Callbacks not syncronized for 5.0 secs!
      [ INFO] [1678312005.244696531]: Odom: quality=0, std dev=99.995000m|99.995000rad, update time=0.065001s
      [ WARN] (2023-03-08 16:46:45.477) util3d.cpp:605::cloudFromDepthRGB() Cloud with only NaN values created!

I tried on these datasets,
- TUM -> fr1/desk2 [Link](https://cvg.cit.tum.de/data/datasets/rgbd-dataset/download)
- rgbd-scenes-v2 [Link](http://rgbd-dataset.cs.washington.edu/dataset/rgbd-scenes-v2/)

It works perfectly for,

- Redwood dataset -> living room 1 [Link](http://redwood-data.org/indoor/dataset.html)

**Comment by JayParikh20** [comment]
... logging to /home/valorrobotics/.ros/log/b4184c62-bdfa-11ed-a065-48b02d833aa8/roslaunch-ubuntu-129589.log
      Checking log directory for disk usage. This may take a while.
      Press Ctrl-C to interrupt
      Done checking log file disk usage. Usage is <1GB.
      
      started roslaunch server http://ubuntu:36157/
      
      SUMMARY
      ========
      
      PARAMETERS
       * /rosdistro: noetic
       * /rosversion: 1.15.15
       * /vr/rgbd_odometry/frame_id: vr_camera
       * /vr/rgbd_odometry/subscribe_rgbd: True
       * /vr/rgbd_sync/approx_sync: False
       * /vr/rtabmap/RGBD/AngularUpdate: 0.01
       * /vr/rtabmap/RGBD/LinearUpdate: 0.01
       * /vr/rtabmap/RGBD/OptimizeFromGraphEnd: false
       * /vr/rtabmap/Rtabmap/DetectionRate: 30.0
       * /vr/rtabmap/approx_sync: False
       * /vr/rtabmap/frame_id: vr_camera
       * /vr/rtabmap/queue_size: 10
       * /vr/rtabmap/subscribe_depth: False
       * /vr/rtabmap/subscribe_rgb: False
       * /vr/rtabmap/subscribe_rgbd: True
      
      NODES
        /
          display_frames (stereo_camera/display_frames)
          pointcloud_visualizer (stereo_camera/pointcloud_visualizer)
          read_rgbd (stereo_camera/read_rgbd.py)
        /vr/
          rgbd_odometry (rtabmap_ros/rgbd_odometry)
          rgbd_sync (nodelet/nodelet)
          rtabmap (rtabmap_ros/rtabmap)
      
      auto-starting new master
      process[master]: started with pid [129608]
      ROS_MASTER_URI=http://localhost:11311
      
      setting /run_id to b4184c62-bdfa-11ed-a065-48b02d833aa8
      process[rosout-1]: started with pid [129629]
      started core service [/rosout]
      process[read_rgbd-2]: started with pid [129636]
      process[pointcloud_visualizer-3]: started with pid [129637]
      process[display_frames-4]: started with pid [129638]
      process[vr/rgbd_sync-5]: started with pid [129639]
      process[vr/rgbd_odometry-6]: started with pid [129640]
      type is rtabmap_ros/rgbd_sync
      process[vr/rtabmap-7]: started with pid [129641]
      [ INFO] [1678311999.248404989]: Initializing nodelet with 12 worker threads.
      [ INFO] [1678311999.403056922]: Odometry: frame_id               = vr_camera
      [ INFO] [1678311999.403121915]: Odometry: odom_frame_id          = odom
      [ INFO] [1678311999.403144539]: Odometry: publish_tf             = true
      [ INFO] [1678311999.403162939]: Odometry: wait_for_transform     = true
      [ INFO] [1678311999.403187899]: Odometry: wait_for_transform_duration  = 0.100000
      [ INFO] [1678311999.403206203]: Odometry: log_to_rosout_level    = 4
      [ INFO] [1678311999.403270236]: Odometry: initial_pose           = xyz=0.000000,0.000000,0.000000 rpy=0.000000,-0.000000,0.000000
      [ INFO] [1678311999.403294044]: Odometry: ground_truth_frame_id  = 
      [ INFO] [1678311999.403311677]: Odometry: ground_truth_base_frame_id = vr_camera
      [ INFO] [1678311999.403330045]: Odometry: config_path            = 
      [ INFO] [1678311999.403347485]: Odometry: publish_null_when_lost = true
      [ INFO] [1678311999.403363421]: Odometry: guess_frame_id         = 
      [ INFO] [1678311999.403382013]: Odometry: guess_min_translation  = 0.000000
      [ INFO] [1678311999.403399358]: Odometry: guess_min_rotation     = 0.000000
      [ INFO] [1678311999.403417342]: Odometry: guess_min_time         = 0.000000
      [ INFO] [1678311999.403435742]: Odometry: expected_update_rate   = 0.000000 Hz
      [ INFO] [1678311999.403453342]: Odometry: max_update_rate        = 0.000000 Hz
      [ INFO] [1678311999.403471006]: Odometry: min_update_rate        = 0.000000 Hz
      [ INFO] [1678311999.403486847]: Odometry: wait_imu_to_init       = false
      [ INFO] [1678311999.403528767]: Odometry: stereoParams_=0 visParams_=1 icpParams_=0
      [ INFO] [1678311999.459881279]: Starting node...
      [ INFO] [1678311999.582467728]: Initializing nodelet with 12 worker threads.
      [ INFO] [1678312000.078068846]: /vr/rtabmap(maps): map_filter_radius          = 0.000000
      [ INFO] [1678312000.078183535]: /vr/rtabmap(maps): map_filter_angle           = 30.000000
      [ INFO] [1678312000.078218096]: /vr/rtabmap(maps): map_cleanup                = true
      [ INFO] [1678312000.078234128]: /vr/rtabmap(maps): map_always_update          = false
      [ INFO] [1678312000.078247216]: /vr/rtabmap(maps): map_empty_ray_tracing      = true
      [ INFO] [1678312000.078260240]: /vr/rtabmap(maps): cloud_output_voxelized     = true
      [ INFO] [1678312000.078272944]: /vr/rtabmap(maps): cloud_subtract_filtering   = false
      [ INFO] [1678312000.078285616]: /vr/rtabmap(maps): cloud_subtract_filtering_min_neighbors = 2
      [ INFO] [1678312000.079015449]: /vr/rtabmap(maps): octomap_tree_depth         = 16
      [ INFO] [1678312000.114143848]: rtabmap: frame_id      = vr_camera
      [ INFO] [1678312000.114217577]: rtabmap: map_frame_id  = map
      [ INFO] [1678312000.114238089]: rtabmap: log_to_rosout_level = 4
      [ INFO] [1678312000.114258089]: rtabmap: initial_pose  = 
      [ INFO] [1678312000.114274185]: rtabmap: use_action_for_goal  = false
      [ INFO] [1678312000.114296970]: rtabmap: tf_delay      = 0.050000
      [ INFO] [1678312000.114311786]: rtabmap: tf_tolerance  = 0.100000
      [ INFO] [1678312000.114324778]: rtabmap: odom_sensor_sync   = false
      [ INFO] [1678312000.115915484]: rtabmap: gen_scan  = false
      [ INFO] [1678312000.115961436]: rtabmap: gen_depth  = false
      [ INFO] [1678312000.230002956]: /vr/rgbd_sync: approx_sync = false
      [ INFO] [1678312000.232559849]: /vr/rgbd_sync: queue_size  = 10
      [ INFO] [1678312000.232613674]: /vr/rgbd_sync: depth_scale = 1.000000
      [ INFO] [1678312000.232664586]: /vr/rgbd_sync: decimation = 1
      [ INFO] [1678312000.232701803]: /vr/rgbd_sync: compressed_rate = 0.000000
      [ INFO] [1678312000.266777006]: 
      /vr/rgbd_sync subscribed to (exact sync):
         /vr/image_rect_color \
         /vr/depth_map \
         /vr/camera_info
      [ INFO] [1678312000.499242463]: RGBDOdometry: approx_sync    = true
      [ INFO] [1678312000.499313759]: RGBDOdometry: approx_sync_max_interval = 0.000000
      [ INFO] [1678312000.499334048]: RGBDOdometry: queue_size     = 5
      [ INFO] [1678312000.499349568]: RGBDOdometry: subscribe_rgbd = true
      [ INFO] [1678312000.499363328]: RGBDOdometry: rgbd_cameras   = 1
      [ INFO] [1678312000.499379648]: RGBDOdometry: keep_color     = false
      [ INFO] [1678312000.506797236]: 
      /vr/rgbd_odometry subscribed to:
         /vr/rgbd_image
      [ INFO] [1678312000.861164526]: Setting RTAB-Map parameter "RGBD/AngularUpdate"="0.01"
      [ INFO] [1678312000.883889136]: Setting RTAB-Map parameter "RGBD/LinearUpdate"="0.01"
      [ INFO] [1678312000.928489963]: Setting RTAB-Map parameter "RGBD/OptimizeFromGraphEnd"="false"
      [ INFO] [1678312001.009389634]: Setting RTAB-Map parameter "Rtabmap/DetectionRate"="30.0"
      [ INFO] [1678312001.995743079]: RTAB-Map detection rate = 30.000000 Hz
      [ INFO] [1678312002.069215658]: rtabmap: Deleted database "/home/valorrobotics/.ros/rtabmap.db" (--delete_db_on_start or -d are set).
      [ INFO] [1678312002.069357675]: rtabmap: Using database from "/home/valorrobotics/.ros/rtabmap.db" (0 MB).
      [ INFO] [1678312002.198611143]: rtabmap: Database version = "0.20.23".
      [ INFO] [1678312002.198732361]: rtabmap: SLAM mode (Mem/IncrementalMemory=true)
      [ INFO] [1678312002.259436570]: /vr/rtabmap: subscribe_depth = false
      [ INFO] [1678312002.259511739]: /vr/rtabmap: subscribe_rgb = false
      [ INFO] [1678312002.259532700]: /vr/rtabmap: subscribe_stereo = false
      [ INFO] [1678312002.259570076]: /vr/rtabmap: subscribe_rgbd = true (rgbd_cameras=1)
      [ INFO] [1678312002.259595420]: /vr/rtabmap: subscribe_odom_info = false
      [ INFO] [1678312002.259612604]: /vr/rtabmap: subscribe_user_data = false
      [ INFO] [1678312002.259626365]: /vr/rtabmap: subscribe_scan = false
      [ INFO] [1678312002.259642589]: /vr/rtabmap: subscribe_scan_cloud = false
      [ INFO] [1678312002.259656253]: /vr/rtabmap: subscribe_scan_descriptor = false
      [ INFO] [1678312002.259671069]: /vr/rtabmap: queue_size    = 10
      [ INFO] [1678312002.259686013]: /vr/rtabmap: approx_sync   = false
      [ INFO] [1678312002.259760958]: Setup rgbd callback
      [ INFO] [1678312002.284128947]: 
      /vr/rtabmap subscribed to (exact sync):
         /vr/odom \
         /vr/rgbd_image
      [ INFO] [1678312002.799662227]: rtabmap 0.20.23 started...
      [ WARN] [1678312003.812500837]: Callbacks not syncronized for 5.0 secs!
      [ INFO] [1678312005.244696531]: Odom: quality=0, std dev=99.995000m|99.995000rad, update time=0.065001s
      [ WARN] (2023-03-08 16:46:45.477) util3d.cpp:605::cloudFromDepthRGB() Cloud with only NaN values created!
      [ WARN] [1678312005.497049862]: Graph has changed! The whole cloud is regenerated.
      [ INFO] [1678312005.497195847]: Assembled 0 obstacle and 0 ground clouds (0 points, 0.000252s)
      [ INFO] [1678312005.497950064]: rtabmap (1): Rate=0.03s, Limit=0.000s, Conversion=0.0012s, RTAB-Map=0.2486s, Maps update=0.0008s pub=0.0010s (local map=1, WM=1)
      [ INFO] [1678312005.751922709]: Odom: quality=348, std dev=0.029551m|0.016542rad, update time=0.488451s
      [ INFO] [1678312005.996082827]: Odom: quality=389, std dev=0.047527m|0.022437rad, update time=0.238603s
      [ WARN] (2023-03-08 16:46:46.061) util3d.cpp:605::cloudFromDepthRGB() Cloud with only NaN values created!
      [ INFO] [1678312006.086745649]: Assembled 0 obstacle and 0 ground clouds (0 points, 0.000014s)
      [ INFO] [1678312006.086929395]: rtabmap (2): Rate=0.03s, Limit=0.000s, Conversion=0.0009s, RTAB-Map=0.3386s, Maps update=0.0061s pub=0.0002s (local map=2, WM=2)
      [ INFO] [1678312006.257541957]: Odom: quality=396, std dev=0.035937m|0.017423rad, update time=0.256071s
      [ WARN] (2023-03-08 16:46:46.290) util3d.cpp:605::cloudFromDepthRGB() Cloud with only NaN values created!
      [ INFO] [1678312006.326499348]: Assembled 0 obstacle and 0 ground clouds (0 points, 0.000006s)
      [ INFO] [1678312006.326861145]: rtabmap (3): Rate=0.03s, Limit=0.000s, Conversion=0.0003s, RTAB-Map=0.2316s, Maps update=0.0064s pub=0.0004s (local map=3, WM=3)
      [ INFO] [1678312006.487896254]: Odom: quality=363, std dev=0.046047m|0.018867rad, update time=0.224712s
      [ WARN] (2023-03-08 16:46:46.602) util3d.cpp:605::cloudFromDepthRGB() Cloud with only NaN values created!
      [ INFO] [1678312006.621754959]: Assembled 0 obstacle and 0 ground clouds (0 points, 0.000007s)
      [ INFO] [1678312006.622115091]: rtabmap (4): Rate=0.03s, Limit=0.000s, Conversion=0.0003s, RTAB-Map=0.2932s, Maps update=0.0004s pub=0.0004s (local map=4, WM=4)
      [ INFO] [1678312006.733871848]: Odom: quality=387, std dev=0.036800m|0.019078rad, update time=0.231578s
      [ WARN] (2023-03-08 16:46:46.857) util3d.cpp:605::cloudFromDepthRGB() Cloud with only NaN values created!
      [ INFO] [1678312006.882292318]: Assembled 0 obstacle and 0 ground clouds (0 points, 0.000008s)
      [ INFO] [1678312006.882620482]: rtabmap (5): Rate=0.03s, Limit=0.000s, Conversion=0.0009s, RTAB-Map=0.2488s, Maps update=0.0055s pub=0.0004s (local map=5, WM=5)
      [ INFO] [1678312006.989199517]: Odom: quality=387, std dev=0.033262m|0.017144rad, update time=0.246963s
      [ WARN] (2023-03-08 16:46:47.117) util3d.cpp:605::cloudFromDepthRGB() Cloud with only NaN values created!
      [ INFO] [1678312007.168892598]: Assembled 0 obstacle and 0 ground clouds (0 points, 0.000008s)
      [ INFO] [1678312007.169521565]: rtabmap (6): Rate=0.03s, Limit=0.000s, Conversion=0.0003s, RTAB-Map=0.2542s, Maps update=0.0308s pub=0.0007s (local map=6, WM=6)
      [ INFO] [1678312007.246098115]: Odom: quality=323, std dev=0.041772m|0.018867rad, update time=0.242835s
      [ WARN] (2023-03-08 16:46:47.401) util3d.cpp:605::cloudFromDepthRGB() Cloud with only NaN values created!
      [ INFO] [1678312007.439167988]: Odom: quality=382, std dev=0.040896m|0.017944rad, update time=0.187887s
      [ INFO] [1678312007.443841481]: Assembled 0 obstacle and 0 ground clouds (0 points, 0.000010s)
      [ INFO] [1678312007.444371087]: rtabmap (7): Rate=0.03s, Limit=0.000s, Conversion=0.0003s, RTAB-Map=0.2480s, Maps update=0.0242s pub=0.0006s (local map=7, WM=7)
      [ INFO] [1678312007.644015371]: Odom: quality=364, std dev=0.047601m|0.021486rad, update time=0.201133s
      [ WARN] (2023-03-08 16:46:47.708) util3d.cpp:605::cloudFromDepthRGB() Cloud with only NaN values created!
      [ INFO] [1678312007.722803594]: Assembled 0 obstacle and 0 ground clouds (0 points, 0.000011s)
      [ INFO] [1678312007.723373329]: rtabmap (8): Rate=0.03s, Limit=0.000s, Conversion=0.0004s, RTAB-Map=0.2700s, Maps update=0.0063s pub=0.0006s (local map=8, WM=8)
      ^C[vr/rtabmap-7] killing on exit
      [ INFO] [1678312007.838382059]: Odom: quality=341, std dev=0.043961m|0.019672rad, update time=0.190245s
      [vr/rgbd_odometry-6] killing on exit
      [vr/rgbd_sync-5] killing on exit
      [display_frames-4] killing on exit
      [pointcloud_visualizer-3] killing on exit
      [read_rgbd-2] killing on exit
      [ WARN] (2023-03-08 16:46:47.884) util3d.cpp:605::cloudFromDepthRGB() Cloud with only NaN values created!
      [ WARN] (2023-03-08 16:46:48.016) util3d.cpp:605::cloudFromDepthRGB() Cloud with only NaN values created!
      rtabmap: Saving database/long-term memory... (located at /home/valorrobotics/.ros/rtabmap.db)
      rtabmap: Saving database/long-term memory...done! (located at /home/valorrobotics/.ros/rtabmap.db, 3 MB)
      [rosout-1] killing on exit
      [master] killing on exit
      shutting down processing monitor...
      ... shutting down processing monitor complete
      done

**Comment by JayParikh20** [comment]
Most of the datasets that are not working have a black border around the edges, which might be causing problem.

**Comment by JayParikh20** [comment]
Most of the datasets that are not working have a black border(zero depth) around the edges, which might be causing the issue. Especially, the ones with black border on top and bottom of the image.

**Comment by matlabbe** [comment]
Can you provide the launch file for at least rtabmap part?

For TUM RGB-D, there is a tool called `rtabmap-rgbd_dataset` (see --help to associate images) for evaluation. Anyway, I tried with standalone, using camera calibration from here:
https://github.com/introlab/rtabmap/blob/0f221ba3cd9913b68ec508af0d914e3f49860430/tools/RgbdDataset/main.cpp#L190

![Screenshot from 2023-04-15 17-59-12](https://user-images.githubusercontent.com/2319645/232261139-7264536d-9c6e-4ec1-82e9-dd1d68cd5a20.png)


It is also possible to use [rgbdslam_datasets.launch](https://github.com/introlab/rtabmap_ros/blob/master/rtabmap_examples/launch/rgbdslam_datasets.launch) file for rtabmap_ros.
 
For the other dataset, I tried also with standalone, but I didn't find where the camera calibration can be downloaded on their [website](http://rgbd-dataset.cs.washington.edu/dataset/rgbd-scenes-v2/), so there is with the TUM fr1 calibration as above:
![Screenshot from 2023-04-15 17-50-32](https://user-images.githubusercontent.com/2319645/232260471-0e78097f-2182-4533-a6b2-6f8f92a34775.png)
