### ISSUE TITLE
Loop closure is not detected but map->odom is not an identity matrix

### ISSUE THREAD

**Issue by Hypothesis-Z** [introlab/rtabmap_ros#926]
I have set Vis/MinInliers to a large number so that no loop closure is accepted. The transform between map and odom should be an identity matrix because RTAB-Map won't do any global optimization.  But the fact is not what thought to be. Why?

![7AE524C8-FA1E-4bf4-81BE-317F2FE7225A](https://user-images.githubusercontent.com/44766273/228476465-525fc191-e49b-429c-963a-f1b8e724d711.png)

**Comment by Hypothesis-Z** [comment]
It was because I fed imu data to RTAB-Map node. Close the issue.

**Comment by matlabbe** [comment]
To disable visual loop closure detection, to most efficient way is to set `Kp/MaxFeatures=-1` to just not extract any features.

**Comment by Hypothesis-Z** [comment]
@matlabbe Thank you for advice. But if no feature is extracted, how to generate visual odometry? Don't we need features to compute PnP and BA?

**Comment by matlabbe** [comment]
`Kp/MaxFeatures=-1` disable loop closure detection, not odometry.
