### ISSUE TITLE
rtabmap_slam Z axis drifting - ZED2i on an UAV for outdoors environments

### ISSUE THREAD

**Issue by aaraujo11** [introlab/rtabmap_ros#929]
I'm using **rtabmap_slam** with **stereo_odometry** with the ZED2i camera (with a Jetson Xavier NX 16G), on an UAV for outdoors forestry environments, in terms of camera setup its installed in the front with a 35º pitch down, i intend to flight in low altitudes (2 - 4m). My available inputs are:
- IMU (100Hz)
- GPS RTK (5Hz) "Float" mainly all the time under the vegetation
- GPS RTK fused with acc (100Hz)
- image_rect_color HD720 (10Hz)

I manage to achieve a interesting parameriazation using [demo_stereo_outdoor](https://github.com/introlab/rtabmap_ros/blob/master/rtabmap_demos/launch/demo_stereo_outdoor.launch) as base, with a very good 2D pose, however in long term it start to drift mainly in Z axis as you can check in the following PS, any idea what it can be.

I notice that it barely appear a close loop in that trial, even crossing same paths in several points of the map.

![Screenshot from 2023-03-31 15-36-38](https://user-images.githubusercontent.com/4540967/229168645-a728d726-ec44-4f5e-9853-47f6ce85ccc7.png)
![Screenshot from 2023-03-31 15-36-28](https://user-images.githubusercontent.com/4540967/229168680-380279ea-b439-42f5-b6da-e8a586ba3b2f.png)
![Screenshot from 2023-03-31 15-37-00](https://user-images.githubusercontent.com/4540967/229168726-089931a5-c2be-4165-b75a-bba7b0f9ea0f.png)

**Comment by matlabbe** [comment]
Did you feed stereo_odometry with IMU? Which one? Is the 35º pitch down between the base frame and camera frame correctly set in URDF? Is URDF between the IMU, base frame and camera frame accurate?

If you don't feed IMU to `stereo_odometry` and `rtabmap` nodes, you may add it to correct pitch and roll over time.

**Comment by aaraujo11** [comment]
Hello @matlabbe thank you, after fine tuning the static TF of the camera it really improve the Z axis drift, and its using IMU data in both `stereo_odometry` and `rtabmap_slam` but still it exists, maybe is better to keep this discussion in one issue #922 , i will close this one. Sorry for the duplication.
