### ISSUE TITLE
RGBD Markers not changing map frame origin

### ISSUE THREAD

**Issue by peredwardsson** [introlab/rtabmap_ros#935]
Hello,

I am using two apriltags to mark an obstacle in my room that i would like to use for the map coordinate system. I have set the priors such that it should (approximately) match two outer edges of the object, and i expect that the map origin should move to be inbetween these two (subject to my approximation, of course). However, I find that no map origin shifting is happening at all. The markers are added, and I can see them if i visualize `/rtabmap/labels`. Am I misunderstanding the function or am I using it wrong? Here are my related params:
```
    Marker/Dictionary: "20"
    Marker/Length: "0.072"
    Marker/Priors: "1 0 0 0 0 0 0|2 0 2.0 0.5 0 0 3.14"
    RGBD/MarkerDetection: "True"
```

**Comment by matlabbe** [comment]
You may have to add parameter `Optimizer/PriorsIgnored` to false so that optimization can use the priors.
