### ISSUE TITLE
republish_right-3 and republish_left-2 process have died

### ISSUE THREAD

**Issue by QuangTruong1506** [introlab/rtabmap_ros#938]
Hi,
I've been trying to run a demo of stereo outdoor in rtapmap tutorial, but i see an issues like this:
![Screenshot from 2023-04-07 10-45-56](https://user-images.githubusercontent.com/77477617/230536889-fb35d70e-7b4b-4374-b530-0a517d05b763.png)
I'am looking forward to everyone's help, thanks.

**Comment by matlabbe** [comment]
`image_transport/republish` node is not from `rtabmap_ros` repo, see https://github.com/ros-perception/image_common/blob/noetic-devel/image_transport/src/republish.cpp

I see you rebuilt `image_transport` locally in your `catkin_ws`, I would try the binary one instead.
