### ISSUE TITLE
cant see rtabmapviz but see it with rtabmap

### ISSUE THREAD

**Issue by an99990** [introlab/rtabmap_ros#939]
Hi,
so weirdly i am able to see rtabmapviz when i type rtabmap, but not when im launching a node

`ERROR: cannot launch node of type [rtabmap_ros/rtabmapviz]: Cannot locate node of type [rtabmapviz] in package [rtabmap_ros]. Make sure file exists in package path and permission is set to executable (chmod +x)`

on rtabmap_ros-0.20.23-noetic release

I indeed dont see rtabmapviz in my build folder

I noticed in the catkin_build that it said that i install rtabmap without gui support, which is weird because i have the rtabmapviz when i type rtabmap

**Comment by matlabbe** [comment]
Issue is closed, mybe you were on 0.21? `rtabmapviz` has benn moved to `rtabmap_viz` package, and renamed `rtabmap_viz`. 
Ref: http://wiki.ros.org/rtabmap_ros#rtabmap_ros.2Fnoetic_and_newer.Migration_Guide_New_Interface_Noetic.2FROS2

**Comment by matlabbe** [comment]
If you refer to zed_rtabmap_example, I created a pull request: https://github.com/stereolabs/zed-ros-examples/pull/49/files
