### ISSUE TITLE
Question about a landmark. 

### ISSUE THREAD

**Issue by JoongKu-Lee** [introlab/rtabmap_ros#944]
Hello, 

I am trying new concept of mapping and I have a simple question about the landmark input in the rtabmap framework. 
I could find some examples to assign landmarks from April tag information. 
However, in my understanding, the landmarks can only be assigned from the last node in the pose graph, not from a specific node in the pose graph. I wonder if this is correct or not. (in rtabmap_ros)

if it is correct for rtabmap_ros, is it also not available with the rtabmap? 
With the rtabmap API, I have actually tried to open the pre-generated database, generate new node, and add link, but failed to add link because the weight of the node became < 0. (I cannot understand this either.. reading data with Dbdriver shows weight>0 but becomes <0 when those are put into rtabmap::Rtabmap)

If possible, any instruction or clue is welcomed. 

Thank you.

**Comment by matlabbe** [comment]
> However, in my understanding, the landmarks can only be assigned from the last node in the pose graph, not from a specific node in the pose graph. I wonder if this is correct or not. (in rtabmap_ros)

correct. It could be possible to add a landmark link to any node offline by manually editing the database.

A node with weight < 0 is an intermediate node. If you add a new node, set weight to 0. To add a landmark, don't add a new node, just edit Link table to add a landmark link.
