### ISSUE TITLE
catkin_make depthai_core not found error

### ISSUE THREAD

**Issue by lgh5054** [introlab/rtabmap_ros#948]
![image](https://user-images.githubusercontent.com/35057391/232643651-2e915eeb-715d-438d-837a-84f06375cf0a.png)

hello 

I'm installed Rtabmap 

source build depthai = on

but catkin_make error 

CMake Error at /home/nvidia/catkin_ws/devel/share/rtabmap_conversions/cmake/rtabmap_conversionsConfig.cmake:173 (message):
  Project 'rtabmap_demos' tried to find library 'depthai::core'.  The library
  is neither a target nor built/installed properly.  Did you compile project
  'rtabmap_conversions'? Did you find_package() it before the subdirectory
  containing its code is included?
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  rtabmap_ros-noetic-devel/rtabmap_demos/CMakeLists.txt:4 (find_package)

**Comment by matlabbe** [comment]
Humm, the rtabmap library has been built witl depthai dependency, but rtabmap_conversions package is failing finding the library. There is maybe a bug in exported `RTABMapConfig.cmake` when rtabmap is built with depthai. I'll take a look.
