### ISSUE TITLE
0.21.1 Noetic update

### ISSUE THREAD

**Issue by wakoko79** [introlab/rtabmap_ros#949]
Just noticed that noetic branch just updated to 0.21.1, problem is all of my scripts now stopped working, and the documentation in [wiki.ros.org/rtabmap_ros](http://wiki.ros.org/rtabmap_ros) is incomplete for noetic. 

New structure tutorial will help lots.
Is there any new documentation out there that can help? Thanks! @matlabbe 

EDIT: The documentations for slam, odometry, etc are on the separate packages (like rtabmap_slam). I think it would be helpful if there is a notice in rtabmap_ros about the documentation for its individual packages, seeing that rtabmap_ros is now just a metapackage.

**Comment by matlabbe** [comment]
Working on it! Just added this migration guide: http://wiki.ros.org/rtabmap_ros/noetic_and_newer#Migration_Guide_New_Interface_Noetic.2FROS2

I'll migrate the documentation

**Comment by antoniskara** [comment]
I faced the same issue. Using rtabmap noetic, after a new build ,all my scripts stopped working. Seems like there are missing files from /ros/opt/noetic/share/rtabmap_ros. More specifically the files missing are : rviz_plugins.xml , nodelet_plugins.xml costmap_plugins.xml msg srv

**Comment by matlabbe** [comment]
See the [link](http://wiki.ros.org/rtabmap_ros#rtabmap_ros.2Fnoetic_and_newer.Migration_Guide_New_Interface_Noetic.2FROS2) of my previous post. These files have been moved in new sub packages, changing `rtabmap_ros` prefix to new package name of the nodelet/costmap plugin.
