### ISSUE TITLE
Load 2d map

### ISSUE THREAD

**Issue by TakahikoHasegawa03** [introlab/rtabmap_ros#954]
Is there a way to load a map that you created in rviz in localisation mode?

I’ve created a map and have .db file and now want to load this in 2d so that I can see it from top view before starting localisation mode. Can we do that in Rviz? 

I’m using galactic ros2

**Comment by matlabbe** [comment]
rtabmap node should publishes the 2D occupancy grid when launching in localization mode, so in rviz add Map display to show it.
