### ISSUE TITLE
No tf link is being published from icp_odometry node.

### ISSUE THREAD

**Issue by zafaryab-a** [introlab/rtabmap_ros#972]
As mentioned "When external odometry is used, tf output is the correction of the external odometry tf so that both transforms can be in the same tf tree (i.e., /odom icp→/odom→/base link)". I was expecting same to be published by icp_odometry  node but it is not publishing these link.
Also on disabling external odometry it is not publishing /odom->base_link tf. 
However odometry is being published on topic in both cases.
Note : I have set "publish_tf" to true.

**Comment by zafaryab-a** [comment]
It is resolved.
The map->odom tf have to changed to map->odom_icp .
Thanks

**Comment by zafaryab-a** [comment]
It is resolved.
The map->odom tf have to changed to map->odom_icp .
Thanks

**Comment by zafaryab-a** [comment]
It is resolved.
The map->odom tf have to changed to map->odom_icp .
But The tf of odom_icp->odom as well as data at /odom_icp is being published at the rate of 1.2Hz, That is very slow.
How to increase this frequency.

**Comment by matlabbe** [comment]
The frame rate will depend on how much data the LiDAR is producing and the computer used. For example, `Icp/VoxelSize` can be increased to downsample the LiDAR scans.
