### ISSUE TITLE
FATAL error occurs.. related to covariance

### ISSUE THREAD

**Issue by huma0605** [introlab/rtabmap_ros#974]
I am seeing the same issue as in https://github.com/introlab/rtabmap_ros/issues/779. Everything was working fine when localization = false. But when we set it to be true, we saw the same g2o error. Below is my package versions
```
Package: ros-noetic-rtabmap-ros
Version: 0.21.1-4focal.20230416.011814
```
```
Package: ros-noetic-pcl-ros
Version: 1.7.4-1focal.20230216.065759
```
```
Package: ros-noetic-libg2o
Version: 2020.5.3-1focal.20210424.015120
```
All the installations were done through simply
```
sudo apt-install rod-noetic-rtabmap-ros
```

I am working on Jetson and thus the cpu arch is aarch64.

**Comment by matlabbe** [comment]
It is closed? did you fix it?
