### ISSUE TITLE
Weird behaviour in the case of Kidnapped robot

### ISSUE THREAD

**Issue by rakshith95** [introlab/rtabmap_ros#979]
Hello, 
In an earlier version of rtabmap_ros that I was using, in the case of the robot starting from a different position than where the last rtabmap session ended, there was no output to the `/rtabmap/localization_pose` topic until a loop closure was found, or manually initialized.

In the current version, the last pose of the previous session is output to `/rtabmap/localization_pose`, and is continually published until a loop closure is found and it corrects itself. I was using the lack of output to the `localization_pose` topic to run some global localization as initialization, but now that logic doesn't work.

 Is there some parameter which I can control for this?

**Comment by matlabbe** [comment]
`rtabmap/lcoalization_pose` is now always published to see the covariance increasing (based on odometry covariance) when it doesn't localize for a while. The localization covariance will shrink when a localization happens. 

To detect the first localization, you can subscribe to [/rtabmap/info](http://docs.ros.org/en/noetic/api/rtabmap_msgs/html/msg/Info.html) topic, and check if `loopClosureId`, `proximityDetectionId` or `landmarkId` is not zero. The disadvantage is that you need to subscribe to another topic.

Currently, the localization covariance is initialized with [first odometry covariance received](https://github.com/introlab/rtabmap/blob/af481fc73074ae13faaa08511ee6d5e36e805b65/corelib/src/Rtabmap.cpp#L1697), but I would prefer initialize with very large covariance (>99) until a first localization is detected. That could be another way to avoid subscribing to a second topic to know when the first localization happens. I'll check this this week.

**Comment by rakshith95** [comment]
Ah I see. What was the reason behind this particular change? It made sense (to me) that  when there was no localization, there was no output to the `rtabmap/localization_pose`

**Comment by matlabbe** [comment]
Always publishing is useful to know what is the current localization error. If you don't localize for a while, the localization covariance will increase. By looking at the covariance, you could know that at some point, you may consider the robot not localized.

I am adding back the old policy, with a new parameter called `pub_loc_pose_only_when_localizing` for rtabmap node. When setting to true, the `rtabmap/localization_pose` will published only when the robot localize (like before). I need to wait for rtabmap's CI to catch up, then I'll merge the new change.

**Comment by rakshith95** [comment]
Alright, thank you. `pub_loc_pose_only_when_localizing`  should be enough for my use case.  

>  By looking at the covariance, you could know that at some point, you may consider the robot not localized.

Wrt this, at what values of the covariances , could you consider the robot as not localized? 

For eg, 
I have covariance:
 ` covariance: [0.00028933980596532335, 2.0734064656530713e-06, 7.598683746486759e-07, 4.7123242513039355e-08, -5.777939068016851e-05, 0.0001568296197007322, 2.0734064656530713e-06, 0.0002773526456441461, -4.452877035192713e-06, 5.683397062097115e-05, -4.0217933942938536e-08, 2.6464146902444794e-05, 7.598683746486759e-07, -4.4528770351927135e-06, 0.0002877751095723878, -0.00015407371500342427, -2.6322948606752522e-05, -6.858001758779642e-09, 4.712324251303918e-08, 5.683397062097115e-05, -0.00015407371500342427, 0.0020022415143231297, -2.122025691918343e-06, -2.0574967662305545e-07, -5.7779390680168504e-05, -4.021793394293861e-08, -2.632294860675252e-05, -2.122025691918345e-06, 0.002035632919534387, 1.56937823021323e-06, 0.00015682961970073218, 2.6464146902444794e-05, -6.858001758779697e-09, -2.0574967662305596e-07, 1.5693782302132352e-06, 0.002034338838584304]
`
and 
`rtabmap/info/loopClosureId: 0`
`rtabmap/info/proximityDetectionId: 0`
`rtabmap/info/landmarkId: 0`

which I assume means it is not localized. So are these covariance values considered large?

**Comment by matlabbe** [comment]
Added `pub_loc_pose_only_when_localizing` to master branch.

Covariance values are small, you may consider it localized at that time. The threshold at which the robot is not localized would be dependent on the application and the scale of the environment. Having 1 meter error on a football field may be considered localized while in an house it may not. For convenience with rtabmap_viz, you can plot the localization error over time (`Loop/MapToBase_lin_std/m`) in Statistics panel.

**Comment by rakshith95** [comment]
This works, thank you!  Closing this issue
