### ISSUE TITLE
/usr/bin/ld: warning: libsl_zed.so, needed by /usr/local/lib/librtabmap_core.so.0.21.1, not found (try using -rpath or -rpath-link)

### ISSUE THREAD

**Issue by Rubeshthirumani** [introlab/rtabmap_ros#982]
am building in jetson nano, ros melodic. (rtabmap_ros catkin_make issues with zed library).

**Comment by matlabbe** [comment]
It seems that `libsl_zed.so` is not on the LD_LIBRARY_PATH. If you are using ROS, you may also not build rtabmap library with ZED -> `cmake -DWITH_ZED=OFF`

**Comment by Rubeshthirumani** [comment]
I still didn't try that. But solved with this method [https://community.stereolabs.com/t/usr-bin-ld-warning-libsl-zed-so-needed-by-usr-local-lib-librtabmap-core-so-0-21-1-not-found-try-using-rpath-or-rpath-link/2793/4?u=thiru](url)

**Comment by matlabbe** [comment]
Humm, maybe RTABMapConfig.cmake should look for ZED dependency, though libraries should be private inside rtabmap. I'll give a try.

**Comment by matlabbe** [comment]
retested on intel computer, it should compile/link correctly even if rtabmap library has been built with zed support. At worst, set explicitly the LD_LIBRARY_PATH:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/zed/lib
```
